metadata/sf-prod/force-app/main/default/objects/Cadence_Task_Configuration__c/Cadence_Task_Configuration__c.object-meta.xml
<CustomObject>
    <description>Information about the reports and tasks created by the report within the task dispatcher</description>
    <label>Cadence Task Configuration</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cadence Task Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Cadence_Task_Configuration__c/fields/Report_ID__c.field-meta.xml
<CustomField>
    <fullName>Report_ID__c</fullName>
    <description>Report Id from the report that will be executed by the task dispatcher</description>
    <inlineHelpText>Report Id from the report that will be executed by the task dispatcher</inlineHelpText>
    <label>Report ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Cadence_Task_Configuration__c/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <description>SLA in days</description>
    <inlineHelpText>SLA in days</inlineHelpText>
    <label>SLA</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Cadence_Task_Configuration__c/fields/Task_Dispatcher__c.field-meta.xml
<CustomField>
    <fullName>Task_Dispatcher__c</fullName>
    <description>Task Dispatcher for which this mapping is part of</description>
    <inlineHelpText>Task Dispatcher for which this mapping is part of</inlineHelpText>
    <label>Task Dispatcher</label>
    <referenceTo>Task_Dispatcher__c</referenceTo>
    <relationshipLabel>Cadence Task Configurations</relationshipLabel>
    <relationshipName>Cadence_Task_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Next_Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Follow_Up_Date__c</fullName>
    <description>Next contact date agreed with the client.</description>
    <inlineHelpText>Next contact date agreed with the client.</inlineHelpText>
    <label>Next Follow Up Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>&apos;Product Family&apos; is required, please refer PB001 for details.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales process</businessProcess>
    <label>Sales</label>
</RecordType>

metadata/sf-prod/force-app/main/default/objects/Task_Dispatcher__c/Task_Dispatcher__c.object-meta.xml
<CustomObject>
    <label>Task Dispatcher</label>
    <nameField>
        <label>Task Dispatcher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Dispatchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Task_Dispatcher__c/fields/Assign_to_Users_in_a_Role__c.field-meta.xml
<CustomField>
    <fullName>Assign_to_Users_in_a_Role__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, the task dispatcher will ignore opportunity owners and create tasks to users in the specified roles using round-robin.</description>
    <inlineHelpText>If checked, the task dispatcher will ignore opportunity owners and create tasks to users in the specified roles using round-robin.</inlineHelpText>
    <label>Role-Based Assignment</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Task_Dispatcher__c/fields/Task_Timeout__c.field-meta.xml
<CustomField>
    <fullName>Task_Timeout__c</fullName>
    <label>Task Timeout Days</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Task_Dispatcher__c/fields/User_Role_ID__c.field-meta.xml
<CustomField>
    <fullName>User_Role_ID__c</fullName>
    <label>Salesforce User Role ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/User/fields/Product_Certifications__c.field-meta.xml
<CustomField>
    <fullName>Product_Certifications__c</fullName>
    <label>Product Assignments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/TaskDispatchUnitTests.cls
@isTest
private class TaskDispatchUnitTests {
    static final String MANAGER_PROFILE = 'Team Manager';
    static final String MANAGER_ROLE = 'Manager New Sales';
    static final String USER_PROFILE = 'System Administrator';

    @isTest static void taskWrapperTest() {
        String ASSERT_ERROR_MESSAGE = 'Tasks should be sorted according to their priority.';
        //Arrange
        List<TaskWrapper> toSortTaskWrapperList = new List<TaskWrapper>();
        Task t1 = new Task( Id = TestData.getFakeId(Task.getSObjectType()), Priority = '0');
        Task t2 = new Task( Id = TestData.getFakeId(Task.getSObjectType()), Priority = '2');
        Task t3 = new Task( Id = TestData.getFakeId(Task.getSObjectType()), Priority = '5');
        toSortTaskWrapperList = new TaskWrapper[]{new TaskWrapper(t1), new TaskWrapper(t2), new TaskWrapper(t3)};
        //Act
        toSortTaskWrapperList.sort();
        //Assert
        System.assert(toSortTaskWrapperList[0].tsk == t3, ASSERT_ERROR_MESSAGE);
        System.assert(toSortTaskWrapperList[1].tsk == t2, ASSERT_ERROR_MESSAGE);
        System.assert(toSortTaskWrapperList[2].tsk == t1, ASSERT_ERROR_MESSAGE);
    }

    @isTest static void taskDispatchSchedulerV2_E2E_Test() {
        //Arrange
        createTaskDispatcher();
        Opportunity testOpportunity = createOpportunityForTaskDispatcher();

        //Act
        Test.startTest();
        TaskDispatchSchedulerV2 scheduler = new TaskDispatchSchedulerV2(); // Just call the scheduler and wait for it's execution. It is better than the dummy 'i++' test
        scheduler.execute(null);
        Test.stopTest();

        //Assert
        List<Task> followUpTask = [SELECT Id, Subject FROM Task WHERE WhatId=:testOpportunity.Id];
        //tasks are not created out of working days
        Integer expected = TaskDispatchBatchV2.todayIsWorkingDay() ? 1 : 0;
        System.assertEquals(expected, followUpTask.size(), 'A tasks should be created.');
    }

    @isTest static void taskDispatchBatchV2_E2E_Test() {
        //Arrange
        createTaskDispatcher();
        Opportunity testOpportunity = createOpportunityForTaskDispatcher();

        //Act
        Test.startTest();
        TaskDispatchBatchV2 batch = new TaskDispatchBatchV2(); 
        Database.executeBatch(batch, 50);
        Test.stopTest();

        //Assert
        List<Task> followUpTask = [SELECT Id, Subject FROM Task WHERE WhatId=:testOpportunity.Id];
        //tasks are not created out of working days
        Integer expected = TaskDispatchBatchV2.todayIsWorkingDay() ? 1 : 0;
        System.assertEquals(expected, followUpTask.size(), 'A tasks should be created.');
    }
    
    @isTest static void taskDispatchBatchV2_E2E_Test_RoleBased() {
        //Arrange
        Task_Dispatcher__c taskDispatcher = createTaskDispatcher();
        taskDispatcher.Assign_to_Users_in_a_Role__c = true;
        update taskDispatcher;
        Opportunity testOpportunity = createOpportunityForTaskDispatcher();

        //Act
        Test.startTest();
        TaskDispatchBatchV2 batch = new TaskDispatchBatchV2(); 
        Database.executeBatch(batch, 50);
        Test.stopTest();

        //Assert
        List<Task> followUpTask = [SELECT Id, Subject FROM Task WHERE WhatId=:testOpportunity.Id];
        //tasks are not created out of working days
        Integer expected = TaskDispatchBatchV2.todayIsWorkingDay() ? 1 : 0;
        System.assertEquals(expected, followUpTask.size(), 'A tasks should be created.');
    }
    
    // Create an opportunity with the Next Follow Up Date = Today and an ISR as the Owner
    static Opportunity createOpportunityForTaskDispatcher() {
        Opportunity testOpportunity = TestData.createOpportunityForCPQDocument();
        User userManager = TestData.getUser(MANAGER_PROFILE);
        TestData.updateUserRole(userManager, MANAGER_ROLE);
        User user = TestData.getUser(USER_PROFILE, userManager);
        UserRole role = [SELECT ID, NAME 
                         FROM UserRole 
                         WHERE id IN ('00E2x000000cVXw','00E2x000000cXlE') 
                         LIMIT 1];
        user.Product_Certifications__c = testOpportunity.Product__c;
        update user;
        TestData.updateUserRole(user, role.name);
        testOpportunity.Next_Follow_Up_Date__c = Date.Today();
        testOpportunity.OwnerId = user.Id;
        testOpportunity.Description = 'ApexTest';
        update testOpportunity; 
        return testOpportunity;
    }

    static Task_Dispatcher__c createTaskDispatcher() {
        Task_Dispatcher__c taskDispatcher = new Task_Dispatcher__c(Name = 'Follow-Up Task Dispatcher', 
            Task_Timeout__c = 5, 
            User_Role_ID__c = '00E2x000000cVXw,00E2x000000cXlE');
        insert taskDispatcher;
        List<Cadence_Task_Configuration__c> reports = new List<Cadence_Task_Configuration__c>();
        reports.add(new Cadence_Task_Configuration__c(Name = 'a1', Task_Dispatcher__c = taskDispatcher.Id, 
            Report_ID__c = '00O2x000002BCj4EAG', SLA__c = 1));
        insert reports;
        return taskDispatcher;
    }
}