metadata/sf-prod/force-app/main/default/objects/Automation_Settings__c/Automation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Settings used to control on and off of PBs, Flows, Triggers etc.</description>
    <label>Automation Settings</label>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Automation_Settings__c/fields/Disable_All_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Disable_All_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable all triggers referencing this field in the entry point criteria.</description>
    <inlineHelpText>Disable all triggers referencing this field in the entry point criteria.</inlineHelpText>
    <label>Disable All Triggers</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Automation_Settings__c/fields/Disable_SObject_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_SObject_Trigger__c</fullName>
    <description>Disable trigger per SObject. Input SObject API names and separate by semicolon (;). For Example: Account;Opportunity</description>
    <inlineHelpText>Disable trigger per SObject. Input SObject API names and separate by semicolon (;). For Example: Account;Opportunity</inlineHelpText>
    <label>Disable SObject Trigger</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/TriggerHandler.cls
public with sharing class TriggerHandler {
  public String sobjectAPIName { get; private set; } 
  public Boolean disableAllTriggers { get; private set; }
  public Boolean disableSObjectTrigger { get; private set; }
  
  public TriggerHandler(String sobjectAPIName) {
    this.sobjectAPIName = sobjectAPIName;

    Automation_Settings__c settings = Automation_Settings__c.getInstance(UserInfo.getUserId());
    this.disableAllTriggers = settings.Disable_All_Triggers__c;
    this.disableSObjectTrigger = getDisableSObjectTrigger(settings);
  }

  private Boolean getDisableSObjectTrigger(Automation_Settings__c settings) {
    if(String.isBlank(settings.Disable_SObject_Trigger__c)) {
      return false;
    }

    return settings.Disable_SObject_Trigger__c.replace(' ', '').split(';').contains(this.sobjectAPIName);
  }

  public Boolean bypassTrigger() {
    return this.disableAllTriggers || this.disableSObjectTrigger;
  }
}