metadata/sf-prod/force-app/main/default/objects/Automation_Settings__c/Automation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Settings used to control on and off of PBs, Flows, Triggers etc.</description>
    <label>Automation Settings</label>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Automation_Settings__c/fields/Disable_All_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Disable_All_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable all triggers referencing this field in the entry point criteria.</description>
    <inlineHelpText>Disable all triggers referencing this field in the entry point criteria.</inlineHelpText>
    <label>Disable All Triggers</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Automation_Settings__c/fields/Disable_SObject_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_SObject_Trigger__c</fullName>
    <description>Disable trigger per SObject. Input SObject API names and separate by semicolon (;). For Example: Account;Opportunity</description>
    <inlineHelpText>Disable trigger per SObject. Input SObject API names and separate by semicolon (;). For Example: Account;Opportunity</inlineHelpText>
    <label>Disable SObject Trigger</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/TriggerHandlerTest.cls
@isTest
public with sharing class TriggerHandlerTest {
  @isTest
  public static void testEnableAllTriggers(){
    Test.startTest();

    Automation_Settings__c settings = new Automation_Settings__c();
    insert settings;
    
    TriggerHandler handler = new TriggerHandler('Account');
    
    System.assertEquals(false, handler.bypassTrigger(), 'All Triggers are enabled.');

    Test.stopTest();    
  }

  @isTest
  public static void testDisableAllTriggers(){
    Test.startTest();

    Automation_Settings__c settings = new Automation_Settings__c();
    settings.Disable_All_Triggers__c = true;
    insert settings;
    
    TriggerHandler handler = new TriggerHandler('Account;Opportunity');
    
    System.assertEquals(true, handler.bypassTrigger(), 'Triggers should be bypassed.');

    Test.stopTest();    
  }

  @isTest
  public static void testDisableSObjectTrigger(){
    Test.startTest();

    Automation_Settings__c settings = new Automation_Settings__c();
    settings.Disable_SObject_Trigger__c = 'Account;Opportunity';
    insert settings;
    
    TriggerHandler handler = new TriggerHandler('Account');
    
    System.assertEquals(true, handler.bypassTrigger(), 'Account Trigger should be bypassed.');

    Test.stopTest();    
  }
}