metadata/sf-prod/force-app/main/default/objects/ApexLogger__c/ApexLogger__c.object-meta.xml
<CustomObject>
    <description>Custom object to log apex exceptions for tracking and troubleshooting</description>
    <label>Apex Logger</label>
    <nameField>
        <displayFormat>Log-{000}</displayFormat>
        <label>ApexLogger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/ApexLogger__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>LAMBDA-64039 exception message generated during exception logging</description>
    <inlineHelpText>Error message generated during exception</inlineHelpText>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/ApexLogger__c/fields/Stack_Trace_String__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace_String__c</fullName>
    <description>LAMBDA-64039 Error stack trace string generated through exception</description>
    <inlineHelpText>Stack trace string generated during exception</inlineHelpText>
    <label>Stack Trace String</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/AR_Quote__c.field-meta.xml
<CustomField>
    <fullName>AR_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>We have two quotes: 1) Offer quote - what we want the customer to sign. 2) Auto-Renewal quote - what will be the default pricing if the customer doesn&apos;t sign. This field stores a reference to the AR Quote.</description>
    <inlineHelpText>Auto-Renewal Quote will be used if customer doesn&apos;t sign the primary quote and includes AR pricing. If we go to auto-renewal this quote will replace the Primary Quote.</inlineHelpText>
    <label>AR Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities (AR Quote)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/CurrentContractHasAutoRenewalClause__c.field-meta.xml
<CustomField>
    <fullName>CurrentContractHasAutoRenewalClause__c</fullName>
    <description>Indicates if the customer&apos;s last signed quote contained the auto-renewal clause and hence we can enforce auto-renewal.</description>
    <inlineHelpText>If the last signed contract/quote contained the AR clause, then set to YES and put a link to the document into the &quot;Previous Quote with AR Cluse&quot; field. If last signed quote did not have the AR clause or quote can&apos;t be located, then set to NO. Auto-Renewal is only possible if there is a previously signed contract/quote with an AR clause.</inlineHelpText>
    <label>Has Auto-Renewal Clause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Customer_Termination_Notice_Period__c.field-meta.xml
<CustomField>
    <fullName>Customer_Termination_Notice_Period__c</fullName>
    <description>LAMBDA-60525 Field to capture number of days before renewal date the customer must notify of cancellation</description>
    <inlineHelpText>Specify the number of days before renewal date customer must notify of cancellation</inlineHelpText>
    <label>Customer Termination Notice Period</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <inlineHelpText>What happened?  See Loss Reason - Why to note any additional reasons WHY it happened?</inlineHelpText>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Company Acquired</fullName>
                <label>Company Acquired/Tech Stack Consolidation</label>
            </value>
            <value>
                <fullName>Contract Terms &amp; Conditions</fullName>
                <label>Contract terms &amp; conditions</label>
            </value>
            <value>
                <fullName>Data Quality</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Finance Action</fullName>
            </value>
            <value>
                <fullName>Inactive Account</fullName>
            </value>
            <value>
                <fullName>Lack of ROI</fullName>
            </value>
            <value>
                <fullName>Lost to Competitor</fullName>
            </value>
            <value>
                <fullName>Min seats is too high</fullName>
            </value>
            <value>
                <fullName>No Budget / Lost Funding</fullName>
            </value>
            <value>
                <fullName>No Decision / Non-Responsive</fullName>
            </value>
            <value>
                <fullName>Not Using Product</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Pre-Import</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Product Issues</fullName>
            </value>
            <value>
                <fullName>Product Shutdown</fullName>
            </value>
            <value>
                <fullName>Professional Services Issues</fullName>
            </value>
            <value>
                <fullName>Project Postponed/Canceled</fullName>
            </value>
            <value>
                <fullName>Sales/Billing Issues</fullName>
            </value>
            <value>
                <fullName>Security Review Failure</fullName>
            </value>
            <value>
                <fullName>Support issues</fullName>
            </value>
            <value>
                <fullName>Handled by the BU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Loss_Reason_Notes__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason_Notes__c</fullName>
    <description>Loss reason detailed notes populated by sales when an opportunity is Closed Lost</description>
    <inlineHelpText>Loss reason detailed notes populated by sales when an opportunity is Closed Lost</inlineHelpText>
    <label>Loss Reason Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Configuration</label>
    <referenceTo>Product_Configuration__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>This is the quote that will be processed and sent to the customer when you move the opportunity to Final Quote. Opportunity products and all the calculations are based on this quote.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/Product_Configuration__c.object-meta.xml
<CustomObject>
    <label>Product Configuration</label>
    <nameField>
        <label>Product Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Mailbox_Override__c.field-meta.xml
<CustomField>
    <fullName>Mailbox_Override__c</fullName>
    <description>Email domain to use for Outreach sequences, system emails to customers sent via Salesforce, and for PostGrid to send AR warning letters to customers. NetSuite adds a CC recipient automatically for all agreements of renewal Quotes (CC to &quot;renewals@OutboundEmailDomain&quot;). This value can ONLY be changed from NetSuite and it&apos;s automatically synchronized here!</description>
    <inlineHelpText>Email domain to use for Outreach sequences, system emails to customers sent via Salesforce, and for PostGrid to send AR warning letters to customers. NetSuite adds a CC recipient automatically for all agreements of renewal Quotes (CC to &quot;renewals@OutboundEmailDomain&quot;). This value can ONLY be changed from NetSuite and it&apos;s automatically synchronized here!</inlineHelpText>
    <label>Outbound Email Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Renewal_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specify if the renewal service is running for the product family (disable certain automation processes when false)</description>
    <inlineHelpText>Specify if the renewal service is running for the product family (disable certain automation processes when false)</inlineHelpText>
    <label>Renewal Enabled</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/TestBatchRenewalmpendingEmailSender.cls
@isTest
public class TestBatchRenewalmpendingEmailSender {
    @TestSetup
    static void makeData() {
        TestData.createOpportunityForCPQDocument('Renewal','ACRM');
        TestData.createDummyTemplate(true);                                    
    }
    @isTest static void testBatchwithValidOpportunity() {
        // Prepare Test Data
        OpportunityQBDisable.execute();
        Opportunity testOpp = [SELECT Id, Renewal_Date__c, CloseDate,Customer_Termination_Notice_Period__c,
                                SBQQ__PrimaryQuote__c,AR_Quote__c,Product_Configuration__c 
                                FROM Opportunity Limit 1];
        testOpp.Renewal_Date__c = Date.today()+44;
        testOpp.CloseDate = Date.today()+10;
        testOpp.CurrentContractHasAutoRenewalClause__c = 'Yes';
        testOpp.Customer_Termination_Notice_Period__c = 0;
        testOpp.AR_Quote__c = testOpp.SBQQ__PrimaryQuote__c;
        update testOpp;
        Product_Configuration__c config = new Product_Configuration__c(
                                            Id=testOpp.Product_Configuration__c,
                                            Mailbox_Override__c='ignitetech.com',
                                            Renewal_Enabled__c=true);
        update config;
        // Start the test
        Test.startTest();
        BatchRenewalmpendingEmailSender batchInstance = new BatchRenewalmpendingEmailSender();
        Database.executeBatch(batchInstance,1);
        Test.stopTest();
        List<ApexLogger__c> lstLogs = [SELECT Id,Exception_Message__c,Stack_Trace_String__c from ApexLogger__c];
        String error ='';
        if(lstLogs!=null && !lstLogs.isEmpty()) {
            error+='Error message:'+lstLogs[0].Exception_Message__c+'\n';
            error+='Stack Trace: '+lstLogs[0].Stack_Trace_String__c;
        }
        System.assertEquals(0, lstLogs.size(),error);
        //Cannot assert emails in test class
        
    }
    @isTest static void testBatchWithInvalidOpportunity() {
        // Prepare Test Data
        OpportunityQBDisable.execute();
        Opportunity testOpp = [SELECT Id, Renewal_Date__c, CloseDate,
                                Customer_Termination_Notice_Period__c,Product_Configuration__c 
                                FROM Opportunity Limit 1];
        testOpp.Renewal_Date__c = Date.today()+44;
        testOpp.CloseDate = Date.today()+10;
        testOpp.CurrentContractHasAutoRenewalClause__c = 'Yes';
        testOpp.Customer_Termination_Notice_Period__c = 0;
        update testOpp;
        Product_Configuration__c config = new Product_Configuration__c(
                                            Id=testOpp.Product_Configuration__c,
                                            Mailbox_Override__c='ignitetech.com',
                                            Renewal_Enabled__c=true);
        update config;
        List<OpportunityContactRole> lstOCR = [SELECT Id,ContactId FROM OpportunityContactRole 
                                                WHERE opportunityId =:testOpp.Id
                                               AND isPrimary = true];
        delete lstOCR;
        // Start the test
        Test.startTest();
        BatchRenewalmpendingEmailSender batchInstance = new BatchRenewalmpendingEmailSender();
        Database.executeBatch(batchInstance,1);
        Test.stopTest();
        //Cannot assert emails in test class
    }
    @isTest static void testBatchWithSkippableOpportunity() {
        OpportunityQBDisable.execute();
        Opportunity testOpp = [SELECT Id, Renewal_Date__c, CloseDate,
                                Customer_Termination_Notice_Period__c,Product_Configuration__c 
                                FROM Opportunity Limit 1];
        testOpp.Renewal_Date__c = Date.today()+44;
        testOpp.Customer_Termination_Notice_Period__c = 0;
        testOpp.CloseDate = Date.today()+10;
        testOpp.CurrentContractHasAutoRenewalClause__c = 'Yes';
        testOpp.StageName='Finalizing';
        testOpp.Loss_Reason__c ='Product Issues';
        testOpp.Loss_Reason_Notes__c = 'Product Issues';
        update testOpp;
        Product_Configuration__c config = new Product_Configuration__c(
                                            Id=testOpp.Product_Configuration__c,
                                            Mailbox_Override__c='ignitetech.com',
                                            Renewal_Enabled__c=true);
        update config;
        // Start the test
        Test.startTest();
        BatchRenewalmpendingEmailSender batchInstance = new BatchRenewalmpendingEmailSender();
        Database.executeBatch(batchInstance,1);
        Test.stopTest();
        //Cannot assert emails in test class
    }
    @isTest static void testGeneralUtility() {
        Opportunity testOpp = [SELECT Id, OwnerId 
                                FROM Opportunity Limit 1];
        List<OpportunityChatterWrapper> lstChatterMsgs = new List<OpportunityChatterWrapper>();
        List<String> lstUserIds = new List<String>();
        lstUserIds.add(testOpp.OwnerId);
        OpportunityChatterWrapper ocw = new OpportunityChatterWrapper();
        ocw.opportunityId = testOpp.Id;
        ocw.userIds = lstUserIds;
        ocw.customMessage = 'Test Chatter Message';
        lstChatterMsgs.add(ocw);
        if(lstChatterMsgs!=null && !lstChatterMsgs.isEmpty()) {
            GeneralUtility.postChatterInBulk(lstChatterMsgs);
        }
        try{
            Integer i = 1/0;
        } catch(Exception ex) {
            GeneralUtility.logApexException(ex,'Test message');
        }
    }
}