metadata/sf-prod/force-app/main/default/objects/ApexLogger__c/ApexLogger__c.object-meta.xml
<CustomObject>
    <description>Custom object to log apex exceptions for tracking and troubleshooting</description>
    <label>Apex Logger</label>
    <nameField>
        <displayFormat>Log-{000}</displayFormat>
        <label>ApexLogger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Initiate_Renewal_Process__e/Initiate_Renewal_Process__e.object-meta.xml
<CustomObject>
    <description>LAMBDA-65516 Platform event to trigger initiate the renewal process and send out an introduction email</description>
    <label>Initiate Renewal Process</label>
    <pluralLabel>Initiate Renewal Process</pluralLabel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Initiate_Renewal_Process__e/fields/Opportunity_18_Digit_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_18_Digit_Id__c</fullName>
    <description>LAMBDA-65516 18 digit opportunity ID from which this platform event was generated</description>
    <label>Opportunity 18 Digit Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Last_Survey_URL__c.field-meta.xml
<CustomField>
    <fullName>Last_Survey_URL__c</fullName>
    <description>LAMBDA-65516 URL of the last survey sent related to this opportunity</description>
    <inlineHelpText>Invitation of the survey last sent on this opportunity</inlineHelpText>
    <label>Last Survey URL</label>
    <type>Url</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Opportunity_18_Digit_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_18_Digit_Id__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity 18 Digit Id</label>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>&apos;Product Family&apos; is required, please refer PB001 for details.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Configuration</label>
    <referenceTo>Product_Configuration__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/Product_Configuration__c.object-meta.xml
<CustomObject>
    <label>Product Configuration</label>
    <nameField>
        <label>Product Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Intro_Survey__c.field-meta.xml
<CustomField>
    <fullName>Intro_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LAMBDA-65516 Field to capture link to the welcome survey record</description>
    <inlineHelpText>Related welcome Survey to be sent in intro email</inlineHelpText>
    <label>Intro Survey</label>
    <referenceTo>Survey</referenceTo>
    <relationshipLabel>Product Configurations</relationshipLabel>
    <relationshipName>Product_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Mailbox_Override__c.field-meta.xml
<CustomField>
    <fullName>Mailbox_Override__c</fullName>
    <description>Email domain to use for Outreach sequences, system emails to customers sent via Salesforce, and for PostGrid to send AR warning letters to customers. NetSuite adds a CC recipient automatically for all agreements of renewal Quotes (CC to &quot;renewals@OutboundEmailDomain&quot;). This value can ONLY be changed from NetSuite and it&apos;s automatically synchronized here!</description>
    <inlineHelpText>Email domain to use for Outreach sequences, system emails to customers sent via Salesforce, and for PostGrid to send AR warning letters to customers. NetSuite adds a CC recipient automatically for all agreements of renewal Quotes (CC to &quot;renewals@OutboundEmailDomain&quot;). This value can ONLY be changed from NetSuite and it&apos;s automatically synchronized here!</inlineHelpText>
    <label>Outbound Email Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/RenewalCadenceTracker__c/RenewalCadenceTracker__c.object-meta.xml
<CustomObject>
    <description>Custom object for tracking renewal email candences.</description>
    <label>Renewal Cadence Tracker</label>
    <nameField>
        <label>RCT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Renewal Cadence Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/RenewalCadenceTracker__c/fields/Actual_Email_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Email_Date__c</fullName>
    <label>Actual Email Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/RenewalCadenceTracker__c/fields/Email_Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Email_Scheduled_Date__c</fullName>
    <label>Email Scheduled Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/RenewalCadenceTracker__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>CadenceOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/RenewalCadenceTracker__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Errored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/RenewalCadenceTracker__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <label>Templateid</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SurveyInvitation/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LAMBDA-65691 Related opportunity to this invitation</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/InitiateRenewalProcessHandler.cls
/***
* @description: LAMBDA-65516 process handler to send intro email on platform event creation
* */
public with sharing class InitiateRenewalProcessHandler {

    static List<ApexLogger__c> lstAllApexLogs = new List<ApexLogger__c>();
    static final string templateIdWithLink = [SELECT ID, Name FROM EmailTemplate 
                                              WHERE DeveloperName =: System.Label.IntroTemplateWithLink limit 1][0].Id ;
    static final string templateIdWithoutLink = [SELECT ID, Name FROM EmailTemplate 
                                                  WHERE 
                                                    DeveloperName =: System.Label.IntroTemplateWithoutLink limit 1][0].Id;
    static final List<String> defaultErrorRecepients = new List<String>{'0052x0000049ZXCAA2','0052x000003dkbXAAQ'};
    static final string communityId = [SELECT ID,name from Network WHERE Name = 'Customer Portal'].Id;
    public static void handleEventInsert (List<Initiate_Renewal_Process__e> lstNewList) {
        Savepoint sp = Database.setSavepoint();
        Set<Id> oppyIdsToProcess = new Set<Id>();
        try {
            if(lstNewList!=null && !lstNewList.isEmpty()) {
                for(Initiate_Renewal_Process__e irp : lstNewList) {
                    if(irp.Opportunity_18_Digit_Id__c!=null) {
                        oppyIdsToProcess.add(irp.Opportunity_18_Digit_Id__c);
                    }
                }
            }
            System.debug('==oppyIdsToProcess=='+oppyIdsToProcess);
            if(oppyIdsToProcess!=null && !oppyIdsToProcess.isEmpty()) {
                processOpportunities(oppyIdsToProcess);
            }
        } catch (Exception ex) {
            Database.rollback(sp);
            System.debug('==exception occurred=='+ex.getMessage());
             GeneralUtility.postToRecord(defaultErrorRecepients[0],
                                        defaultErrorRecepients,
                                        'Errored oppies: '+ex.getMessage()+oppyIdsToProcess);
        } 
    }
    @testVisible
    private static void processOpportunities(Set<Id> opportunityIds) {
        List<SurveyInvitation> lstSurInvToIns = new List<SurveyInvitation>();
        List<Opportunity> lstOppToUpdate = new List<Opportunity>();
        List<Opportunity> lstValidOpportunities = new List<Opportunity>();
        List<RenewalCadenceTracker__c> lstTrackerRecords = new List<RenewalCadenceTracker__c>();
        //query opportunities to process
        List<Opportunity> lstOpportunityToProcess = [SELECT Id, Account.Name, Name, Product__c,StageName,
                                            Product_Configuration__r.Intro_Survey__c,
                                            Product_Configuration__c,Product_Configuration__r.Mailbox_Override__c,
                                            Last_Survey_URL__c,
                                            (SELECT Id, contact.Email, contactId From 
                                            OpportunitycontactRoles WHERe isPrimary=true
                                            and contact.Email!=null),
                                            Owner.email,Owner.Name
                                            from Opportunity WHERE Id IN :opportunityIds 
                                            and Product__c!=null and isClosed=false and StageName!='Pending' 
                                            and Id NOT IN (SELECT OpportunityId from 
                                            OpportunityPartner WHERE AccountToId!=null)
                                            and type = 'Renewal' and Last_Survey_URL__c=null
                                            and Owner.UserRole.Name = 'ISR Renewals'
                                           ];
        System.debug('==lstOpportunityToProcess=='+lstOpportunityToProcess);
        
        lstValidOpportunities = validateOpportunities(lstOpportunityToProcess);
        System.debug('==lstValidOpportunities=='+lstValidOpportunities);
        if(lstValidOpportunities==null || lstValidOpportunities.isEmpty()) {
            return;
        }
        for(Opportunity opp: lstValidOpportunities) {
            if(opp.Product_Configuration__c!=null && 
               opp.Product_Configuration__r.Intro_Survey__c!=null) {
               //generate survey invitation
               lstSurInvToIns.add(generateSurveyInvitation(opp));
               lstTrackerRecords.add(generateCadenceRec(opp,templateIdWithLink,Date.Today()));  
               } else{
                   Opportunity tempOpp = new Opportunity(
                                   Id=opp.Id,
                                   Last_Survey_URL__c = 'https://localhost'
                   );
                   lstOppToUpdate.add(tempOpp);
                   lstTrackerRecords.add(generateCadenceRec(opp,templateIdWithoutLink,Date.Today())); 
               }
        }
        if(lstSurInvToIns!=null && !lstSurInvToIns.isEmpty()) {
            insert lstSurInvToIns;
            lstOppToUpdate.addAll(updateSurveyURLS(lstSurInvToIns));
        }
        if(lstOppToUpdate!=null && !lstOppToUpdate.isEmpty()) {
            update lstOppToUpdate;
            sendEmails(lstValidOpportunities);
        }
        if(lstTrackerRecords!=null && !lstTrackerRecords.isEmpty()) {
            insert lstTrackerRecords;
        }
        
    }
    @testVisible
    private static SurveyInvitation generateSurveyInvitation(Opportunity opp) {
        SurveyInvitation surInv = new SurveyInvitation();
        surInv.SurveyId = opp.Product_Configuration__r.Intro_Survey__c;
        surInv.ParticipantId = opp.OpportunitycontactRoles[0].contactId;
        surInv.OptionsAllowParticipantAccessTheirResponse = false;
        surInv.OptionsCollectAnonymousResponse = false;
        surInv.OptionsAllowGuestUserResponse = true;
        surInv.Opportunity__c = opp.Id;
        surInv.CommunityId = communityId;
        surInv.Name = opp.OpportunitycontactRoles[0].contact.email;
        return surInv;
    }
    private static void sendEmails(List<Opportunity> lstOpportunity) {
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        for(Opportunity opp : lstOpportunity) {
            String templateId =templateIdWithoutLink;
            if(opp.Product_Configuration__r.Intro_Survey__c!=null) {
                templateId = templateIdWithLink;
            }
            Messaging.SingleEmailMessage email = generateEmail(opp, templateId);
            if(email != null) {
                emails.add(email);
            }
        } 
    if(emails!=null && !emails.isEmpty()) {
            Messaging.sendEmail(emails);
        }        
    }
    private static Messaging.SingleEmailMessage generateEmail (Opportunity opp, Id templateId) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            // Retrieve the OrgWideEmailAddress using product configuration
            Id fromEmailId = GeneralUtility.getOrgWideEmailIdbyName(opp.Product_Configuration__r.Mailbox_Override__c);
            mail.setOrgWideEmailAddressId(fromEmailId);
            Id primaryContactId;
            List<String> toAddresses = new List<String>();
            List<String> ccAddresses = new List<String>();
            toAddresses.add(opp.OpportunityContactRoles[0].Contact.Email);
            primaryContactId = opp.OpportunityContactRoles[0].contactId;
            mail.setToAddresses(toAddresses);
            ccAddresses.add(opp.Owner.Email);
            mail.setCcAddresses(ccAddresses);
            mail.setTemplateId(templateId);
            mail.setWhatId(opp.Id);
            mail.setTargetObjectId(primaryContactId);
            mail.setSaveAsActivity(true);
            mail.setTreatTargetObjectAsRecipient(false);
            // Send Email
        return mail;
    }
    @testVisible
    private static List<Opportunity> updateSurveyURLS(List<SurveyInvitation> lstSurveyInvs) {
        Map<Id,SurveyInvitation> mapSurveyInvs = new Map<Id,SurveyInvitation>(lstSurveyInvs);
        List<Opportunity> lstOpportunityToUpdate = new List<Opportunity>();
        List<SurveyInvitation> lstSurveyInvsToQuery = [SELECT Id, Opportunity__c, InvitationLink  
                                                       from SurveyInvitation WHERE ID In: mapSurveyInvs.keySet()];
        for(SurveyInvitation survInv : lstSurveyInvsToQuery) {
            Opportunity tempOpp = new Opportunity(Id=survInv.Opportunity__c,
                                                  Last_Survey_URL__c = survInv.InvitationLink);
            lstOpportunityToUpdate.add(tempOpp);
        }
        return lstOpportunityToUpdate;
    }
    @testVisible
    private static List<Opportunity> validateOpportunities(List<Opportunity> lstOpportunityToValidate) {
        List<Opportunity> lstValidOpportunity = new List<Opportunity>();
        List<OpportunityChatterWrapper> lstChatterMsgs = new List<OpportunityChatterWrapper>();
        List<String> lstUserIds = new List<String>();
        lstUserIds.addAll(defaultErrorRecepients);
        for(Opportunity opp: lstOpportunityToValidate) {
            Boolean isValid = true;
            String message = '';
            if(opp.OpportunitycontactRoles==null || opp.OpportunitycontactRoles.isEmpty()) {
            //add chatter message primary contact missing
              isValid = false;
                message +='The first email from the renewal sequence - "Critical: '+opp.Account.Name;
                message += '- Your Contact for '+ opp.Product__c+' Renewal" ';
                message += 'was not sent out because a Primary Contact with a valid email was not found. '; 
                message += 'The email sending will be reattempted once the primary contact has been updated. @';
                message += opp.owner.Name+' please update the contact details asap.';
          }
            Id fromEmailId = GeneralUtility.getOrgWideEmailIdbyName(opp.Product_Configuration__r.Mailbox_Override__c);
            System.debug('==fromEmailId=='+fromEmailId);
            if(fromEmailId==null) {
                //add chatter
                isValid = false;
                message += 'Valid renewals mailbox not found';
            }
            if(isValid) {
                lstValidOpportunity.add(opp);
            }
            if(!isValid) {
                lstUserIds.add(opp.OwnerId);
                OpportunityChatterWrapper ocw = new OpportunityChatterWrapper();
                ocw.opportunityId = opp.Id;
                ocw.userIds = lstUserIds;
                ocw.customMessage = message;
                lstChatterMsgs.add(ocw);
            }
        }
        if(lstChatterMsgs!=null && !lstChatterMsgs.isEmpty()) {
            GeneralUtility.postChatterInBulk(lstChatterMsgs);
        }
        return lstValidOpportunity;
    }
    @testVisible
    private static RenewalCadenceTracker__c generateCadenceRec(Opportunity opp, Id templateId, Date scheduledDate) {
		RenewalCadenceTracker__c tracker = new RenewalCadenceTracker__c();
        try {
            tracker.Opportunity__c = opp.Id;
        	tracker.TemplateId__c = templateId;
            tracker.status__c = 'Sent';
            tracker.Email_Scheduled_Date__c = scheduledDate;
            tracker.Actual_Email_Date__c = scheduledDate;
            String name = opp.Name + '_' + templateId;
            tracker.Name = name.left(80).trim();
            
            
        } catch (Exception ex) {
            String message = 'Error occurred while creating tracker record ='+ex.getMessage() + ' oppId='+opp.Id;
            GeneralUtility.postToRecord(defaultErrorRecepients[0],
                                        defaultErrorRecepients,
                                        message);
        }
        System.debug('==tracker records=='+tracker);
		return tracker;        
    }
}