metadata/sf-prod/force-app/main/default/objects/Platinum_Offer_Item__c/Platinum_Offer_Item__c.object-meta.xml
<CustomObject>
    <description>Keeps platinum offer details for a product</description>
    <label>Platinum Offer Item</label>
    <nameField>
        <label>Platinum Offer Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platinum Offer Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Platinum_Offer_Item__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LAMBDA-53172 Flag to check whether it is active or not</description>
    <inlineHelpText>Active flag for the product item</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Platinum_Offer_Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>LAMBDA-53172 type of the category of the Platinum offering</description>
    <inlineHelpText>Category of the platinum offering</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Platinum_Offer_Item__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <description>LAMBDA-53172 capture the details of the service</description>
    <inlineHelpText>Service offered by this item</inlineHelpText>
    <label>Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Platinum_Offer_Item_Product__c/Platinum_Offer_Item_Product__c.object-meta.xml
<CustomObject>
    <description>LAMBDA-53172 Create the data objects and relationships required to capture platinum feedback and set up on Pivotal</description>
    <label>Platinum Offer Item Product</label>
    <nameField>
        <label>Platinum Offer Item Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platinum Offer Item Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Platinum_Offer_Item_Product__c/fields/Platinum_Offer_Item__c.field-meta.xml
<CustomField>
    <fullName>Platinum_Offer_Item__c</fullName>
    <description>LAMBDA-53172 Platinum offer item record related to the product</description>
    <inlineHelpText>Parent Platinum offer item related to the product</inlineHelpText>
    <label>Platinum Offer Item</label>
    <referenceTo>Platinum_Offer_Item__c</referenceTo>
    <relationshipLabel>Platinum Offer Item Products</relationshipLabel>
    <relationshipName>Platinum_Offer_Item_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Platinum_Offer_Item_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LAMBDA-53172 Product related to the platinum offer item</description>
    <inlineHelpText>Product related to platinum offer item</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Platinum Offers</relationshipLabel>
    <relationshipName>Platinum_Offer_Item_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule__c/QC_Rule__c.object-meta.xml
<CustomObject>
    <label>QC Rule</label>
    <nameField>
        <label>QC Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/QC_Rule__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Rules can be grouped into categories.  A QC Rule can belong to a single QC Rule Category. When LLM prompt gets constructed, the category prompt text comes before the rules that belong to that category.</description>
    <inlineHelpText>Rules can be grouped into categories.  A QC Rule can belong to a single QC Rule Category. When LLM prompt gets constructed, the category prompt text comes before the rules that belong to that category.</inlineHelpText>
    <label>Category</label>
    <referenceTo>QC_Rule_Category__c</referenceTo>
    <relationshipLabel>QC Rules</relationshipLabel>
    <relationshipName>QC_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <description>Context to use in the AI prompt</description>
    <inlineHelpText>Context to use in the AI prompt</inlineHelpText>
    <label>Context</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule__c/fields/Enforced_On__c.field-meta.xml
<CustomField>
    <fullName>Enforced_On__c</fullName>
    <label>Enforced On</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Work_Unit_Types</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule__c/fields/Grader_Type__c.field-meta.xml
<CustomField>
    <fullName>Grader_Type__c</fullName>
    <label>Grader Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>AutoAI</fullName>
                <default>true</default>
                <label>AutoAI</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule__c/fields/Grading_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Grading_Criteria__c</fullName>
    <description>Grading Criteria to use in the AI prompt</description>
    <inlineHelpText>Grading Criteria to use in the AI prompt</inlineHelpText>
    <label>Grading Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule__c/fields/Grading_Order__c.field-meta.xml
<CustomField>
    <fullName>Grading_Order__c</fullName>
    <description>Specifies a position of the rule in the final AI prompt (compared to other rules). A rule with a minimal number appears first in the prompt.</description>
    <inlineHelpText>Specifies a position of the rule in the final AI prompt (compared to other rules). A rule with a minimal number appears first in the prompt.</inlineHelpText>
    <label>Grading Order</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule_Category__c/QC_Rule_Category__c.object-meta.xml
<CustomObject>
    <description>QC rules can be placed into categories.</description>
    <label>QC Rule Category</label>
    <nameField>
        <label>QC Rule Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Rule Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/QC_Rule_Category__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <description>The contents of this field is used in the LLM prompt that evaluates the QC Rules associated with this QC Rule Category. The text goes before the rules and sets the context for the rest of the rules.</description>
    <inlineHelpText>The contents of this field is used in the LLM prompt that evaluates the QC Rules associated with this QC Rule Category. The text goes before the rules and sets the context for the rest of the rules.</inlineHelpText>
    <label>Prompt</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule_Result__c/QC_Rule_Result__c.object-meta.xml
<CustomObject>
    <label>QC Rule Result</label>
    <nameField>
        <label>QC Rule Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Rule Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/QC_Rule_Result__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category of the QC Rule</description>
    <formula>QC_Rule__r.Category__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Category of the QC Rule</inlineHelpText>
    <label>Category</label>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule_Result__c/fields/QC_Rule__c.field-meta.xml
<CustomField>
    <fullName>QC_Rule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>QC Rule</label>
    <referenceTo>QC_Rule__c</referenceTo>
    <relationshipLabel>QC Rule Results</relationshipLabel>
    <relationshipName>QC_Rule_Results</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule_Result__c/fields/QC_Scorecard__c.field-meta.xml
<CustomField>
    <fullName>QC_Scorecard__c</fullName>
    <label>QC Scorecard</label>
    <referenceTo>QC_Scorecard__c</referenceTo>
    <relationshipLabel>QC Rule Results</relationshipLabel>
    <relationshipName>QC_Rule_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Scorecard__c/QC_Scorecard__c.object-meta.xml
<CustomObject>
    <label>QC Scorecard</label>
    <nameField>
        <label>QC Scorecard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Scorecards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/QC_Scorecard__c/fields/QC_Summary__c.field-meta.xml
<CustomField>
    <fullName>QC_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>QC Summary</label>
    <referenceTo>QC_Summary__c</referenceTo>
    <relationshipLabel>QC Scorecards</relationshipLabel>
    <relationshipName>QC_Scorecards</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Summary__c/QC_Summary__c.object-meta.xml
<CustomObject>
    <description>Quality Check Summary object provides insights for a work unit, specifically it shows if work unit completed per defined quality. If some quality bars are not satisfied then comments provided with the explanation.</description>
    <label>QC Summary</label>
    <nameField>
        <label>QC Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/classes/PromptBuilder.cls
public with sharing class PromptBuilder extends IPromptBuilder {
    private static final String NO_RULES_TO_QC_FOUND = 'PromptBuilder.cls: No rules to QC found';
    private static final String NO_TRANSCRIPT_FOUND = 'PromptBuilder.cls: No transcript found for task: ';

    @TestVisible
    private class DataRecord {
        public String prefixName;
        public Id recordId;
        public Object value;

        public DataRecord(String prefixName, Id recordId, Object value) {
            this.prefixName = prefixName;
            this.recordId = recordId;
            this.value = value;
        }
        public DataRecord(String prefixName, Id recordId) {
            this.prefixName = prefixName;
            this.recordId = recordId;
            this.value = null;
        }
    }

    private IPromptRegistry m_promptRegistry;
    public PromptBuilder(IPromptRegistry promptRegistry) {
        this.m_promptRegistry = promptRegistry;
    }

    @TestVisible
    //prepares data for placeholders replacement
    private static List<PromptBuilder.DataRecord> prepareDataRecords(Id taskId, Id platinumOfferId) {
        Task task = [SELECT WhatId, What.Type, WhoId, Who.Type FROM Task WHERE Id = :taskId LIMIT 1];

        List<PromptBuilder.DataRecord> dataRecords = new List<PromptBuilder.DataRecord> {
            new PromptBuilder.DataRecord('Record', taskId)
        };
        if(task.Who.Type != null) {
            dataRecords.add(new PromptBuilder.DataRecord(task.Who.Type, task.WhoId));
        }
        if(task.What.Type != null) {
            dataRecords.add(new PromptBuilder.DataRecord(task.What.Type, task.WhatId));
        }

        //special handling for the Platinum Offers
        if(platinumOfferId != null) {
            dataRecords.add(new PromptBuilder.DataRecord('Platinum_Offer_Item__c', platinumOfferId));
        } else {
            List<Id> platinumOfferIds = getPlatinumOfferIDs(taskId);
            if(!platinumOfferIds.isEmpty()) {
                Map<String, Object> valueMap = new Map<String, Object>{
                    '$Custom' => new Map<String, Object>{'Platinum_Offer_Item__r' => platinumOfferIds}
                };
                dataRecords.add(new PromptBuilder.DataRecord('$Custom', null, valueMap));
            }
        }
        return dataRecords;
    }

    public override IPromptBuilder.QCJobDS prepareQCJobDS(Id recordId) {
        IPromptBuilder.QCJobDS ds = new IPromptBuilder.QCJobDS();
        ds.promptPrefix = m_promptRegistry.getQCTaskPromptPrefix();
        
        List<QC_Rule_Result__c> ruleResults = getRuleResultsForTask(recordId);
        if (ruleResults.isEmpty()) {
            System.debug(NO_RULES_TO_QC_FOUND);
            return null;
        }

        //prepare placeholder data records
        List<PromptBuilder.DataRecord> dataRecords = prepareDataRecords(recordId, null);

        ds.QCRules = new List<IPromptBuilder.QCRuleDS>();
        for (QC_Rule_Result__c ruleResult : ruleResults) {
            IPromptBuilder.QCRuleDS qcRule = new IPromptBuilder.QCRuleDS();
            qcRule.category = ruleResult.QC_Rule__r.Category__r.Name;
            qcRule.name = ruleResult.QC_Rule__r.Name;
            qcRule.context = PromptBuilder.replacePlaceholders(dataRecords, ruleResult.QC_Rule__r.Context__c);
            qcRule.gradingCriteria = 
                PromptBuilder.replacePlaceholders(dataRecords, ruleResult.QC_Rule__r.Grading_Criteria__c);
            ds.QCRules.add(qcRule);
        }
        
        String transcript = getTranscriptForTask(recordId);
        if (transcript == null) {
            String msg = NO_TRANSCRIPT_FOUND + recordId;
            throw new IPromptBuilder.NoTranscriptFoundException(msg);
        }
        ds.workData = transcript;
        ds.qcCategories = getQCCategories();
        return ds;
    }

    private List<IPromptBuilder.QCCategoryDS> getQCCategories() {
        List<QC_Rule_Category__c> categories = [SELECT Id, Name, Prompt__c FROM  QC_Rule_Category__c];
        List<IPromptBuilder.QCCategoryDS> qcCategories = new List<IPromptBuilder.QCCategoryDS>();
        for (QC_Rule_Category__c category : categories) {
            IPromptBuilder.QCCategoryDS qcCategoryDS = new IPromptBuilder.QCCategoryDS();
            qcCategoryDS.name = category.Name;
            qcCategoryDS.prompt = category.Prompt__c;
            qcCategories.add(qcCategoryDS);
        }
        return qcCategories;
    }

    public override IPromptBuilder.QCTaskPrompt prepareQcTaskPrompt(Id taskId) {

        String qcPrompt = m_promptRegistry.getQCTaskPromptPrefix() + '\n';

        List<QC_Rule_Result__c> ruleResults = getRuleResultsForTask(taskId);
        if (!ruleResults.isEmpty()) {
            System.debug('PromptBuilder.cls: Number of rules to QC: ' + ruleResults.size());
        } else {
            System.debug(NO_RULES_TO_QC_FOUND);
            return null;
        }

        for (QC_Rule_Result__c ruleResult : ruleResults) {
            //ignore the platinum offer rule, there will be a separate prompt for that
            if (ruleResult.QC_Rule__r.Name.contains(IPromptBuilder.PLATINUM_OFFER_RULE_NAME)) {
                continue;
            }
            qcPrompt += '\n\nRule Name: ' + ruleResult.QC_Rule__r.Name;
            if(String.isNotBlank(ruleResult.QC_Rule__r.Context__c)) {
                qcPrompt += '\nContext: ' + ruleResult.QC_Rule__r.Context__c;
            }
            qcPrompt += '\nGrading Criteria: ' + ruleResult.QC_Rule__r.Grading_Criteria__c;
        }

        String transcript = getTranscriptForTask(taskId);
        if(transcript == null) {
            String msg = NO_TRANSCRIPT_FOUND + taskId;
            throw new IPromptBuilder.NoTranscriptFoundException(msg);
        }

        //prepare placeholder data records and do the replacement
        List<PromptBuilder.DataRecord> dataRecords = prepareDataRecords(taskId, null);
        qcPrompt = PromptBuilder.replacePlaceholders(dataRecords, qcPrompt);

        //add transcript
        qcPrompt += '\n\n=== TRANSCRIPT===\n' + transcript;

        //prepare result
        IPromptBuilder.QCTaskPrompt qcPromptRes = new IPromptBuilder.QCTaskPrompt();
        qcPromptRes.scorecardId = ruleResults[0].QC_Scorecard__c;
        qcPromptRes.prompt = qcPrompt;
        qcPromptRes.ruleResults = ruleResults;
        return qcPromptRes;
    }

    public override IPromptBuilder.QCTaskPlatinumOfferPrompt preparePromptsToQcPlatinumOffers(Id taskId) {
        String qcPrefix = m_promptRegistry.getQCTaskPlatinumOfferPromptPrefix() + '\n';

        String transcript = getTranscriptForTask(taskId);
        if(transcript == null) {
            String msg = NO_TRANSCRIPT_FOUND + taskId;
            throw new IPromptBuilder.NoTranscriptFoundException(msg);
        }

        List<QC_Rule_Result__c> ruleResults = getRuleResultsForTask(taskId);
        if (!ruleResults.isEmpty()) {
            System.debug('PromptBuilder.cls: Number of rules to QC: ' + ruleResults.size());
        } else {
            System.debug(NO_RULES_TO_QC_FOUND);
            return null;
        }

        IPromptBuilder.QCTaskPlatinumOfferPrompt qcPromptRes = new IPromptBuilder.QCTaskPlatinumOfferPrompt();
        qcPromptRes.prompts = new List<String>();

        String promptTemplate = null;
        for (QC_Rule_Result__c ruleResult : ruleResults) {
            //search for the platinum discovery rule
            if (ruleResult.QC_Rule__r.Name.contains(IPromptBuilder.PLATINUM_OFFER_RULE_NAME)) {
                promptTemplate = '';
                if(String.isNotBlank(ruleResult.QC_Rule__r.Context__c)) {
                    promptTemplate += '\nContext: ' + ruleResult.QC_Rule__r.Context__c;
                }
                promptTemplate += '\nGrading Criteria: ' + ruleResult.QC_Rule__r.Grading_Criteria__c;
                qcPromptRes.ruleResult = ruleResult;
                break;
            }
        }

        if(promptTemplate == null) {
            System.debug('PromptBuilder.cls: there is no rule for platinum offer discovery');
            return null;
        }

        List<String> offerPrompts = replacePlatinumOfferRulePlaceholders(taskId, promptTemplate);
        if(offerPrompts.isEmpty()) {
            System.debug('PromptBuilder.cls: there are no offer items for the task (or no opp?) ' + taskId);
            return null;
        }

        for (String prompt : offerPrompts) {
            qcPromptRes.prompts.add(qcPrefix + prompt + '\n\n=== TRANSCRIPT===\n' + transcript);
        }
        return qcPromptRes;
    }

    @TestVisible
    private static string replacePlaceholders(List<DataRecord> dataRecords, String template) {
        Pattern placeholderPattern = Pattern.compile('\\$\\{([^}]+)\\}');
        Set<String> uniquePlaceholders = new Set<String>();

        Matcher matcher = placeholderPattern.matcher(template);
        while (matcher.find()) {
            uniquePlaceholders.add(matcher.group(0));
        }

        for (String placeholder : uniquePlaceholders) {
            String placeholderWithoutBraces = placeholder.substring(2, placeholder.length() - 1);
            String[] parts = placeholderWithoutBraces.split('\\.');
            String prefix = parts[0];

            DataRecord matchedRecord = findMatchingDataRecord(dataRecords, prefix);
            if (matchedRecord != null) {
                Object resolvedValue = resolvePlaceholderValue2(matchedRecord, placeholderWithoutBraces);
                if (resolvedValue instanceof String) {
                    template = template.replace(placeholder, (String) resolvedValue);
                }
            }
        }

        // Iterate construct replacement
        Pattern iteratePattern = Pattern.compile('(?s)<%iterate:\\s*([^%]+)\\s*%>(.*?)<%iterate_end%>');
        Matcher iterateMatcher = iteratePattern.matcher(template);

        while (iterateMatcher.find()) {
            String iteratePlaceholder = iterateMatcher.group(0);
            String iteratePath = iterateMatcher.group(1);
            String iterateContent = iterateMatcher.group(2);

            DataRecord iterateDataRecord = findMatchingDataRecord(dataRecords, iteratePath.split('\\.')[0]);
            if (iterateDataRecord != null) {
                List<Id> recordIDs = (List<Id>) resolvePlaceholderValue2(iterateDataRecord, iteratePath);
                if (recordIDs != null) {
                    String replacement = '';
                    Integer index = 1;
                    for (Id itemRecordId : recordIDs) {
                        List<DataRecord> itemDataRecords = new List<DataRecord> {
                            new DataRecord('$item', itemRecordId),
                            new DataRecord('$index', null, String.valueOf(index))
                        };
                        String iterationValue = replacePlaceholders(itemDataRecords, iterateContent);
                        replacement += iterationValue;
                        index++;
                    }
                    template = template.replace(iteratePlaceholder, replacement);
                }
            }
        }
        return template;
    }

    private static DataRecord findMatchingDataRecord(List<DataRecord> dataRecords, String prefix) {
        for (DataRecord dataRecord : dataRecords) {
            if (dataRecord.prefixName.equals(prefix)) {
                return dataRecord;
            }
        }
        return null;
    }

    private static Object resolvePlaceholderValue2(DataRecord dataRecord, String placeholderWithoutBraces) {
        if (dataRecord.value == null) {
            return resolvePlaceholderValue(dataRecord, placeholderWithoutBraces);
        }

        Object value = dataRecord.value;
        String[] parts = placeholderWithoutBraces.split('\\.');
        if (parts.size() > 1) {
            for (String part : parts) {
                if (value instanceof Map<String, Object>) {
                    value = ((Map<String, Object>)value).get(part);
                } else {
                    return null;
                }
            }
        }
        return value;
    }

    private static String resolvePlaceholderValue(DataRecord dataRecord, String placeholderWithoutBraces) {
        Id recordId = dataRecord.recordId;
        String objectName = recordId.getSObjectType().getDescribe().getName();
        String[] parts = placeholderWithoutBraces.split('\\.');

        String sanitizedFieldName = placeholderWithoutBraces
                .substring(parts[0].length() + 1)
                .replaceAll('[^a-zA-Z0-9_\\.]', '');

        String soql = 'SELECT ' + sanitizedFieldName + ' FROM ' + objectName + ' WHERE Id = \'' + recordId + '\'';
        try {
            SObject record = Database.query(soql);
            Object value = record;
            for (Integer i = 1; i < parts.size() - 1; i++) {
                value = ((SObject)value).getSObject(parts[i]);
            }
            Object val = ((SObject)value).get(parts[parts.size() - 1]);
            return String.valueOf(val);
        } catch (Exception e) {
            System.debug('PromptBuilder.cls: Unable to resolve value for ' + placeholderWithoutBraces);
            System.debug('PromptBuilder.cls: query is ' + soql);
            System.debug('PromptBuilder.cls: error is ' + e.getMessage());            
            return null;
        }
    }

    private static List<Id> getPlatinumOfferIDs(Id taskId) {

        Task task = [SELECT WhatId, What.Type, WhoId, Who.Type FROM Task WHERE Id = :taskId LIMIT 1];
        List<Platinum_Offer_Item_Product__c> offers = [
            SELECT
                Platinum_Offer_Item__r.Id
            FROM 
                Platinum_Offer_Item_Product__c 
            WHERE 
                Platinum_Offer_Item__r.Active__c = True 
                AND Product__c in (select Product2Id from OpportunityLineItem where OpportunityId = :task.WhatId)
            ORDER BY
                Platinum_Offer_Item__r.Service__c
        ];

        Set<Id> uniqueOfferIds = new Set<Id>();
        for (Platinum_Offer_Item_Product__c offer : offers) {
            uniqueOfferIds.add(offer.Platinum_Offer_Item__r.Id);
        }

        return new List<Id>(uniqueOfferIds);
    }

    private List<String> replacePlatinumOfferRulePlaceholders(Id taskId, String promptTemplate) {

        List<String> prompts = new List<String>();
        List<Id> uniqueOfferIds = getPlatinumOfferIDs(taskId);
        for (Id offerId : uniqueOfferIds) {
            List<PromptBuilder.DataRecord> dataRecords = prepareDataRecords(taskId, offerId);
            String prompt = PromptBuilder.replacePlaceholders(dataRecords, promptTemplate);
            prompts.add(prompt);
        }

        return prompts;
    }

    private List<QC_Rule_Result__c> getRuleResultsForTask(Id taskId) {

        Task task = [SELECT Work_Unit_Type__c, QC_Summary__c FROM Task WHERE Id = :taskId LIMIT 1];
        List<QC_Scorecard__c> qcScorecards = [
            SELECT Id 
            FROM QC_Scorecard__c 
            WHERE QC_Summary__c = :task.QC_Summary__c 
            ORDER BY CreatedDate DESC LIMIT 1
        ];
        if (qcScorecards.isEmpty()) {
            System.debug('PromptBuilder.cls: No scorecard found for ' + taskId);
            return new List<QC_Rule_Result__c>();
        }
        QC_Scorecard__c qcScorecard = qcScorecards[0];

        List<QC_Rule_Result__c> ruleResults = [
            SELECT
                QC_Scorecard__c,
                QC_Rule__r.Category__r.Name,
                QC_Rule__r.Name,
                QC_Rule__r.Context__c,
                QC_Rule__r.Grading_Criteria__c
            FROM 
                QC_Rule_Result__c 
            WHERE 
                QC_Scorecard__c = :qcScorecard.Id 
                and QC_Rule__r.Grader_Type__c = 'AutoAI'
                and QC_Rule__r.Enforced_On__c INCLUDES(:task.Work_Unit_Type__c)
            ORDER BY
                QC_Rule__r.Grading_Order__c,
                QC_Rule__r.Name
        ];

        return ruleResults;
    }

    private String getTranscriptForTask(Id taskId) {
        // Load the most recent transcript file content
        List<ContentDocumentLink> docLinks = [
            select 
                Id,
                LinkedEntityId,
                ContentDocument.Title,  
                ContentDocument.CreatedDate, 
                ContentDocument.LatestPublishedVersionId 
            from 
                ContentDocumentLink 
            where 
                LinkedEntityId = :taskId
                and ContentDocument.Title like '%-transcript.vtt.txt'
            order by 
                ContentDocument.CreatedDate desc
            limit 1
        ];

        String transcript = null;

        ContentDocumentLink docLink = docLinks.isEmpty() ? null : docLinks[0];
        if (docLink != null) {
            ContentVersion transcriptContent = [
                SELECT VersionData 
                FROM ContentVersion 
                WHERE Id = :docLink.ContentDocument.LatestPublishedVersionId
                LIMIT 1
            ];
            transcript = transcriptContent.VersionData.toString();
        }
        return transcript;
    }
}