metadata/sf-prod/force-app/main/default/objects/Initiate_Renewal_Process__e/Initiate_Renewal_Process__e.object-meta.xml
<CustomObject>
    <description>LAMBDA-65516 Platform event to trigger initiate the renewal process and send out an introduction email</description>
    <label>Initiate Renewal Process</label>
    <pluralLabel>Initiate Renewal Process</pluralLabel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Initiate_Renewal_Process__e/fields/Opportunity_18_Digit_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_18_Digit_Id__c</fullName>
    <description>LAMBDA-65516 18 digit opportunity ID from which this platform event was generated</description>
    <label>Opportunity 18 Digit Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>The field is checked when automation is enabled for the opportunity. Opportunity is active when it&apos;s not marked as Draft and the service for that opportunity type is enabled in Product Configuration. i.e. It&apos;s active when Renewal service is enabled and it&apos;s a Renewal opportunity.</description>
    <formula>IF( Text(Type) = &apos;Renewal&apos; ,
      AND(Product_Configuration__r.Renewal_Enabled__c, NOT(Draft__c)),
      IF(OR(Text(Type) = &apos;New Business&apos;, Text(Type) = &apos;Upsell&apos;), 
           AND(Product_Configuration__r.New_Business_Enabled__c , NOT(Draft__c)), 
             False))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The field is checked when automation is enabled for the opportunity. It depends on the Draft field and if a specific type of service is enabled in the Product Configuration.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Last_Survey_URL__c.field-meta.xml
<CustomField>
    <fullName>Last_Survey_URL__c</fullName>
    <description>LAMBDA-65516 URL of the last survey sent related to this opportunity</description>
    <inlineHelpText>Invitation of the survey last sent on this opportunity</inlineHelpText>
    <label>Last Survey URL</label>
    <type>Url</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Opportunity_18_Digit_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_18_Digit_Id__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity 18 Digit Id</label>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Primary_Contact_Changed__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Changed__c</fullName>
    <description>Date when the Primary contact was changed or set</description>
    <label>Primary Contact Changed</label>
    <type>DateTime</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>This is the quote that will be processed and sent to the customer when you move the opportunity to Final Quote. Opportunity products and all the calculations are based on this quote.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Quality_Bars_Configuration__c/Quality_Bars_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Quality Bars Configuration to enable and disable validation rules</description>
    <label>Quality Bars Configuration</label>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Quality_Bars_Configuration__c/fields/Disabled_Opportunity_QBs__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Opportunity_QBs__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true validation rules for the Opportunity object will be disabled</description>
    <inlineHelpText>If true validation rules for the Opportunity object will be disabled</inlineHelpText>
    <label>Disabled Opportunity QBs</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Reseller_Agreement__c/Reseller_Agreement__c.object-meta.xml
<CustomObject>
    <description>Reseller Agreement that a customer has with a subsidiary</description>
    <label>Reseller Agreement</label>
    <nameField>
        <displayFormat>RA# {0000}</displayFormat>
        <label>Reseller Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reseller Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Reseller_Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Account that signed the Reseller Agreement</description>
    <inlineHelpText>Account that signed the Reseller Agreement</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reseller Agreements</relationshipLabel>
    <relationshipName>Reseller_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Reseller_Agreement__c/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Subsidiary for which the Reseller Agreement was signed</description>
    <inlineHelpText>Subsidiary for which the Reseller Agreement was signed</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Reseller Agreements</relationshipLabel>
    <relationshipName>Reseller_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Out for Signature</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/fields/Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Subsidiary link set automatically when quote is created/updated</description>
    <inlineHelpText>Subsidiary link set automatically when quote is created/updated</inlineHelpText>
    <label>Service Provider</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>LAMBDA-34344 custom object to replace subsidiary fields on Product configuration with lookups</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/classes/OpportunityTriggerHandler.cls
/**
 * @author: Paras Dhingra
 * @description: Handler class for Opportunity trigger. All logic should be in this and triggers should be logicless
 */
public with sharing class OpportunityTriggerHandler {
    /**
    * description: LAMBDA-40414 Method to prevent users from moving opportunity to Final stage unless,
    *               Reseller Agreement is populated on related account if a partner exist.
    */
    public static void oppyValidations(Map<Id,Opportunity> mapNewOpportunity, Map<Id,Opportunity> mapOldOpportunity) {
        if(OpportunityTriggerHandler.currentUserHasByPass()) {
            return;
        }
        checkOpportunityPartners(mapNewOpportunity,mapOldOpportunity);
    }
    public static boolean currentUserHasByPass() {
        Quality_Bars_Configuration__c qualityBars = Quality_Bars_Configuration__c.getInstance();
        if(qualityBars!=null && qualityBars.Disabled_Opportunity_QBs__c) {
            return true;
        }
        return false;
    }
    private static void checkOpportunityPartners(Map<Id,Opportunity> mapNewOpportunity, Map<Id,Opportunity> mapOldOpportunity) {
        Set<Id> setOpportunitiesToQuery = new Set<Id>();
        for(Opportunity oppy: mapNewOpportunity.values()) {
            Opportunity oldOpportunity = mapOldOpportunity.get(oppy.Id);
            if(oppy.StageName!=oldOpportunity.StageName && oppy.StageName ==System.Label.FinalQuote) {
                setOpportunitiesToQuery.add(oppy.Id);
            }
        }
        if(setOpportunitiesToQuery!=null && !setOpportunitiesToQuery.isEmpty()) {
            Set<Id> accountsToGetAgreements = new Set<Id>();
            List<Opportunity> lstEligiblePartners = [SELECT Id, AccountId, Account.BillingAddress,
                                    Account.ShippingAddress, SBQQ__PrimaryQuote__r.Service_Provider__c,
                                    SBQQ__PrimaryQuote__r.SBQQ__Partner__c, SBQQ__PrimaryQuote__r.SBQQ__Distributor__c,
                                    (SELECT Id,AccountToId,AccountTo.BillingAddress,Role FROM OpportunityPartnersFrom
                                    WHERE Role IN ('VAR/Reseller','Distributor')) 
                                    FROM Opportunity WHERE Id IN:setOpportunitiesToQuery];
            if(lstEligiblePartners!=null && !lstEligiblePartners.isEmpty()) {
                for(Opportunity erroredOppy: lstEligiblePartners) {

                    // Validate opportunity partners are correct.
                    List<String> errors = validateOpportunityPartners(erroredOppy);
                    if (!errors.isEmpty()) {
                        // If not, add error(s). Stop processing this opportunity as it doesn't make sense to continue.
                        mapNewOpportunity.get(erroredOppy.Id).addError(String.join(errors, '\n'));
                        continue;
                    }

                    if (!erroredOppy.OpportunityPartnersFrom.isEmpty()) {
                        if (erroredOppy.SBQQ__PrimaryQuote__r.Service_Provider__c == null) {
                            mapNewOpportunity.get(erroredOppy.Id).addError(System.Label.ServiceProviderEmpty);
                        } else {
                            for(OpportunityPartner oppyPartner: erroredOppy.OpportunityPartnersFrom ) {
                                Boolean isPartnerAddressMissing = 
                                    isAddressMissingFields(oppyPartner.AccountTo.BillingAddress);
                                if(isPartnerAddressMissing) {
                                    mapNewOpportunity.get(erroredOppy.Id)
                                        .addError(System.Label.FinalQuoteBillingAddressError);
                                }
                                accountsToGetAgreements.add(oppyPartner.AccountToId);
                            }
                        }
                    }

                    if(erroredOppy.OpportunityPartnersFrom==null || erroredOppy.OpportunityPartnersFrom.isEmpty()) {
                        Boolean isAccountAddressMissing = isAddressMissingFields( erroredOppy.Account.BillingAddress );
                        
                        if(isAccountAddressMissing) {
                            mapNewOpportunity.get(erroredOppy.Id)
                                .addError(formatMessage('Billing',System.Label.FinalQuoteAccountAddressError));
                        }
                    }
                    Boolean isAccountShippingAddressMissing = isAddressMissingFields(erroredOppy.Account.ShippingAddress);
                    if(isAccountShippingAddressMissing) {
                        mapNewOpportunity.get(erroredOppy.Id)
                            .addError(formatMessage('Shipping',System.Label.FinalQuoteAccountAddressError));
                    }
                }
                
                if (!accountsToGetAgreements.isEmpty()) {
                    List<Reseller_Agreement__c> resellerAgreements = [SELECT Account__c,Subsidiary__c
                        FROM Reseller_Agreement__c WHERE Account__c IN:accountsToGetAgreements];
                    Map<Id,Set<Id>> accountToSubsidiaries = new Map<Id,Set<Id>>();
                    for (Reseller_Agreement__c agreement: resellerAgreements) {
                        if (!accountToSubsidiaries.containsKey(agreement.Account__c)) {
                            accountToSubsidiaries.put(agreement.Account__c, new Set<Id>());
                        }
                        accountToSubsidiaries.get(agreement.Account__c).add(agreement.Subsidiary__c);
                    }
                    for(Opportunity erroredOppy: lstEligiblePartners) {
                        for(OpportunityPartner oppyPartner: erroredOppy.OpportunityPartnersFrom ) {
                            if (!accountToSubsidiaries.containsKey(oppyPartner.AccountToId) ||
                                !accountToSubsidiaries.get(oppyPartner.AccountToId)
                                    .contains(erroredOppy.SBQQ__PrimaryQuote__r.Service_Provider__c)) {
                                mapNewOpportunity.get(erroredOppy.Id).addError(System.Label.FinalQuoteError);
                            }
                        }
                    }
                }
                
            } 

        }
    }

    /**
     * Returns true if the opportunity partners match the quote partners; otherwise, returns false.
     */
    private static List<String> validateOpportunityPartners(Opportunity oppy) {

        // Check if partner/distributor exists on primary quote.
        Boolean partnerExistsOnQuote = oppy.SBQQ__PrimaryQuote__r.SBQQ__Partner__c != null;
        Boolean distributorExistsOnQuote = oppy.SBQQ__PrimaryQuote__r.SBQQ__Distributor__c != null;

        // Check if an associated partners exists on opportunity and, if any, check the role is unique.
        Boolean resellerExistsOnOpportunity = false;
        Integer resellerCount = 0;
        Boolean distributorExistsOnOpportunity = false;
        Integer distributorCount = 0;
        for(OpportunityPartner oppyPartner: oppy.OpportunityPartnersFrom) {
            if (oppyPartner.Role == 'VAR/Reseller') {
                resellerExistsOnOpportunity = resellerExistsOnOpportunity
                    || oppyPartner.AccountToId == oppy.SBQQ__PrimaryQuote__r.SBQQ__Partner__c;
                resellerCount++;
            }
            if (oppyPartner.Role == 'Distributor') {
                distributorExistsOnOpportunity = distributorExistsOnOpportunity
                    || oppyPartner.AccountToId == oppy.SBQQ__PrimaryQuote__r.SBQQ__Distributor__c;
                distributorCount++;
            }
        }

        // Ensure the setup on primary quote and on opportunity is aligned.
        List<String> errors = new List<String>();
        if(partnerExistsOnQuote != resellerExistsOnOpportunity || resellerCount > 1) {
            errors.add(String.format(
                System.Label.FinalQuoteIncorrectOpportunityPartner,
                new String[]{'partner', 'VAR/Reseller'}
            ));
        }
        if(distributorExistsOnQuote != distributorExistsOnOpportunity || distributorCount > 1) {
            errors.add(String.format(
                System.Label.FinalQuoteIncorrectOpportunityPartner,
                new String[]{'distributor', 'Distributor'})
            );
        }        
        return errors;
    }

    private static Boolean isAddressMissingFields(Address addr) {
        if(addr==null) {
            return true;
        }
        if(String.isBlank(addr.getCity()) || String.isBlank(addr.getCountry()) ||String.isBlank(addr.getStreet())) {
            return true;
        }
        return false;
    }
    @testvisible 
    private static String formatMessage(String parameter, String message) {
        List<String> parameters = new List<String>();
        parameters.add(parameter);
        return String.format(message, parameters);
    }

    public static void recallQuoteApprovalProcess(
      List<Opportunity> newRecords,
      Map<Id, Opportunity> oldMap
    ) {
      List<ID> quoteIds =  new List<ID>();
      List<String> stagesBeforeFinalQuote = new List<String>{'Pending', 'Outreach', 'Engaged', 'Proposal'};
      for (Opportunity opp : newRecords) {
          Opportunity oldOpp = oldMap.get(opp.Id);
          if(oldOpp.StageName == 'Final Quote' && stagesBeforeFinalQuote.contains(opp.StageName)) {
              quoteIds.add(opp.SBQQ__PrimaryQuote__c);
          }
      }

      if (quoteIds.size() > 0) {
          Map<Id,SBQQ__Quote__c> quotes = new Map<Id,SBQQ__Quote__c>([SELECT SBQQ__Status__c FROM SBQQ__Quote__c
                                                                      WHERE Id in :quoteIds]);
          List<ProcessInstanceWorkitem> processes = [SELECT Id, ProcessInstanceId, ProcessInstance.TargetObjectId
                                                      FROM ProcessInstanceWorkitem 
                                                      WHERE ProcessInstance.TargetObjectId in :quoteIds];
          for (ProcessInstanceWorkitem process : processes) {
              SBQQ__Quote__c quote = quotes.get(process.ProcessInstance.TargetObjectId);
              if (quote.SBQQ__Status__c == 'In Review') {
                  Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                  req.setAction('Removed');       
                  req.setWorkitemId(process.Id);
                  Approval.process(req,false);
              }
          }
      }
    }
    public static void onOutreachSequenceTrigger(Map<Id,Opportunity> oldMap, Map<Id,Opportunity> newMap) {
        List<Initiate_Renewal_Process__e> events = new List<Initiate_Renewal_Process__e>();
        for(Opportunity opp: (List<Opportunity>) newMap.values()) {
            Opportunity oldOpp = (Opportunity) oldmap.get(opp.Id);
            if((opp.StageName!=oldOpp.StageName || 
                opp.Primary_Contact_Changed__c!=oldOpp.Primary_Contact_Changed__c
               || opp.OwnerId != oldOpp.OwnerId)
               && opp.StageName =='Outreach'
               && opp.Type == 'Renewal'
               && opp.Last_Survey_URL__c==null
               && opp.Active__c == true
              ) {
                  Initiate_Renewal_Process__e irp = new Initiate_Renewal_Process__e ();
					irp.Opportunity_18_Digit_Id__c =opp.Id;
                  	events.add(irp);
              }
        }
        if(events!=null && !events.isEmpty()) {
            EventBus.publish(events);
        }
    }
}