metadata/sf-prod/force-app/main/default/objects/Contract/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <description>Contract Success Level. Gets the value from the related opportunity.</description>
    <formula>TEXT(SBQQ__Opportunity__r.Success_Level__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Success Level</label>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>&apos;Product Family&apos; is required, please refer PB001 for details.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <description>Inferred from the success level of the opportunity line items (each line item linked to a product object that has a Success Level field).</description>
    <inlineHelpText>The success level of the subscription added to the primary quote.</inlineHelpText>
    <label>Success Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Success_Levels</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/recordTypes/CSM.recordType-meta.xml
<RecordType>
    <fullName>CSM</fullName>
    <active>true</active>
    <businessProcess>CSM Journey</businessProcess>
    <label>CSM</label>
</RecordType>

metadata/sf-prod/force-app/main/default/classes/CreateCSMOpportunitiesTest.cls
@isTest
public with sharing class CreateCSMOpportunitiesTest {
    static final String TEST_EMAIL = 'test@trilogy.com';

    @isTest
    static void createCSMOpportunityTest(){
        // Arrange
        Test.startTest();
        TestData.ArrangeReturn data = TestData.createOppAndContract();
        String product = data.opportunity.Product__c;
        Test.stopTest();
        // Act

        // Assert
        List<Opportunity> csmOpps = [SELECT Id, ContractId, AccountId, Product__c, 
                                        CloseDate, Success_Level__c, Owner.Name
                                        FROM Opportunity WHERE Type = 'CSM'];
        System.assertEquals(1, csmOpps.size(), 'Should exist one CSM Opportunity.');
        System.assertEquals(data.contract.Id, csmOpps[0].ContractId, 'ContractId should match Id from Contract.');
        System.assertEquals(data.opportunity.AccountId, csmOpps[0].AccountId, 
            'AccountId should match AccountId from opportunity that originated the contract.');
        System.assertEquals(product, csmOpps[0].Product__c, String.format('Product Family should be {0}', 
            new String[] {product}));
        System.assertEquals(data.contract.EndDate, csmOpps[0].CloseDate, 'CloseDate should match Contract EndDate.');
        //this test case is not valid anymore as the Flow has been updated to work on record type and not on type
        /*System.assertEquals(data.opportunity.Success_Level__c, csmOpps[0].Success_Level__c, 
            'Success level should match success level from opportunity that originated the contract.');*/
        
    }

    
}