metadata/sf-prod/force-app/main/default/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>What product is this lead for?</description>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Lead/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Configuration</label>
    <referenceTo>Product_Configuration__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Lead/fields/Set_Google_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Set_Google_Timezone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Set Google Timezone</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Lead/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <label>Default</label>
</RecordType>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/Product_Configuration__c.object-meta.xml
<CustomObject>
    <label>Product Configuration</label>
    <nameField>
        <label>Product Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>LAMBDA-34344 custom object to replace subsidiary fields on Product configuration with lookups</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/classes/AssignTimezoneBatchTest.cls
@isTest
public with sharing class AssignTimezoneBatchTest {
    class AssignTimezoneBatchWrapper extends AssignTimezoneBatch { // replace the timezone service with a wrapper
        protected override  CachedTimezoneService getTimezoneService(){
            return new CachedTimezoneServiceWrapper(); // Caching timezone service. It will cache HTTP request and count them
        }
    }     

    class CachedTimezoneServiceWrapper extends CachedTimezoneService { // Instead of HTTP requests we will use the mocked timezones
         public override TimezoneService.TimeZone getTimezone(String city, String country, String postalCode){
            TimezoneService.TimeZone tz = new TimezoneService.TimeZone();
            if(country == 'Exception') {
                throw new IllegalArgumentException('Test exception is raised.');
            }
            if(country == 'USA' || country == 'us'){            
                tz.timeZoneId ='America/Chicago';
            } else {
                tz.timeZoneId ='GMT';
            }
            return tz;
        }
    }

    static List<Lead> prepareSingleLeadData(String counrty){ // Insert one lead with the country given
        //Product Configuration
        Subsidiary__c subsidiary = new Subsidiary__c();
        insert subsidiary;
        Product_Configuration__c prodConfig = TestData.createProductConfiguration(subsidiary.Id, null, 'Kayako');
        List<Lead> unassignedLeads = new List<Lead>();
        Lead lead = new Lead(
            Country = counrty,
            PostalCode = null,
            City = null,
            LastName = TestData.LAST_NAME,
            Company = TestData.TEST_COMPANY,
            Set_Google_Timezone__c = false, 
            Product__c = 'Kayako',
            Timezone__c = null
        );
        insert lead;
        unassignedLeads.add(lead);
        return unassignedLeads;
    }

    @isTest
    static void testTimezoneAssignTest(){
        // Arrange
        AssignTimezoneBatch batch = new AssignTimezoneBatchWrapper();
        List<Lead> unassignedLeads = prepareSingleLeadData('USA');

        // Act
        batch.execute((Database.BatchableContext)null, unassignedLeads);

        // Assert
        Lead leadFromDb = [SELECT Id, Timezone__c, Set_Google_Timezone__c FROM Lead];
        System.assertEquals('America/Chicago', leadFromDb.Timezone__c, 'Incorrect timezone.');
        System.assertEquals(true, leadFromDb.Set_Google_Timezone__c, 'The Set_Google_Timezone__c should be true after timezone assigning.');
    }

    @isTest
    static void emptyCountryAssignTest(){ // Test that if the country = null the process executes assigning USA by default
        // Arrange
        AssignTimezoneBatch batch = new AssignTimezoneBatchWrapper();
        List<Lead> unassignedLeads = prepareSingleLeadData(null);

        // Act
        batch.execute((Database.BatchableContext)null, unassignedLeads);

        // Assert
        Lead leadFromDb = [SELECT Id, Timezone__c, Set_Google_Timezone__c FROM Lead];
        System.assertEquals('America/Chicago', leadFromDb.Timezone__c, 'Incorrect timezone.');
        System.assertEquals(true, leadFromDb.Set_Google_Timezone__c, 'The Set_Google_Timezone__c should be true after timezone assigning.');
    }

    @isTest
    static void exceptionHandlingTest(){ // Test that exception processing is correct
        // Arrange
        AssignTimezoneBatch batch = new AssignTimezoneBatchWrapper();
        List<Lead> unassignedLeads = prepareSingleLeadData('Exception');

        // Act
        batch.execute((Database.BatchableContext)null, unassignedLeads);

        // Assert
        Lead leadFromDb = [SELECT Id, Timezone__c, Set_Google_Timezone__c FROM Lead];
        System.assertEquals(null, leadFromDb.Timezone__c, 'When exception occurs the timezone should not be set.');
        System.assertEquals(true, leadFromDb.Set_Google_Timezone__c, 'The Set_Google_Timezone__c should be true after timezone assigning.');
    }
}