metadata/sf-prod/force-app/main/default/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>What product is this lead for?</description>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Lead/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Configuration</label>
    <referenceTo>Product_Configuration__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Lead/fields/Product_Edition__c.field-meta.xml
<CustomField>
    <fullName>Product_Edition__c</fullName>
    <description>If the lead is for a specific product edition from the product family</description>
    <inlineHelpText>If the lead is for a specific product edition from the product family</inlineHelpText>
    <label>Product Edition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Lead/fields/Set_Google_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Set_Google_Timezone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Set Google Timezone</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Created_From_Lead__c.field-meta.xml
<CustomField>
    <fullName>Created_From_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created From Lead</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>&apos;Product Family&apos; is required, please refer PB001 for details.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Configuration</label>
    <referenceTo>Product_Configuration__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <description>Inferred from the success level of the opportunity line items (each line item linked to a product object that has a Success Level field).</description>
    <inlineHelpText>The success level of the subscription added to the primary quote.</inlineHelpText>
    <label>Success Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Success_Levels</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales process</businessProcess>
    <label>Sales</label>
</RecordType>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Max_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Max_Quantity__c</fullName>
    <label>Max Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Min_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Min_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Min Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Product_Edition__c.field-meta.xml
<CustomField>
    <fullName>Product_Edition__c</fullName>
    <label>Product Edition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Editions</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Product_Edition_Label__c.field-meta.xml
<CustomField>
    <fullName>Product_Edition_Label__c</fullName>
    <label>Product Edition Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Subscription_Terms__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Terms__c</fullName>
    <label>Subscription Terms</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Terms</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <label>Success Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Success_Levels</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/Product_Configuration__c.object-meta.xml
<CustomObject>
    <label>Product Configuration</label>
    <nameField>
        <label>Product Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>LAMBDA-34344 custom object to replace subsidiary fields on Product configuration with lookups</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/classes/AutoConvertLeadsCPQTest.cls
@IsTest
private class AutoConvertLeadsCPQTest{
    static List<Id> LeadIds;
    static final String PRODUCT_NAME = 'Kayako';
    static final String USER_PROFILE = 'System Administrator';
    static final String USER_ROLE = 'ISR';
    static final String MANAGER_PROFILE = 'Team Manager';
    static final String MANAGER_ROLE = 'Manager New Sales';

    @isTest
    static void leadAssign_ShouldSilentlyIgnoresInvalidLeadIds(){
        // Given there is a list containing non existing lead ids
        LeadIds = new List<Id>{'001xa000003DIloAAG'};

        // When we convert the lead
        Test.startTest();
        Exception actualException = null;
        try{
            AutoConvertLeadsCPQ.leadAssign(leadIds);
        } catch (Exception dmx){
            actualException = dmx;
        }
        Test.stopTest();

        // Then the exception shouldn't be thrown
        System.assertEquals(null, actualException);
    }

    @isTest
    static void leadAssign_ShouldConvertTheLead(){
        User userManager = TestData.getUser(MANAGER_PROFILE);
        TestData.updateUserRole(userManager, MANAGER_ROLE);
        User user = TestData.createTestUser(USER_PROFILE, USER_ROLE, PRODUCT_NAME, userManager);
        arrange(true);

        Test.startTest();
        Exception actualException = null;
        try{
            SBQQ.TriggerControl.disable();
            try{
                // Given there is a lead
                Lead lead = new Lead(OwnerId = user.Id, Product__c = TestData.PRODUCT_FAMILY, Country = null,
                    PostalCode = null, LastName = TestData.LAST_NAME, Company = TestData.TEST_COMPANY, City = null,
                    Set_Google_Timezone__c = true, Status = 'MQL', IsConverted = false);
                insert lead;
                lead.Status = 'Engaged';
                update lead;
                //When creating Lead this method will be call in OnLeanUpdate Flow
                //AutoConvertLeadsCPQ.leadAssign(new List<Id>{lead.Id});
            } finally{
                SBQQ.TriggerControl.enable();
            }
        } catch (Exception dmx){
            actualException = dmx;
        }
        Test.stopTest();

        // Then the exception shouldn't be thrown
        System.assertEquals(null, actualException);

        // Then must have one opportunity created with Created from lead set
        List<Opportunity> opp = [SELECT Created_From_Lead__c FROM Opportunity];
        System.assertEquals(1,opp.size());
        System.assertEquals(true,opp[0].Created_From_Lead__c);
    }

    @isTest
    static void leadAssign_ShouldConvertLeadWithoutActiveProduct(){
        User userManager = TestData.getUser(MANAGER_PROFILE);
        TestData.updateUserRole(userManager, MANAGER_ROLE);
        User user = TestData.createTestUser(USER_PROFILE, USER_ROLE, PRODUCT_NAME, userManager);
        arrange(false);

        Test.startTest();
        Exception actualException = null;
        try{
            SBQQ.TriggerControl.disable();
            try{
                // Given there is a lead
                Lead lead = new Lead(OwnerId = user.Id, Product__c = TestData.PRODUCT_FAMILY, Country = null,
                    PostalCode = null, LastName = TestData.LAST_NAME, Company = TestData.TEST_COMPANY, City = null,
                    Set_Google_Timezone__c = true, Status = 'MQL', IsConverted = false,
                    Product_Edition__c = TestData.PRODUCT_EDITION_LABEL);
                insert lead;
                lead.Status = 'Engaged';
                update lead;
                //When creating Lead this method will be call in OnLeanUpdate Flow
                //AutoConvertLeadsCPQ.leadAssign(new List<Id>{lead.Id});
            } finally{
                SBQQ.TriggerControl.enable();
            }
        } catch (Exception dmx){
            actualException = dmx;
        }
        Test.stopTest();

        // Then the exception shouldn't be thrown
        System.assertEquals(null, actualException);

        // Then must have one opportunity created with Created from lead set
        List<Opportunity> opp = [SELECT Created_From_Lead__c FROM Opportunity];
        System.assertEquals(1,opp.size());
        System.assertEquals(true,opp[0].Created_From_Lead__c);
    }

    private static void arrange(Boolean productIsActive){
        Product2 product = new Product2(Name = String.format('{0}:Standard:Standard:0:49:Yearly',
            new String[]{AutoConvertLeadsCPQTest.PRODUCT_NAME}), CanUseRevenueSchedule = false,
            IsActive = productIsActive, Product__c = AutoConvertLeadsCPQTest.PRODUCT_NAME,
            ProductCode = TestData.PRODUCT_CODE, Family = TestData.PRODUCT_FAMILY,
            Success_Level__c = TestData.PRODUCT_SUCCESS_LEVEL, Product_Edition__c = TestData.PRODUCT_EDITION,
            Product_Edition_Label__c = TestData.PRODUCT_EDITION_LABEL, Min_Quantity__c = 1, Max_Quantity__c = 999,
            Subscription_Terms__c = '12;24');
        insert product;
        
        Subsidiary__c subsidiary = new Subsidiary__c();
        insert subsidiary;
        Product_Configuration__c productConfig = TestData.createProductConfiguration(subsidiary.Id, null, TestData.PRODUCT_FAMILY);

        id standardPBID = Test.getStandardPricebookId();
        PricebookEntry stdPBE = new PriceBookEntry(Product2Id = product.Id, Pricebook2Id = standardPBID,
            UnitPrice = 3000000.00, UseStandardPrice = false, IsActive = true);
        insert stdPBE;

        PriceBook2 customPriceBook = new PriceBook2();
        customPriceBook.Name = 'Custom Pricebook';
        customPriceBook.IsActive = true;
        insert customPriceBook;

        PricebookEntry cusPBE = new PriceBookEntry(Product2Id = product.Id, Pricebook2Id = customPriceBook.Id,
            UnitPrice = 5000000.00, UseStandardPrice = false, IsActive = true);
        insert cusPBE;
    }
}