metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Out for Signature</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/QuoteTriggerHandler.cls
public with sharing class QuoteTriggerHandler {
    public static void generateFinalQuote(Map<Id, SBQQ__Quote__c> oldMap, List<SBQQ__Quote__c> newRecords) {
      List<SBQQ__Quote__c> toGenerate = new List<SBQQ__Quote__c>();
      
      for (SBQQ__Quote__c q : newRecords) {
          if (q.SBQQ__Primary__c && 
              q.SBQQ__Status__c == 'Accepted' &&
              oldMap.get(q.Id).SBQQ__Status__c != 'Accepted'
          ) {
            toGenerate.add(q);
          }
      }
      
      CPQGenerateQuotePDF generateQuotePDF = new CPQGenerateQuotePDF();
      generateQuotePDF.GeneratePDFs(toGenerate);
    }
}