metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/Product_Configuration__c.object-meta.xml
<CustomObject>
    <label>Product Configuration</label>
    <nameField>
        <label>Product Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Additional_Notification_Party__c.field-meta.xml
<CustomField>
    <fullName>Additional_Notification_Party__c</fullName>
    <label>Additional Notification Party</label>
    <type>Email</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Fulfillment_Email__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Email__c</fullName>
    <label>Fulfillment Email</label>
    <type>Email</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/InvalidEmailHandler.cls
global class InvalidEmailHandler implements SandboxPostCopy {
    global void runApexClass(SandboxContext context) {
        addInvalidToAll();
    }

    public static void addInvalidToAll() {
        List<Product_Configuration__c> productConfigs = [SELECT Additional_Notification_Party__c, Fulfillment_Email__c 
                                                            FROM Product_Configuration__c];
        for (Product_Configuration__c config : productConfigs) {
            config.Additional_Notification_Party__c = addInvalid(config.Additional_Notification_Party__c);
            config.Fulfillment_Email__c = addInvalid(config.Fulfillment_Email__c);
        }
        update productConfigs;
        InvalidEmailContactBatch contactBatch = new InvalidEmailContactBatch();
        Database.executeBatch(contactBatch,2000);
    }

    public static String addInvalid(String email) {
        if (String.isBlank(email)) {
            return null;
        }
        return email + '.invalid';
    }
}