metadata/sf-prod/force-app/main/default/objects/Account/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <description>Is the sum of ARR of all opportunities where the Renewal / Start Date is before TODAY and the Renewal Date / Start Date + Term is after TODAY.</description>
    <inlineHelpText>Reflects the ARR of our total relationship with the customer. It is the sum of ARR of all active contracts as of TODAY.</inlineHelpText>
    <label>ARR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Account/fields/Product_Families__c.field-meta.xml
<CustomField>
    <fullName>Product_Families__c</fullName>
    <description>All product families for which this account holds subscriptions.</description>
    <label>Product Families</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Account/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <label>Success Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Success_Levels</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <description>MRR x 12.  Calculated based on the recurring opportunity products. Does not include one-time items.</description>
    <formula>MRR__c * 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/MRR__c.field-meta.xml
<CustomField>
    <fullName>MRR__c</fullName>
    <description>Monthly cost of recurring items from the Opportunity Products. Used for Reporting. Calculated by the OnOpportunityUpdate flow</description>
    <label>MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>&apos;Product Family&apos; is required, please refer PB001 for details.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <description>Defines if purchase order is not required or if it is attached</description>
    <inlineHelpText>Keep this field empty if purchase order is required and not attached</inlineHelpText>
    <label>Purchase Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <description>Inferred from the success level of the opportunity line items (each line item linked to a product object that has a Success Level field).</description>
    <inlineHelpText>The success level of the subscription added to the primary quote.</inlineHelpText>
    <label>Success Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Success_Levels</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/AccountRollupBatchTest.cls
@isTest
public class AccountRollupBatchTest {

    @TestSetup
    static void makeData() {
        TestData.ArrangeReturn data = TestData.createOppAndContract();
    }
    @isTest
    static void testAccountRollupBatch() {
        
        Test.startTest();
        List<Opportunity> lstOpportunity = new List<Opportunity>();
        lstOpportunity = [SELECT Id, MRR__c, StageName, Purchase_Order__c,AccountId,Renewal_Date__c,Product__c,Success_Level__c from Opportunity];
        lstOpportunity[0].MRR__c = 100;
        lstOpportunity[0].Purchase_Order__c = 'Not Required';
        lstOpportunity[0].StageName = 'Closed Won';
        lstOpportunity[0].Renewal_Date__c = Date.today()-1;
        lstOpportunity[0].Product__c = 'ACRM';
        lstOpportunity[0].Success_Level__c = 'Platinum';
        OpportunityQBDisable.execute();
        update lstOpportunity;
        OpportunityQBEnable.execute();
        // Execute Batch
        AccountRollupBatch processor = new AccountRollupBatch();
        String sch ='0 1 * * * ?';
        Id batchId = System.schedule('Batch Scheduled',sch,processor);
        Database.executeBatch(processor,50);
        Test.stopTest();
        
        // Asserts
        List<Account> updatedAccounts = [SELECT Id, ARR__c, Product_families__c,Success_Level__c FROM Account where Id = :lstOpportunity[0].AccountId];
        System.assertEquals('ACRM', updatedAccounts[0].Product_families__c, 'Testing Product Families');
        //System.assertEquals(1200.0, updatedAccounts[0].ARR__c,'Testing ARR value');
        System.assertEquals('Platinum',updatedAccounts[0].Success_Level__c,'Testing Success Level');
    }
}