metadata/sf-prod/force-app/main/default/objects/Account/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <description>Is the sum of ARR of all opportunities where the Renewal / Start Date is before TODAY and the Renewal Date / Start Date + Term is after TODAY.</description>
    <inlineHelpText>Reflects the ARR of our total relationship with the customer. It is the sum of ARR of all active contracts as of TODAY.</inlineHelpText>
    <label>ARR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Account/fields/Product_Families__c.field-meta.xml
<CustomField>
    <fullName>Product_Families__c</fullName>
    <description>All product families for which this account holds subscriptions.</description>
    <label>Product Families</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Account/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <label>Success Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Success_Levels</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Contract/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <description>Sum of subscriptions ARR</description>
    <inlineHelpText>Sum of subscriptions ARR</inlineHelpText>
    <label>ARR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Contract/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <description>Contract Success Level. Gets the value from the related opportunity.</description>
    <formula>TEXT(SBQQ__Opportunity__r.Success_Level__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Success Level</label>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <description>MRR x 12.  Calculated based on the recurring opportunity products. Does not include one-time items.</description>
    <formula>MRR__c * 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>&apos;Product Family&apos; is required, please refer PB001 for details.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <description>Inferred from the success level of the opportunity line items (each line item linked to a product object that has a Success Level field).</description>
    <inlineHelpText>The success level of the subscription added to the primary quote.</inlineHelpText>
    <label>Success Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Success_Levels</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Term_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_End_Date__c</fullName>
    <description>LAMBDA-60439 field to calculate end of the renewal term based on the close date</description>
    <formula>IF(
       (ISPICKVAL(Type,&apos;Upsell&apos;)|| RecordTypeId=&apos;0122x000000V65fAAC&apos;) 
			&amp;&amp;  NOT(ISBLANK(ContractId)) , AddMonths(Contract.StartDate,Opportunity_Term__c),
	    	AddMonths(Renewal_Date__c-1,Opportunity_Term__c)
)</formula>
    <inlineHelpText>Term calculated to be used in templates</inlineHelpText>
    <label>Term End Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/recordTypes/New_Business.recordType-meta.xml
<RecordType>
    <fullName>New_Business</fullName>
    <active>true</active>
    <businessProcess>New Business Process</businessProcess>
    <description>Record Type for New Business</description>
    <label>New Business</label>
</RecordType>

metadata/sf-prod/force-app/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales process</businessProcess>
    <label>Sales</label>
</RecordType>

metadata/sf-prod/force-app/main/default/classes/AccountRollupBatch.cls
/**
 * @description: LAMBDA-63234 Batch to rollup ARR from Contract
 */
public class AccountRollupBatch implements Database.Batchable<sObject>,Schedulable {
    public String query ; 
    public Database.QueryLocator start(Database.BatchableContext bc) {
        if(query==null || query=='') {
            query = 'SELECT Id FROM Account Where Id IN' +
                    ' (SELECT AccountId FROM Opportunity WHERE ' +
                    ' Renewal_Date__c <= Today' + 
                    ' and isWon = true and Type!=\'Prime\' and RecordType.DeveloperName In (\'Sales\',\'New_Business\')) ' ;
        }
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Account> scope) {
        Map<Id, Decimal> accountToARRMap = new Map<Id, Decimal>();
        Map<Id, Set<String>> accountToProductFamiliesMap = new Map<Id, Set<String>>();
        Map<Id,Account> mapAccountIds = new Map<Id, Account> (scope);
        Set<String> productFamilyActiveValues = new Set<String>();
        Map<Id, String> accountIdToHighestSuccessLevel = new Map<Id, String>();
        productFamilyActiveValues.addAll(getValidProductFamilies());
        for (Opportunity opp : [SELECT Id, AccountId, Product__c, Renewal_Date__c, Term_End_Date__c,
                                Arr__c,Success_Level__c
                               FROM Opportunity 
                               WHERE AccountId IN :mapAccountIds.keyset() AND 
                               Renewal_Date__c < Today   AND 
                               isWon=true ]) {
            Id accountId = opp.AccountId;
            Decimal opportunityARR = opp.Term_End_Date__c < Date.today()?0.0:opp.Arr__c;
            String productFamily = opp.Product__c;
            
            if (!accountToARRMap.containsKey(accountId)) {
                accountToARRMap.put(accountId, opportunityARR);
            } else {
                accountToARRMap.put(accountId, accountToARRMap.get(accountId) + opportunityARR);
            }
            
            if (productFamily != null) {
                if(!productFamilyActiveValues.contains(productFamily)) {
                    continue;
                }
                if (!accountToProductFamiliesMap.containsKey(accountId)) {
                    accountToProductFamiliesMap.put(accountId, new Set<String>{productFamily});
                } else {
                    accountToProductFamiliesMap.get(accountId).add(productFamily);
                }
            }
            Integer oppySLRank = getSuccessLevelRank(opp.Success_Level__c);                     
            if(!accountIdToHighestSuccessLevel.containsKey(opp.AccountId) || 
                oppySLRank > getSuccessLevelRank(accountIdToHighestSuccessLevel.get(opp.AccountId))) {
                String successLevel = opp.Term_End_Date__c < Date.today()?'':opp.Success_level__c;
                accountIdToHighestSuccessLevel.put(opp.AccountId, successLevel);
             }
        }
        
        List<Account> accountsToUpdate = new List<Account>();
        for (Account acc : scope) {
            acc.ARR__c = accountToARRMap.get(acc.Id);
            if (accountToProductFamiliesMap.containsKey(acc.Id)) {
                acc.Product_families__c = String.join(new List<String>(accountToProductFamiliesMap.get(acc.Id)), ';');
            } else {
                acc.Product_families__c = null; // Reset to null if no products found
            }
            if(accountIdToHighestSuccessLevel.containsKey(acc.Id)) {
                acc.Success_Level__c = accountIdToHighestSuccessLevel.get(acc.Id);
            } else {
                acc.Success_Level__c = '';//Reset to null if no success level found
            }
            accountsToUpdate.add(acc);
        }
        
        update accountsToUpdate;
    }

    public void finish(Database.BatchableContext bc){
    }
    private Set<String> getValidProductFamilies() {
        Set<String> pickListValuesList= new Set<String>();
        Schema.DescribeFieldResult fieldResult = Account.Product_families__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple) {
            pickListValuesList.add(pickListVal.getLabel());
        }     
        return pickListValuesList;
    }
    public void execute(SchedulableContext ctx) {
        AccountRollupBatch processor = new AccountRollupBatch();
        Database.executeBatch(processor, 50);
    }
    private static Integer getSuccessLevelRank(String successLevel) {
    Map<String, Integer> successLevelRankings = new Map<String, Integer>{
        'Legacy' => 1,
        'Standard' => 2,
        'Gold' => 3,
        'Platinum' => 4
    };
    
    return successLevelRankings.containsKey(successLevel) ? successLevelRankings.get(successLevel) : 0;
}

}