metadata/sf-prod/force-app/main/default/objects/Account/fields/Home_Product_Renewal_Contact__c.field-meta.xml
<CustomField>
    <fullName>Home_Product_Renewal_Contact__c</fullName>
    <description>LAMBDA-63247 : This will store the primary contact from the recent renewal opportunity</description>
    <label>Home Product Renewal Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Contact/fields/Current_Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Current_Opportunity_Stage__c</fullName>
    <description>Used to update the stage of the latest Opportunity associated with this Contact from Outreach.</description>
    <label>Current Opportunity Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Stages</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Contact/fields/Current_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Current_Product_Family__c</fullName>
    <description>Last active Product Family being sold</description>
    <label>Current Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Contact/fields/Current_Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Current_Renewal_Date__c</fullName>
    <label>Current Renewal Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Contact/fields/Term_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_End_Date__c</fullName>
    <description>LAMBDA-65776 term end date derived from related open renewal</description>
    <inlineHelpText>End date of the latest open renewal opportunity related to this contact</inlineHelpText>
    <label>Term End Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Primary_Contact_Changed__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Changed__c</fullName>
    <description>Date when the Primary contact was changed or set</description>
    <label>Primary Contact Changed</label>
    <type>DateTime</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>&apos;Product Family&apos; is required, please refer PB001 for details.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Term_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_End_Date__c</fullName>
    <description>LAMBDA-60439 field to calculate end of the renewal term based on the close date</description>
    <formula>IF(
       (ISPICKVAL(Type,&apos;Upsell&apos;)|| RecordTypeId=&apos;0122x000000V65fAAC&apos;) 
			&amp;&amp;  NOT(ISBLANK(ContractId)) , AddMonths(Contract.StartDate,Opportunity_Term__c),
	    	AddMonths(Renewal_Date__c-1,Opportunity_Term__c)
)</formula>
    <inlineHelpText>Term calculated to be used in templates</inlineHelpText>
    <label>Term End Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/OpportunityContactRoleTriggerHandler.cls
public with sharing class OpportunityContactRoleTriggerHandler {
  public static void UpdatePrimaryContact(
    List<OpportunityContactRole> newRecords,
    Map<Id, OpportunityContactRole> newMap,  
    List<OpportunityContactRole> oldRecords,
    Map<Id, OpportunityContactRole> oldMap
  ) {
      List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();
      List<Contact> contacts = new List<Contact>();
      Set<Id> contactIds = new Set<Id>(); // A set to filter out contact duplicates
      Set<Id> oppIds = new  Set<Id>();

      for (OpportunityContactRole r : newRecords) { // Get all the corresponding opportunities
        oppIds.add(r.OpportunityId);
      }

      Map<Id, Opportunity> mapOpps = new Map<Id, Opportunity>(
      [SELECT Id, Renewal_Date__c, Primary_Contact_Changed__c, Product__c, StageName 
        FROM Opportunity 
        WHERE Id IN :oppIds]
      );

      for (OpportunityContactRole r : newRecords) {
        if (r.IsPrimary) {
            Opportunity opp = mapOpps.get(r.OpportunityId);
            if(!contactIds.contains(r.ContactId)) { // Prevent duplication error                                
                Contact contact = new Contact(
                  Id = r.ContactId, 
                  Current_Renewal_Date__c = opp.Renewal_Date__c, 
                  Current_Product_Family__c = opp.Product__c, 
                  Current_Opportunity_Stage__c = opp.StageName);
                
                contacts.add(contact);
                contactIds.add(contact.Id);
            }
            if(oldMap != null){
                OpportunityContactRole oldRole = oldMap.get(r.Id);
                if(!oldRole.IsPrimary){
                    // The primary contact changed
                    opp.Primary_Contact_Changed__c = System.now();
                    opportunitiesToUpdate.add(opp);
                }
            }else{
                opp.Primary_Contact_Changed__c = System.now();
                opportunitiesToUpdate.add(opp);
            }
          }
      }
      update opportunitiesToUpdate;
      update contacts;

    // Update the Home_Product_Renewal_Contact__c field on the Account
    Map<Id, String> primaryContactNamesMap = new Map<Id, String>();
    Map<Id, Account> accountsToUpdateMap = new Map<Id, Account>();
    Set<Id> updatedOppIds = new Set<Id>();
    
    for (OpportunityContactRole role : newRecords) {
        if (role.IsPrimary) {
            updatedOppIds.add(role.OpportunityId);
        }
    }
        
    if (!updatedOppIds.isEmpty()) {
        for (OpportunityContactRole role : [SELECT Opportunity.AccountId,Opportunity.Term_End_Date__c,Contact.Name
                                            FROM OpportunityContactRole
                                            WHERE IsPrimary = true AND OpportunityId IN :updatedOppIds]) {
                                                primaryContactNamesMap.put(role.Opportunity.AccountId, role.Contact.Name);
                                            }
        
        for (Opportunity opp : [SELECT Id, AccountId,Term_End_Date__c FROM Opportunity WHERE Term_End_Date__c > TODAY AND Id IN :updatedOppIds]) {
            if (opp.AccountId != null && primaryContactNamesMap.containsKey(opp.AccountId)) {
                String primaryContactName = primaryContactNamesMap.get(opp.AccountId);
                Id accountId = opp.AccountId;
                // Check if the Account is already in the map
                if (accountsToUpdateMap.containsKey(accountId)) {
                    // If the Account is already in the map, update the Home_Product_Renewal_Contact__c field
                    Account acc = accountsToUpdateMap.get(accountId);
                    acc.Home_Product_Renewal_Contact__c = primaryContactName;
                } else {
                     // If the Account is not in the map, create a new Account with the updated Home_Product_Renewal_Contact__c field
                    Account acc = new Account(Id = accountId, Home_Product_Renewal_Contact__c = primaryContactName);
                    accountsToUpdateMap.put(accountId, acc);
                }       
            }
        }
        
        // Perform the update on the Account records
        if (!accountsToUpdateMap.isEmpty()) {
            update accountsToUpdateMap.values();
        }
    }
  }
}