metadata/sf-prod/force-app/main/default/objects/Account/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <description>ID which is taken from the URL of the customer profile page in the NetSuite</description>
    <externalId>true</externalId>
    <inlineHelpText>Customer profile page is available at https://4914352.app.netsuite.com/app/common/entity/custjob.nl?id=&lt;ID&gt; (replace &lt;ID&gt; with this field value)</inlineHelpText>
    <label>NetSuite ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Account/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <label>Success Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Success_Levels</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Contact/fields/Current_ARR__c.field-meta.xml
<CustomField>
    <fullName>Current_ARR__c</fullName>
    <description>LAMBDA-65776 Field to capture the ARR amount from related active renewal</description>
    <inlineHelpText>This field is synced from latest ongoing renewal opportunity and brings ARR value</inlineHelpText>
    <label>Current ARR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Contact/fields/Current_Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Current_Success_Level__c</fullName>
    <description>LAMBDA-65776 success level of the current active renewal for which this contact is primary contact</description>
    <inlineHelpText>Derived from Current active renewal related to this contact as Primary.</inlineHelpText>
    <label>Current Success Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Contact/fields/Current_Term__c.field-meta.xml
<CustomField>
    <fullName>Current_Term__c</fullName>
    <description>LAMBDA-65776 field to capture Term from Opportunity</description>
    <inlineHelpText>The field shows the term synced from latest active renewal related to this opportunity</inlineHelpText>
    <label>Current Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Contact/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <externalId>true</externalId>
    <label>NetSuite ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Addons__c.field-meta.xml
<CustomField>
    <fullName>Current_Addons__c</fullName>
    <label>Current Addons</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Addons_ARR__c.field-meta.xml
<CustomField>
    <fullName>Current_Addons_ARR__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Current Addons ARR = Current ARR - current master products ARR</description>
    <inlineHelpText>Current annual recurring revenue (ARR) of add-on products only (i.e. non-master products which cannot be sold separately)</inlineHelpText>
    <label>Current Addons ARR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_ARR__c.field-meta.xml
<CustomField>
    <fullName>Current_ARR__c</fullName>
    <description>Current ARR = master products ARR + addons ARR of the parent subscription.</description>
    <inlineHelpText>Total annual recurring revenue (ARR) of the current (parent) subscription (include both addons ARR and master products ARR)</inlineHelpText>
    <label>Current ARR</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Billing_Term__c.field-meta.xml
<CustomField>
    <fullName>Current_Billing_Term__c</fullName>
    <label>Current Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Billing_Frequency</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Primary_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Current_Primary_Contact_Email__c</fullName>
    <label>Current Primary Contact Email</label>
    <type>Email</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Product__c.field-meta.xml
<CustomField>
    <fullName>Current_Product__c</fullName>
    <label>Current Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Product_Edition__c.field-meta.xml
<CustomField>
    <fullName>Current_Product_Edition__c</fullName>
    <label>Current Product Edition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Product_Edition_Label__c.field-meta.xml
<CustomField>
    <fullName>Current_Product_Edition_Label__c</fullName>
    <label>Current Product Edition Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Seats__c.field-meta.xml
<CustomField>
    <fullName>Current_Seats__c</fullName>
    <label>Current Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Current_Success_Level__c</fullName>
    <label>Current Success Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Success_Levels</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Term__c.field-meta.xml
<CustomField>
    <fullName>Current_Term__c</fullName>
    <inlineHelpText>Term of the current contract (the one being renewed) in months. 0 (zero) is for EVERGREEN subscriptions.</inlineHelpText>
    <label>Current Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>ID of the NetSuite renewal subscription associated with this opportunity. If matches &quot;O-&lt;ID&gt;&quot; then the ID points to NetSuite Opportunity record instead.</inlineHelpText>
    <label>NetSuite ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Parent_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Parent_Subscription_ID__c</fullName>
    <description>A valid NetSuite or Zuora (for Kayako) subscription number of the parent/renewed subscription.</description>
    <inlineHelpText>A valid NetSuite or Zuora (for Kayako) subscription number of the parent/renewed subscription.</inlineHelpText>
    <label>Parent Subscription ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>&apos;Product Family&apos; is required, please refer PB001 for details.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Configuration</label>
    <referenceTo>Product_Configuration__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <description>Inferred from the success level of the opportunity line items (each line item linked to a product object that has a Success Level field).</description>
    <inlineHelpText>The success level of the subscription added to the primary quote.</inlineHelpText>
    <label>Success Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Success_Levels</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/OpportunityLineItem/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <description>LAMBDA-69849 field to derive success level from related Product</description>
    <formula>TEXT(PricebookEntry.Product2.Success_Level__c)</formula>
    <inlineHelpText>Success level of the related product fetched from the Product record</inlineHelpText>
    <label>Success Level</label>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Max_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Max_Quantity__c</fullName>
    <label>Max Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Min_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Min_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Min Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <description>The ID of the corresponding subscription plan in Netsuite.</description>
    <externalId>true</externalId>
    <inlineHelpText>The ID of the corresponding subscription plan in Netsuite.</inlineHelpText>
    <label>NetSuite ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Product_Edition__c.field-meta.xml
<CustomField>
    <fullName>Product_Edition__c</fullName>
    <label>Product Edition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Editions</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Product_Edition_Label__c.field-meta.xml
<CustomField>
    <fullName>Product_Edition_Label__c</fullName>
    <label>Product Edition Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Subscription_Terms__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Terms__c</fullName>
    <label>Subscription Terms</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Terms</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <label>Success Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Success_Levels</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/Product_Configuration__c.object-meta.xml
<CustomObject>
    <label>Product Configuration</label>
    <nameField>
        <label>Product Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <externalId>true</externalId>
    <label>NetSuite ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <description>NetSuite ID obtained from the Product</description>
    <formula>SBQQ__Product__r.NetSuite_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NetSuite ID</label>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>LAMBDA-34344 custom object to replace subsidiary fields on Product configuration with lookups</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Subsidiary__c/fields/Netsuite_Id__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_Id__c</fullName>
    <externalId>true</externalId>
    <label>Netsuite Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/SetupRenewalOpportunityTest.cls
@isTest
public class SetupRenewalOpportunityTest {
    public class ArrangeParams{
        String productName = 'Kayako';
        String productEdition;
        String productEditionLabel = 'Growth';
        String productSuccessLevel = 'Standard';
        String email = 'test@test.com';
        Integer minQuantity = 1;
        Integer maxQuantity = 49;
        String billingTerm = 'Annual';
        Decimal unitPrice = 15.00;
        Integer quantity = 20;
        String term = '1';
        Decimal currentARR;
        String currentProduct;
        String currentProductEdition;
        String currentProductEditionLabel;
        String currentSuccessLevel;
        Decimal currentAddonsARR;
        Integer currentTerm;
        public ArrangeParams(String productEdition, Decimal currentARR, 
                             String currentProduct, String currentProductEdition,
                             String currentProductEditionLabel, String currentSuccessLevel, 
                             Decimal currentAddonsARR){
            this(productEdition, currentArr, currentProduct, currentProductEdition, currentProductEditionLabel,
                currentSuccessLevel, currentAddonsARR, 1);
        }
        public ArrangeParams(String productEdition, Decimal currentARR, 
                             String currentProduct, String currentProductEdition,
                             String currentProductEditionLabel, String currentSuccessLevel, 
                             Decimal currentAddonsARR, Integer currentTerm){
            this.productEdition = productEdition;
            this.currentARR = currentARR;
            this.currentProduct = currentProduct;
            this.currentProductEdition = currentProductEdition;
            this.currentProductEditionLabel = currentProductEditionLabel;
            this.currentSuccessLevel = currentSuccessLevel;
            this.currentAddonsARR = currentAddonsARR;
            this.currentTerm = currentTerm;
        }
    }

    public class TestResults{
        List<OpportunityLineItem> lineItems;
        SBQQ__Quote__c quote;
        List<SBQQ__QuoteLine__c> quoteLines;
        TestResults(List<OpportunityLineItem> lineItems, SBQQ__Quote__c quote, List<SBQQ__QuoteLine__c> quoteLines){
            this.lineItems = lineItems;
            this.quote = quote;
            this.quoteLines = quoteLines;
        }
    }
    
    @isTest 
    static void verifyNoQuoteCreationForEvergreen() {
        Test.startTest();
        //EVERGREEN have currentTerm = 0
        ArrangeParams params = new ArrangeParams('Standard', 300.00, 'OnDemand', 'Standard', 'Growth', 'Standard', 
            0.00, 0);
        arrange(params);
        Test.stopTest();

        // Assert
        List<Opportunity> oppList = [SELECT Id, Type, Current_Success_Level__c
                                     FROM Opportunity];
        System.assertEquals(1, oppList.size(), 'Expects 1 opportunity to be returned');
        List<AggregateResult> countQuotes = [SELECT Count(Id) cnt
                                             FROM SBQQ__Quote__c
                                             WHERE SBQQ__Opportunity2__c = :oppList[0].Id];
        System.assert((Integer)countQuotes[0].get('cnt') == 0, 'No quote lines should be created.');
    }
    
    @isTest 
    static void verifyCurrentTermMatchesSent() {
        Test.startTest();
        ArrangeParams params = new ArrangeParams('Standard', 300.00, 'OnDemand', 'Standard', 'Growth', 'Standard', 
            0.00, 10);
        arrange(params);
        Test.stopTest();

        // Assert
        List<Opportunity> oppList = [SELECT Id, Type, Current_Term__c
                                     FROM Opportunity];
        System.assertEquals(1, oppList.size(), 'Expects 1 opportunity to be returned');
        System.assertEquals(oppList[0].Current_Term__c, params.currentTerm, 
            'Current Term should be equal current term sent.');
    }

    @isTest 
    static void given_Product_When_DefaultConfiguration_Verify_TypeAndSuccessLevelAndARR() {
        Test.startTest();
        arrange(new ArrangeParams('Standard', 300.00, 'Kayako', 'Standard', 'Growth', 'Standard', 0.00));
        Test.stopTest();

        // Assert
        List<Opportunity> oppList = [SELECT Id, Type, Current_Success_Level__c
                                     FROM Opportunity];
        TestResults results = getTestResults(oppList);
        doDefaultAssertions(oppList, results);
        System.assert(results.quoteLines.size() > 0, 'Quote lines should be created.');
    }

    @isTest 
    static void editionUpgradeTest() {        
        Test.startTest();
        arrange(new ArrangeParams('Enterprise', 300.00, 'Kayako', 'None', 'Growth', 'Standard', 0.00));
        Test.stopTest();

        // Assert
        List<Opportunity> oppList = [SELECT Type, Current_Success_Level__c
                                     FROM Opportunity];
        TestResults results = getTestResults(oppList);
        doDefaultAssertions(oppList, results);
        System.assert(results.quoteLines.size() == 1, 'One quote line should be created.');
    }

    @isTest 
    static void addonsTest() {        
        Test.startTest();
        arrange(new ArrangeParams('Enterprise', 0.00, 'Kayako', 'None', 'Growth', 'Standard', 100.00));
        Test.stopTest();

        // Assert
        List<Opportunity> oppList = [SELECT Type, Current_Success_Level__c
                                     FROM Opportunity];
        TestResults results = getTestResults(oppList);
        doDefaultAssertions(oppList, results);
        System.assert(results.quoteLines.size() == 2, 
                        'Quote lines for the main product and the add-on should be created.');
    }
    
    @isTest 
    static void given_OpportunityWithOptOutEmailContact_When_DefaultConfiguration_Verify_OppDescriptionAndStageNameCorrect() {
        Test.startTest();
        ArrangeParams params = new ArrangeParams('Standard', 300.00, 'Kayako', 'Standard', 'Growth', 'Standard', 0.00);
        Contact contact = new Contact(LastName = 'LastName', Email = params.email, HasOptedOutOfEmail = true);
        insert contact;
        arrange(params);
        Test.stopTest();
        
        // Assert
        List<Opportunity> oppList = [SELECT Type, Current_Success_Level__c, Description, StageName
                                     FROM Opportunity];
        String dateStr = Date.today().format();
        System.assertEquals(dateStr + ': The Primary Contact (' + params.email + ') has Opted Out of email communication. Use alternate means to engage or identify an alternate contact.', oppList[0].Description);
        System.assertEquals('Pending', oppList[0].StageName);
    }

    @isTest
    static void given_Product_And_ProductConfiguration_When_OpportunityWith_Null_CurrentProductData_Verify_Opportunity_Is_NotNull(){
        Test.startTest();
        arrange(new ArrangeParams('Enterprise', 300.00, null, null, null, null, 0.00));
        Test.stopTest();
    
        // Assert
        List<Opportunity> oppList = [SELECT Type, Current_Success_Level__c, Description, StageName
                                     FROM Opportunity];
        System.assert(oppList[0] != null);
        System.assertEquals('Pending', oppList[0].StageName);
        System.assertEquals('Renewal', oppList[0].Type);
    }

    @isTest
    static void given_Product_And_ProductConfiguration_When_OpportunityWith_Null_CurrentProductEdition_Verify_Opportunity_Is_NotNull(){
        Test.startTest();
        arrange(new ArrangeParams('Enterprise', 300.00, 'Kayako', null, 'Growth', 'Standard', 0.00));
        Test.stopTest();

        // Assert
        List<Opportunity> oppList = [SELECT Type, Current_Success_Level__c, Description, StageName
                                     FROM Opportunity];
        System.assert(oppList[0] != null);
        System.assertEquals('Pending', oppList[0].StageName);
        System.assertEquals('Renewal', oppList[0].Type);
    }

    static TestResults getTestResults(List<Opportunity> oppList){
        List<OpportunityLineItem> lineItems = [SELECT Quantity
                                               FROM OpportunityLineItem
                                               WHERE OpportunityId = :oppList[0].Id];
        SBQQ__Quote__c quote = [SELECT Id
                                FROM SBQQ__Quote__c
                                WHERE SBQQ__Opportunity2__c = :oppList[0].Id];
        List<SBQQ__QuoteLine__c> quoteLines = [SELECT Id, SBQQ__Quote__c, SBQQ__Quantity__c
                                               FROM SBQQ__QuoteLine__c];
        return new TestResults(lineItems, quote, quoteLines);
    }

    static void doDefaultAssertions(List<Opportunity> oppList, TestResults results){
        System.assertEquals('Renewal', oppList[0].Type, 'Renewal opportunity type should be set.');
        System.assertEquals('Standard', oppList[0].Current_Success_Level__c,
            'Success Level should be set for the opportunity');
        System.assertEquals(20, results.lineItems[0].Quantity, 'Quantity should be set');
        System.assert(results.quote != null, 'Quote should be created.');
    }

    public static void arrange(ArrangeParams arrangeParams){
        Account acct = new Account(Name='Test Account');
        insert acct;
        List<Contact> cont = [SELECT Id,AccountId from Contact WHERE Email=:arrangeParams.email];
        if(cont!=null && !cont.isEmpty()) {
			cont[0].AccountId = acct.Id;
            update cont;            
        }

        Id idPricebook = Test.getStandardPricebookId();
        // Product2
        Product2 productDb = new Product2(Name = 'Kayako:Standard:Standard:0:49:Yearly', CanUseRevenueSchedule = false,
            IsActive = true, Product__c = arrangeParams.productName, ProductCode = 'starter',
            Family = arrangeParams.productName, Success_Level__c = arrangeParams.productSuccessLevel,
            Product_Edition__c = arrangeParams.productEdition,
            Product_Edition_Label__c = arrangeParams.productEditionLabel, Min_Quantity__c = arrangeParams.minQuantity,
            Max_Quantity__c = arrangeParams.maxQuantity, Subscription_Terms__c = '1;12;24');
        insert productDb;

        // Product2
        Product2 productAddon = new Product2(Name = 'Kayako:Collaborators', CanUseRevenueSchedule = false,
            IsActive = true, Product__c = 'Collaborators', ProductCode = 'starter1',
            Family = arrangeParams.productName, Success_Level__c = arrangeParams.productSuccessLevel,
            Product_Edition__c = arrangeParams.productEdition,
            Product_Edition_Label__c = arrangeParams.productEditionLabel, Min_Quantity__c = arrangeParams.minQuantity,
            Max_Quantity__c = arrangeParams.maxQuantity, Subscription_Terms__c = '1;12;24');
        insert productAddon;

        Id userId = TestData.getUser('System Administrator').Id;
        // Pricebook
        Pricebook2 standardPricebook = new Pricebook2(Id = idPricebook, IsActive = true);
        update standardPricebook;
        // PriceBookEntry
        PriceBookEntry priceBook = new PriceBookEntry(UnitPrice = arrangeParams.unitPrice, Product2Id = productDb.Id, IsActive = true, PriceBook2Id = idPricebook, UseStandardPrice = false);
        insert priceBook;
        PriceBookEntry priceBookAddons = new PriceBookEntry(UnitPrice = arrangeParams.unitPrice, Product2Id = productAddon.Id, IsActive = true, PriceBook2Id = idPricebook, UseStandardPrice = false);
        insert priceBookAddons;

        Subsidiary__c subsidiary = new Subsidiary__c();
        insert subsidiary;
        Product_Configuration__c prodConfigDb = TestData.createProductConfiguration(subsidiary.Id, null, arrangeParams.productName);
        String netSuiteId = arrangeParams.productName == 'Kayako' ? '' :
            String.valueOf(Integer.valueof((Math.random() * 1000000000)));
        String parentSubscriptionId = 'A-S00000000';
        Opportunity opp = new Opportunity(Name = acct.Name + ' Opportunity', StageName = 'Pending', Type = 'Renewal',
            CloseDate = System.today().addMonths(1), AccountId = acct.Id, OwnerId = userId,
            Product_Configuration__c = prodConfigDb.Id, Product__c = arrangeParams.productName,
            Current_Product__c = arrangeParams.currentProduct,
            Current_Product_Edition__c = arrangeParams.currentProductEdition,
            Current_Product_Edition_Label__c = arrangeParams.currentProductEditionLabel,
            Current_Success_Level__c = arrangeParams.currentSuccessLevel,
            Current_Billing_Term__c = arrangeParams.billingTerm, Current_Term__c = arrangeParams.currentTerm,
            Current_ARR__c = arrangeParams.currentARR, Current_Seats__c = arrangeParams.quantity,
            Current_Primary_Contact_Email__c = arrangeParams.email, Renewal_Date__c = Date.today(),
            Current_Addons__c = arrangeParams.currentAddonsARR == 0.0 ? 0 : 1,
            Current_Addons_ARR__c = arrangeParams.currentAddonsARR,
            NetSuite_ID__c = netSuiteId,
            Parent_Subscription_ID__c = parentSubscriptionId);
        insert opp;
    }
    
}