metadata/sf-prod/force-app/main/default/objects/Account/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <label>Success Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Success_Levels</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Addons__c.field-meta.xml
<CustomField>
    <fullName>Current_Addons__c</fullName>
    <label>Current Addons</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Addons_ARR__c.field-meta.xml
<CustomField>
    <fullName>Current_Addons_ARR__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Current Addons ARR = Current ARR - current master products ARR</description>
    <inlineHelpText>Current annual recurring revenue (ARR) of add-on products only (i.e. non-master products which cannot be sold separately)</inlineHelpText>
    <label>Current Addons ARR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_ARR__c.field-meta.xml
<CustomField>
    <fullName>Current_ARR__c</fullName>
    <description>Current ARR = master products ARR + addons ARR of the parent subscription.</description>
    <inlineHelpText>Total annual recurring revenue (ARR) of the current (parent) subscription (include both addons ARR and master products ARR)</inlineHelpText>
    <label>Current ARR</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Billing_Term__c.field-meta.xml
<CustomField>
    <fullName>Current_Billing_Term__c</fullName>
    <label>Current Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Billing_Frequency</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Primary_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Current_Primary_Contact_Email__c</fullName>
    <label>Current Primary Contact Email</label>
    <type>Email</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Product__c.field-meta.xml
<CustomField>
    <fullName>Current_Product__c</fullName>
    <label>Current Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Product_Edition__c.field-meta.xml
<CustomField>
    <fullName>Current_Product_Edition__c</fullName>
    <label>Current Product Edition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Seats__c.field-meta.xml
<CustomField>
    <fullName>Current_Seats__c</fullName>
    <label>Current Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Current_Success_Level__c</fullName>
    <label>Current Success Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Success_Levels</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Current_Term__c.field-meta.xml
<CustomField>
    <fullName>Current_Term__c</fullName>
    <inlineHelpText>Term of the current contract (the one being renewed) in months. 0 (zero) is for EVERGREEN subscriptions.</inlineHelpText>
    <label>Current Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Parent_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Parent_Subscription_ID__c</fullName>
    <description>A valid NetSuite or Zuora (for Kayako) subscription number of the parent/renewed subscription.</description>
    <inlineHelpText>A valid NetSuite or Zuora (for Kayako) subscription number of the parent/renewed subscription.</inlineHelpText>
    <label>Parent Subscription ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>&apos;Product Family&apos; is required, please refer PB001 for details.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Configuration</label>
    <referenceTo>Product_Configuration__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Quoting_Entity__c.field-meta.xml
<CustomField>
    <fullName>Quoting_Entity__c</fullName>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quoting_Entities</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <description>Inferred from the success level of the opportunity line items (each line item linked to a product object that has a Success Level field).</description>
    <inlineHelpText>The success level of the subscription added to the primary quote.</inlineHelpText>
    <label>Success Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Success_Levels</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/OpportunityLineItem/fields/Central_ProductCode__c.field-meta.xml
<CustomField>
    <fullName>Central_ProductCode__c</fullName>
    <description>Code of the product in the source system (e.g. NetSuite, Central SF). Must be provided for the legacy product item.</description>
    <inlineHelpText>Code of the product in the source system (e.g. NetSuite, Central SF). Must be provided for the legacy product item.</inlineHelpText>
    <label>Source Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/OpportunityLineItem/fields/Central_ProductName__c.field-meta.xml
<CustomField>
    <fullName>Central_ProductName__c</fullName>
    <description>Name of the product in the source system (e.g. NetSuite, Central SF). Must be provided for the legacy product item.</description>
    <inlineHelpText>Name of the product in the source system (e.g. NetSuite, Central SF). Must be provided for the legacy product item.</inlineHelpText>
    <label>Source Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/OpportunityLineItem/fields/Subscription_Term__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Term__c</fullName>
    <description>The term of the subscription in months. Used in MRR calculation.</description>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/OpportunityLineItem/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <description>LAMBDA-69849 field to derive success level from related Product</description>
    <formula>TEXT(PricebookEntry.Product2.Success_Level__c)</formula>
    <inlineHelpText>Success level of the related product fetched from the Product record</inlineHelpText>
    <label>Success Level</label>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Max_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Max_Quantity__c</fullName>
    <label>Max Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Min_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Min_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Min Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Product_Edition__c.field-meta.xml
<CustomField>
    <fullName>Product_Edition__c</fullName>
    <label>Product Edition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Editions</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Subscription_Terms__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Terms__c</fullName>
    <label>Subscription Terms</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Terms</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Success_Level__c.field-meta.xml
<CustomField>
    <fullName>Success_Level__c</fullName>
    <label>Success Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Success_Levels</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/Product_Configuration__c.object-meta.xml
<CustomObject>
    <label>Product Configuration</label>
    <nameField>
        <label>Product Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>LAMBDA-34344 custom object to replace subsidiary fields on Product configuration with lookups</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/classes/SFCentralOppDescriptionUpdateTest.cls
@isTest
public without sharing class SFCentralOppDescriptionUpdateTest {
    private static String PRODUCT_FAMILY = 'Kayako';
    private static Integer QUANTITY_NO = 5;
    private static Integer UNIT_PRICE = 120; 
    private static String CENTRAL_PRD_NAME = 'Kayako_Central_Product_Name';
    private static String CENTRAL_PRD_CODE = 'Kayako_Central_Product_Code';
    
    static void arrange() {
        Account acct = new Account(Name='Test Account');
        insert acct;
        Id idPricebook = Test.getStandardPricebookId();
        // Product2
        Product2 productDb = new Product2(Name = 'Kayako:Standard:Standard:0:49:Yearly',
            IsActive = true, Product__c = PRODUCT_FAMILY, ProductCode = 'starter', 
            Family = PRODUCT_FAMILY, Success_Level__c = 'Standard', 
            Product_Edition__c = 'Standard', 
            Min_Quantity__c = 1, 
            Max_Quantity__c = 50, 
            Subscription_Terms__c = '1;12;24');
        insert productDb;
        Id userId = TestData.getUser('System Administrator').Id;
         // Pricebook
        Pricebook2 standardPricebook = new Pricebook2(Id = idPricebook, IsActive = true);
        update standardPricebook;
        // PriceBookEntry
        PriceBookEntry priceBook = new PriceBookEntry(UnitPrice = UNIT_PRICE, 
                                                      Product2Id = productDb.Id, 
                                                      IsActive = true, 
                                                      PriceBook2Id = idPricebook, 
                                                      UseStandardPrice = false);
        insert priceBook;
        Subsidiary__c subsidiary = new Subsidiary__c();
        insert subsidiary;
        Product_Configuration__c prodConfigDb = TestData.createProductConfiguration(subsidiary.Id, null, PRODUCT_FAMILY);
        Opportunity opp = new Opportunity(Name = acct.Name + ' Opportunity', StageName = 'Pending', Type = 'Renewal',
            CloseDate = System.today().addMonths(1), AccountId = acct.Id, OwnerId = userId, 
            Product_Configuration__c = prodConfigDb.Id, 
            Product__c = PRODUCT_FAMILY,
            Current_Product__c = 'Kayako Standard',
            Current_Product_Edition__c = 'Standard',
            Current_Success_Level__c = 'Standard',
            Current_Billing_Term__c = 'Annual', 
            Current_Term__c = 1,
            Current_ARR__c = 1500, 
            Current_Seats__c = 1,
            Current_Primary_Contact_Email__c = 'test@test.com', 
            Renewal_Date__c = Date.today(),
            Current_Addons__c = 0,
            Current_Addons_ARR__c = 0,
            //Quoting_Entity__c = 'Aclate',
            Parent_Subscription_ID__c = 'A-S00000000');
        insert opp;

        //create your opportunity line item. 
        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            Quantity = QUANTITY_NO,
            Subscription_Term__c = 12,
            PricebookEntryId = priceBook.Id,
            TotalPrice = QUANTITY_NO * priceBook.UnitPrice,
            Central_ProductName__c = CENTRAL_PRD_NAME,
            Central_ProductCode__c = CENTRAL_PRD_CODE
        );
        insert oli;

    }
    @isTest static void centralOpportunityDescUpdateBatchTest() {
        arrange();   

        Test.startTest();   
        SFCentralOppDescriptionUpdate sf = new SFCentralOppDescriptionUpdate(PRODUCT_FAMILY, 
                                                new String[] {'test@test.com'});    
        Database.executeBatch(sf,1);
        Test.stopTest();

        Opportunity opp = [Select ID, Description from Opportunity limit 1];
        System.assertEquals(getDescriptionFieldTestText(), 
                            opp.Description, 
                            'Error Generated Description is not Correct');
    }

    private static String getDescriptionFieldTestText() {
        List<Opportunity> opportunities = [SELECT Id, Description, CreatedDate from Opportunity];
        String description = '';
        for (Opportunity opp : opportunities) {
            description += String.format('{0}/{1}/{2} System: Opportunity migrated from Central SF:', 
                                    new String[]{ String.valueOf(opp.CreatedDate.month()), 
                                                  String.valueOf(opp.CreatedDate.day()), 
                                                  String.valueOf(opp.CreatedDate.year()).substring(2) });
            description += '\r\n';
            description += '----------------------------------------';
            description += '\r\n';
            List<OpportunityLineItem> lineItems = [SELECT Central_ProductName__c, Central_ProductCode__c, 
                                                          Id, Subscription_Term__c, Quantity, TotalPrice
                                                   FROM OpportunityLineItem
                                                   WHERE  OpportunityId = :opp.Id];
            Integer rowNumber = 1;
            for (OpportunityLineItem item: lineItems) {
                description += String.format('{0}- {1}  {2} T:{3} Q:{4} TP:{5}', 
                                        new String[] {String.valueOf(rowNumber),
                                                      item.Central_ProductName__c, 
                                                      item.Central_ProductCode__c, 
                                                      String.valueOf(item.Subscription_Term__c), 
                                                      String.valueOf(item.Quantity), 
                                                      String.valueOf(item.TotalPrice)});
                description += '\r\n';
                rowNumber += 1;
            }
            
            description += '----------------------------------------';
        }
        return description;
    }
}