metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Addresses_Validated__c.field-meta.xml
<CustomField>
    <fullName>Addresses_Validated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should be checked when the addresses for Account and Primary Partner are validated. Used to not allow the opportunity to move to the final quote without the addresses being validated.</description>
    <inlineHelpText>Make sure you verify the customer and partner (if applicable) addresses. Check this box when done. You can&apos;t generate the final quote until you verify. If sold directly, set both shipping and billing addresses on the account. If sold via a partner, set the shipping address for the end-user on the account, and billing address on the partner (since we will be charging them).</inlineHelpText>
    <label>Addresses Validated?</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>This is the quote that will be processed and sent to the customer when you move the opportunity to Final Quote. Opportunity products and all the calculations are based on this quote.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Reseller_Agreement__c/Reseller_Agreement__c.object-meta.xml
<CustomObject>
    <description>Reseller Agreement that a customer has with a subsidiary</description>
    <label>Reseller Agreement</label>
    <nameField>
        <displayFormat>RA# {0000}</displayFormat>
        <label>Reseller Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reseller Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Reseller_Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Account that signed the Reseller Agreement</description>
    <inlineHelpText>Account that signed the Reseller Agreement</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reseller Agreements</relationshipLabel>
    <relationshipName>Reseller_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Reseller_Agreement__c/fields/Reseller_Agreement_Link__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Agreement_Link__c</fullName>
    <description>URL pointing to the reseller agreement (Preferably NetSuite URL)</description>
    <inlineHelpText>URL pointing to the reseller agreement (Preferably NetSuite URL)</inlineHelpText>
    <label>Reseller Agreement Link</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Reseller_Agreement__c/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Subsidiary for which the Reseller Agreement was signed</description>
    <inlineHelpText>Subsidiary for which the Reseller Agreement was signed</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Reseller Agreements</relationshipLabel>
    <relationshipName>Reseller_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>End date for subscriptions in this group.</description>
    <inlineHelpText>End date for subscriptions in this group.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
    <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Out for Signature</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/fields/Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Subsidiary link set automatically when quote is created/updated</description>
    <inlineHelpText>Subsidiary link set automatically when quote is created/updated</inlineHelpText>
    <label>Service Provider</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/fields/Service_Provider_City__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_City__c</fullName>
    <label>Service Provider City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/fields/Service_Provider_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Country__c</fullName>
    <label>Service Provider Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/fields/Service_Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Name__c</fullName>
    <description>ESW entity selling the products on this quote</description>
    <label>Service Provider Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/fields/Service_Provider_Street__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Street__c</fullName>
    <label>Service Provider Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>LAMBDA-34344 custom object to replace subsidiary fields on Product configuration with lookups</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/classes/TestOpportunityTriggerHandler.cls
@isTest
public with sharing class TestOpportunityTriggerHandler {
    static final String LABEL_FAKE_ACCOUNT = 'Fake account';
    static final STRING ROLE_DISTRIBUTOR = 'Distributor';
    static final String ROLE_RESELLLER = 'VAR/Reseller';

    @TestSetup
    static void makeData() {
        TestData.createOpportunityForCPQDocument('Renewal','ACRM');
    }

    @isTest
    static void checkOpportunityPartnersSkippedWhenStageNameIsNotFinalQuote() {
        Opportunity oppy = [SELECT Id, Name,StageName,AccountId FROM Opportunity WHERE Type='Renewal' limit 1];
        Account fakeAccount = new Account(Name=LABEL_FAKE_ACCOUNT);
        insert fakeAccount;
        SBQQ__Quote__c primaryQuote = [
            SELECT Id, SBQQ__Partner__c FROM SBQQ__Quote__c WHERE SBQQ__Opportunity2__c=:oppy.Id LIMIT 1
        ];
        primaryQuote.SBQQ__Partner__c = fakeAccount.Id;
        update primaryQuote;

        Test.startTest();
        oppy.StageName = 'Engaged';
        update oppy;
        System.assert(true, 'Passed if no error occurred.');
        Test.stopTest();
    }

    @isTest
    static void checkOpportunityPartnersFailedWhenResellerSetupIsInvalid() {
        Opportunity oppy = [SELECT Id, Name,StageName,AccountId FROM Opportunity WHERE Type='Renewal' limit 1];
        Account fakeAccount = new Account(Name=LABEL_FAKE_ACCOUNT);
        insert fakeAccount;
        SBQQ__Quote__c primaryQuote = [
            SELECT Id, SBQQ__Partner__c FROM SBQQ__Quote__c WHERE SBQQ__Opportunity2__c=:oppy.Id LIMIT 1
        ];
        primaryQuote.SBQQ__Partner__c = fakeAccount.Id;
        update primaryQuote;
        
        Test.startTest();
        oppy.StageName = System.Label.FinalQuote;
        try {
            update oppy;
            System.assert(false,'Control will not reach here');
        } catch (DMLException dmlex) {
            String message = String.format(System.Label.FinalQuoteIncorrectOpportunityPartner,
                                           new String[]{'partner', ROLE_RESELLLER});
            System.assertEquals(message,dmlex.getDmlMessage(0).trim(),'Verifying error message');
        }
        Test.stopTest();
    }

    @isTest
    static void checkOpportunityPartnersFailedWhenResellerSetupIsInvalidWithDuplicateRole() {
        Opportunity oppy = [SELECT Id, Name,StageName,AccountId FROM Opportunity WHERE Type='Renewal' limit 1];
        Account fakeAccount1 = new Account(Name=LABEL_FAKE_ACCOUNT+' 1');
        Account fakeAccount2 = new Account(Name=LABEL_FAKE_ACCOUNT+' 2');
        insert new Account[] { fakeAccount1, fakeAccount2 };
        SBQQ__Quote__c primaryQuote = [
            SELECT Id, SBQQ__Partner__c FROM SBQQ__Quote__c WHERE SBQQ__Opportunity2__c=:oppy.Id LIMIT 1
        ];
        primaryQuote.SBQQ__Partner__c = fakeAccount1.Id;
        update primaryQuote;
        insert new OpportunityPartner[] {
            new OpportunityPartner(OpportunityId=oppy.Id, AccountToId=fakeAccount1.Id, Role=ROLE_RESELLLER), 
            new OpportunityPartner(OpportunityId=oppy.Id, AccountToId=fakeAccount2.Id, Role=ROLE_RESELLLER)
        };

        Test.startTest();
        oppy.StageName = System.Label.FinalQuote;
        try {
            update oppy;
            System.assert(false,'Control will not reach here');
        } catch (DMLException dmlex) {
            String message = String.format(System.Label.FinalQuoteIncorrectOpportunityPartner,
                                           new String[]{'partner', ROLE_RESELLLER});
            System.assertEquals(message,dmlex.getDmlMessage(0).trim(),'Verifying error message');
        }
        Test.stopTest();
    }

    @isTest
    static void checkOpportunityPartnersFailedWhenDistributorSetupIsInvalid() {
        Opportunity oppy = [SELECT Id, Name,StageName,AccountId FROM Opportunity WHERE Type='Renewal' limit 1];
        Account fakeAccount = new Account(Name=LABEL_FAKE_ACCOUNT);
        insert fakeAccount;
        SBQQ__Quote__c primaryQuote = [
            SELECT Id, SBQQ__Distributor__c FROM SBQQ__Quote__c WHERE SBQQ__Opportunity2__c=:oppy.Id LIMIT 1
        ];
        primaryQuote.SBQQ__Distributor__c = fakeAccount.Id;
        update primaryQuote;

        Test.startTest();
        oppy.StageName = System.Label.FinalQuote;
        try {
            update oppy;
            System.assert(false,'Control will not reach here');
        } catch (DMLException dmlex) {
            String message = String.format(System.Label.FinalQuoteIncorrectOpportunityPartner,
                                           new String[]{'distributor', ROLE_DISTRIBUTOR});
            System.assertEquals(message,dmlex.getDmlMessage(0).trim(),'Verifying error message');
        }
        Test.stopTest();
    }

    @isTest
    static void checkOpportunityPartnersFailedWhenDistributorSetupIsInvalidWithDuplicateRole() {
        Opportunity oppy = [SELECT Id, Name,StageName,AccountId FROM Opportunity WHERE Type='Renewal' limit 1];
        Account fakeAccount1 = new Account(Name=LABEL_FAKE_ACCOUNT+' 1');
        Account fakeAccount2 = new Account(Name=LABEL_FAKE_ACCOUNT+' 2');
        insert new Account[] { fakeAccount1, fakeAccount2 };
        SBQQ__Quote__c primaryQuote = [SELECT Id, SBQQ__Distributor__c FROM SBQQ__Quote__c
                                       WHERE SBQQ__Opportunity2__c=:oppy.Id LIMIT 1];
        primaryQuote.SBQQ__Distributor__c = fakeAccount1.Id;
        update primaryQuote;
        OpportunityPartner fakeDistributor1 = new OpportunityPartner(
            OpportunityId=oppy.Id, AccountToId=fakeAccount1.Id, Role=ROLE_DISTRIBUTOR
        );
        OpportunityPartner fakeDistributor2 = new OpportunityPartner(
            OpportunityId=oppy.Id, AccountToId=fakeAccount2.Id, Role=ROLE_DISTRIBUTOR
        );
        insert new OpportunityPartner[] { fakeDistributor1, fakeDistributor2 };

        Test.startTest();
        oppy.StageName = System.Label.FinalQuote;
        try {
            update oppy;
            System.assert(false,'Control will not reach here');
        } catch (DMLException dmlex) {
            String message = String.format(System.Label.FinalQuoteIncorrectOpportunityPartner,
                                           new String[]{'distributor', ROLE_DISTRIBUTOR});
            System.assertEquals(message,dmlex.getDmlMessage(0).trim(),'Verifying error message');
        }
        Test.stopTest();
    }

    @isTest
    static void checkOpportunityValidations() {
        Opportunity testOpportunity = [SELECT Id, Name,StageName FROM Opportunity WHERE Type='Renewal' limit 1];
        Account testResellerAccount = new Account
                                    (Id = null, 
                                    Name = 'Test Reseller account', 
                                    BillingCountry = 'USA', 
                                    BillingCity = 'New York',
                                    BillingState ='New York',
                                    BillingStreet = 'Test Times Square Corner');
        insert testResellerAccount;
        OpportunityPartner oppyPartner = new OpportunityPartner
                                        (OpportunityId=testOpportunity.Id,
                                        AccountToId=testResellerAccount.Id,
                                        Role='Distributor');
        insert oppyPartner;
        SBQQ__Quote__c primaryQuote = [SELECT Id, SBQQ__Status__c,Service_Provider_Name__c,Service_Provider_Street__c,
                                       Service_Provider_City__c,Service_Provider_Country__c, Service_Provider__c
                                       FROM SBQQ__Quote__c
                                       WHERE SBQQ__Opportunity2__c=:testOpportunity.Id LIMIT 1];
        primaryQuote.SBQQ__Distributor__c = testResellerAccount.Id;
        update primaryQuote;
        Contact testContact = new Contact(LastName = 'LastName', Email = 'test@test2.com', HasOptedOutOfEmail = false,AccountId=testResellerAccount.Id);
        insert testContact;
        Test.startTest();
        //break the validation
        testOpportunity.Addresses_Validated__c = true;
        testOpportunity.StageName = System.Label.FinalQuote;
        try {
            update testOpportunity;
            System.assert(false,'Control will not reach here');
        } catch (DMLException dmlex) {
            String message = '';
            message = message + System.Label.FinalQuoteError;
            System.assertEquals(message,dmlex.getDmlMessage(0).trim(),'Verifying error message');
        }
       	Reseller_Agreement__c agreement = new Reseller_Agreement__c(
            Account__c = testResellerAccount.Id,
            Subsidiary__c = primaryQuote.Service_Provider__c,
            Reseller_Agreement_Link__c = 'https://www.trilogy.com'
        );
        insert agreement;
		primaryQuote.SBQQ__EndDate__c = Date.today()+90;
        primaryQuote.SBQQ__Status__c = 'Draft';
        primaryQuote.SBQQ__Primarycontact__c=testContact.Id;
        testOpportunity.SBQQ__PrimaryQuote__c = primaryQuote.Id;
        update primaryQuote;
        update testOpportunity;
        System.assert(true,'No error occurred test passed!!');
        Test.stopTest();
    }

    @isTest
    static void checkOpportunityAddressValidations() {
        Opportunity testOpportunity = [SELECT Id, Name,StageName,AccountId FROM Opportunity WHERE Type='Renewal' limit 1];
        Account testResellerAccount = new Account
                                    (Id = null, 
                                    Name = 'Test Reseller account', 
                                    BillingCountry = 'USA', 
                                    BillingCity = 'New York');
        insert testResellerAccount;
        OpportunityPartner oppyPartner = new OpportunityPartner
                                        (OpportunityId=testOpportunity.Id,
                                        AccountToId=testResellerAccount.Id,
                                        Role='Distributor');
        insert oppyPartner;
        Contact testContact = new Contact(LastName = 'LastName', Email = 'test@test2.com', HasOptedOutOfEmail = false,AccountId=testResellerAccount.Id);
        insert testContact;
        SBQQ__Quote__c primaryQuote = [SELECT Id, SBQQ__Status__c,Service_Provider_Name__c,Service_Provider_Street__c,
                                       Service_Provider_City__c,Service_Provider_Country__c,
                                       SBQQ__Primary__c,SBQQ__EndDate__c, Service_Provider__c FROM SBQQ__Quote__c
                                       WHERE SBQQ__Opportunity2__c=:testOpportunity.Id LIMIT 1];
        primaryQuote.SBQQ__Distributor__c=testResellerAccount.Id;
        update primaryQuote;
        Reseller_Agreement__c agreement = new Reseller_Agreement__c(
            Account__c = testResellerAccount.Id,
            Subsidiary__c = primaryQuote.Service_Provider__c,
            Reseller_Agreement_Link__c = 'https://www.trilogy.com'
        );
        insert agreement;

        Test.startTest();
        //break the validation
        testOpportunity.Addresses_Validated__c = true;
        testOpportunity.StageName = System.Label.FinalQuote;
        try {
            update testOpportunity;
            System.assert(false,'Control will not reach here');
        } catch (DMLException dmlex) {
            String message = '';
            message = message +System.Label.FinalQuoteBillingAddressError;
            System.assertEquals(message,dmlex.getDmlMessage(0).trim(),'Verifying error message');
        }
        testResellerAccount.BillingState ='New York';
        testResellerAccount.BillingStreet = 'Test Times Square Corner';
        primaryQuote.SBQQ__Status__c = 'Draft';
        primaryQuote.SBQQ__EndDate__c = Date.today()+90;
        primaryQuote.SBQQ__Primarycontact__c=testContact.Id;
        Account testAccount = [SELECT ID, BillingState,ShippingStreet,ShippingCity,ShippingCountry FROM Account WHERE ID=:testOpportunity.AccountId LIMIT 1];
        testAccount.ShippingStreet='test street';
        testAccount.ShippingCity='New York';
        testAccount.ShippingCountry='United States';
        update testAccount;
        update primaryQuote;
        update testResellerAccount;
        update testOpportunity;
        System.assert(true,'No error occurred test passed!!');
        //checking account billing address
        testOpportunity.StageName = 'Pending';
        update testOpportunity;
        delete agreement;
        delete testResellerAccount;
        testAccount.BillingCity='';
        update testAccount;
        Contact testContact2 = new Contact(LastName = 'LastName2', Email = 'test@test2.com',AccountId=testAccount.Id);
        insert testContact2;
        primaryQuote.SBQQ__Status__c = 'Draft';
        primaryQuote.SBQQ__PrimaryContact__c=testContact2.Id;
        primaryQuote.SBQQ__Distributor__c=null;
        update primaryQuote;
        testOpportunity.StageName = System.Label.FinalQuote;
        try {
            update testOpportunity;
            System.assert(false,'Control will not reach here');
        } catch (DMLException dmlex) {
            String message = '';
            message = message  + OpportunityTriggerHandler.formatMessage('Billing',System.Label.FinalQuoteAccountAddressError);
            System.assertEquals(message,dmlex.getDmlMessage(0).trim(),'Verifying error message');
        }
        Test.stopTest();
    }
}