metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Addresses_Validated__c.field-meta.xml
<CustomField>
    <fullName>Addresses_Validated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should be checked when the addresses for Account and Primary Partner are validated. Used to not allow the opportunity to move to the final quote without the addresses being validated.</description>
    <inlineHelpText>Make sure you verify the customer and partner (if applicable) addresses. Check this box when done. You can&apos;t generate the final quote until you verify. If sold directly, set both shipping and billing addresses on the account. If sold via a partner, set the shipping address for the end-user on the account, and billing address on the partner (since we will be charging them).</inlineHelpText>
    <label>Addresses Validated?</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>ID of the NetSuite renewal subscription associated with this opportunity. If matches &quot;O-&lt;ID&gt;&quot; then the ID points to NetSuite Opportunity record instead.</inlineHelpText>
    <label>NetSuite ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>&apos;Product Family&apos; is required, please refer PB001 for details.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Configuration</label>
    <referenceTo>Product_Configuration__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/Product_Configuration__c.object-meta.xml
<CustomObject>
    <label>Product Configuration</label>
    <nameField>
        <label>Product Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Manual_Quote__c.field-meta.xml
<CustomField>
    <fullName>Manual_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual O2C</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Processed_via_OTC__c.field-meta.xml
<CustomField>
    <fullName>Processed_via_OTC__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Set to TRUE if closed deals should be finalized via the OTC team (e.g. invoice processing). OTC-related tasks are automatically generated for the product when the value is TRUE.</description>
    <inlineHelpText>Set to TRUE if closed deals should be finalized via the OTC team (e.g. invoice processing). OTC-related tasks are automatically generated for the product when the value is TRUE.</inlineHelpText>
    <label>Processed via O2C</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <externalId>true</externalId>
    <label>NetSuite ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Out for Signature</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>LAMBDA-34344 custom object to replace subsidiary fields on Product configuration with lookups</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Subsidiary__c/fields/Netsuite_Id__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_Id__c</fullName>
    <externalId>true</externalId>
    <label>Netsuite Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/User/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <description>ID which is taken from the URL of the employee profile page in the NetSuite</description>
    <externalId>true</externalId>
    <inlineHelpText>Employee profile page is available at https://4914352.app.netsuite.com/app/common/entity/employee.nl?id=&lt;ID&gt; (replace &lt;ID&gt; with this field value)</inlineHelpText>
    <label>NetSuite ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/ElectronicSignTests.cls
@isTest 
public with sharing class ElectronicSignTests {
   static final String DOCUMENT_NAME = 'Test';
   static final String AFTER_SENDING_STAGE_NAME = 'Quote Follow-Up';
   static final Id DMITRY_BAKAEV_ID = [SELECT Id FROM User WHERE Name='Dmitry Bakaev'].Id;

   @isTest
   static void e2eTest(){ // Run the process with inserting a CPQ Quote document to test End2End
      Opportunity resultOpportunity = e2eTestCommon('Kayako', 'Renewal', false, false);
      System.assert(resultOpportunity.StageName == AFTER_SENDING_STAGE_NAME, 
         'After sending to signing the opportunity should move to Quote Follow-Up.');
      System.assert(resultOpportunity.Description.contains('quote'), 
         'After sending to signing a record should be added to the description.');
   }

   @isTest
   static void e2eTestManualQuote(){ // We should not process manual quotes
      Opportunity resultOpportunity = e2eTestCommon('SLI', 'Renewal', true, false);
      System.assert(resultOpportunity.StageName != AFTER_SENDING_STAGE_NAME, 
         'Manual quotes should not be processed for eSigning.');
      System.assert(String.isBlank(resultOpportunity.Description), 
         'Manual quotes should not be processed for eSigning.');
   }

   @isTest
   static void e2eTestProcessViaOtcQuote(){ // We should not process manual quotes
      Opportunity resultOpportunity = e2eTestCommon('SLI', 'Renewal', false, true);
      System.assert(resultOpportunity.StageName != AFTER_SENDING_STAGE_NAME, 
         'Quotes processed via OTC should not be processed for eSigning.');
      System.assert(String.isBlank(resultOpportunity.Description), 
         'Quotes processed via OTC should not be processed for eSigning.');
   }
   
   
   // Creates an opportunity with the given Owner, Product Familty and Type and runs the eSigning sequence with the config given
   static Opportunity e2eTestCommon(String family, String type,  Boolean manualQuote, Boolean prcessedViaOtc ){
      Test.startTest();
      SBQQ.TriggerControl.disable();
      User user = TestData.getUser('System Administrator');
      
      
      // Product_Configuration__c
      Subsidiary__c subsidiary = new Subsidiary__c(
               Name = 'Skyvera, LLC',
               City__c = 'New York',
               State__c = 'NY',
               Country__c = 'United States',
               Street__c = 'Test Broadway and fifth'
      );
      insert subsidiary;
      Product_Configuration__c prodConfig = TestData.createProductConfiguration(subsidiary.Id, null, family);
      prodConfig.Manual_Quote__c = manualQuote;
      prodConfig.Processed_via_OTC__c = prcessedViaOtc;
      update prodConfig;
      Product_Configuration__c prodConfigDb = [SELECT Id FROM Product_Configuration__c
                                               WHERE Id = :prodConfig.Id];

      user.echosign_dev1__EchoSign_Allow_Delegated_Sending__c = true;
      user.echosign_dev1__EchoSign_Email_Verified__c = true;
      update user;

      User dmitryUser = [select Id from User where id = :DMITRY_BAKAEV_ID];
      System.runAs(dmitryUser) {
         UserRole userRole = [select id from UserRole where name = 'System Administrator'];
        
         user.UserRoleId = userRole.Id;
         user.isActive = true;
         update user;
      }

      // 'Quote Approver' is not configured in the 'Product Configuration'
      Opportunity testOpportunity = TestData.createOpportunityForCPQDocument(type, family);
      testOpportunity.OwnerId = user.Id;
      testOpportunity.Product__c = family;
      testOpportunity.Type = type;
      testOpportunity.Product_Configuration__c = prodConfigDb.Id;
      testOpportunity.Product_Configuration__r = prodConfigDb;
      testOpportunity.StageName = 'Final Quote';
      testOpportunity.NetSuite_ID__c = 'TEST-ElectronicSignTests-'+family;
      testOpportunity.Addresses_Validated__c = true;
      update testOpportunity;

      SBQQ__QuoteDocument__c doc = TestData.createCpqQuoteDocument(testOpportunity, DOCUMENT_NAME); // Insert trigger for SBQQ_QuoteDocument is executed        
      SBQQ.TriggerControl.enable();
      update new SBQQ__Quote__c(Id = doc.SBQQ__Quote__c, SBQQ__Status__c = 'Accepted');

      List<SBQQ__QuoteDocument__c> toSend = new List<SBQQ__QuoteDocument__c>();
      toSend.add(doc);
      QuoteSigningQueuable.EnqueueSigningTasks(toSend);
      Test.stopTest();
      Opportunity resultOpportunity = [SELECT StageName, Description, Product_Configuration__c 
                                       FROM Opportunity WHERE Id=:testOpportunity.Id];

      return resultOpportunity;
   }
}