metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Draft__c.field-meta.xml
<CustomField>
    <fullName>Draft__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field excludes the opportunity from process automation. It&apos;s used when we import new opportunity and its renewal date is too close. It should be reviewed by the Sales Manager before we start sending automated emails to customers.</description>
    <inlineHelpText>Excludes the opportunity from the renewal process automation. It was likely imported too close to the Renewal Date. Review the opportunity, adjust the stage appropriately, and then uncheck this field.</inlineHelpText>
    <label>Draft</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>ID of the NetSuite renewal subscription associated with this opportunity. If matches &quot;O-&lt;ID&gt;&quot; then the ID points to NetSuite Opportunity record instead.</inlineHelpText>
    <label>NetSuite ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Parent_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Parent_Subscription_ID__c</fullName>
    <description>A valid NetSuite or Zuora (for Kayako) subscription number of the parent/renewed subscription.</description>
    <inlineHelpText>A valid NetSuite or Zuora (for Kayako) subscription number of the parent/renewed subscription.</inlineHelpText>
    <label>Parent Subscription ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>&apos;Product Family&apos; is required, please refer PB001 for details.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/User/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <description>ID which is taken from the URL of the employee profile page in the NetSuite</description>
    <externalId>true</externalId>
    <inlineHelpText>Employee profile page is available at https://4914352.app.netsuite.com/app/common/entity/employee.nl?id=&lt;ID&gt; (replace &lt;ID&gt; with this field value)</inlineHelpText>
    <label>NetSuite ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/MarkOverdueOppAsDraftTests.cls
@isTest
public with sharing class MarkOverdueOppAsDraftTests {

    private static Opportunity insertOpportunity(Date renewalDate) {
        User user = TestData.getUser('System Administrator');
        Opportunity opp = new Opportunity(
                Name = 'Test Opportunity',
                StageName = 'Proposal',
                CloseDate = renewalDate.addDays(-1),
                Type = 'Renewal',
                OwnerId = user.Id,
                NetSuite_ID__c = '1234',
                Parent_Subscription_ID__c = 'A-S00000000',
                Product__c = 'Acorn',
                Renewal_Date__c = renewalDate
        );

        return opp;
    }

    @isTest
    static void draftShouldBeTrueForOpporunityRenewalPassed() {
        //Arrange
        Opportunity opp = insertOpportunity(System.now().date().addDays(-7));

        //Act
        Insert opp;
        Opportunity retrievedOpp = [select Id, Draft__c from Opportunity];

        //Assert
        System.assert(retrievedOpp.Draft__c, 'Draft flag should be set to true');
    }


    @isTest
    static void draftShouldBeTrueForOpporunityRenewalToday() {
        //Arrange
        Opportunity opp = insertOpportunity(System.now().date());

        //Act
        Insert opp;
        Opportunity retrievedOpp = [select Id, Draft__c from Opportunity];

        //Assert
        System.assert(retrievedOpp.Draft__c, 'Draft flag should be set to true');
    }

    @isTest
    static void draftShouldBeFalseForOpporunityRenewalFuture() {
          //Arrange
        Opportunity opp = insertOpportunity(System.now().date().addDays(7) );

        //Act
        Insert opp;
        Opportunity retrievedOpp = [select Id, Draft__c from Opportunity];

        //Assert
        System.assert(!retrievedOpp.Draft__c, 'Draft flag should be set to false');
    }
    
}