metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Draft__c.field-meta.xml
<CustomField>
    <fullName>Draft__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field excludes the opportunity from process automation. It&apos;s used when we import new opportunity and its renewal date is too close. It should be reviewed by the Sales Manager before we start sending automated emails to customers.</description>
    <inlineHelpText>Excludes the opportunity from the renewal process automation. It was likely imported too close to the Renewal Date. Review the opportunity, adjust the stage appropriately, and then uncheck this field.</inlineHelpText>
    <label>Draft</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>ID of the NetSuite renewal subscription associated with this opportunity. If matches &quot;O-&lt;ID&gt;&quot; then the ID points to NetSuite Opportunity record instead.</inlineHelpText>
    <label>NetSuite ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Parent_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Parent_Subscription_ID__c</fullName>
    <description>A valid NetSuite or Zuora (for Kayako) subscription number of the parent/renewed subscription.</description>
    <inlineHelpText>A valid NetSuite or Zuora (for Kayako) subscription number of the parent/renewed subscription.</inlineHelpText>
    <label>Parent Subscription ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>&apos;Product Family&apos; is required, please refer PB001 for details.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Configuration</label>
    <referenceTo>Product_Configuration__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/Product_Configuration__c.object-meta.xml
<CustomObject>
    <label>Product Configuration</label>
    <nameField>
        <label>Product Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Contracting_Entity_Other__c.field-meta.xml
<CustomField>
    <fullName>Contracting_Entity_Other__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>All other locales</description>
    <inlineHelpText>All other locales</inlineHelpText>
    <label>Contracting Entity Other</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Product Configurations (Contracting Entity Other)</relationshipLabel>
    <relationshipName>OtherEntities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Contracting_Entity_US_and_AE__c.field-meta.xml
<CustomField>
    <fullName>Contracting_Entity_US_and_AE__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>USA and United Arab Emirates</description>
    <inlineHelpText>USA and United Arab Emirates</inlineHelpText>
    <label>Contracting Entity US and AE</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Product Configurations</relationshipLabel>
    <relationshipName>USandUAEEntities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Fulfillment_Email__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Email__c</fullName>
    <label>Fulfillment Email</label>
    <type>Email</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Manual_Quote__c.field-meta.xml
<CustomField>
    <fullName>Manual_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual O2C</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/New_Business_Enabled__c.field-meta.xml
<CustomField>
    <fullName>New_Business_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specify if the New Business service is running for the product family (certain automation processes disabled when false)</description>
    <inlineHelpText>Specify if the New Business service is running for the product family (certain automation processes disabled when false)</inlineHelpText>
    <label>New Business Enabled</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Non_US_Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Non_US_Provider_Name__c</fullName>
    <label>Non-US Service Provider Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Renewal_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specify if the renewal service is running for the product family (disable certain automation processes when false)</description>
    <inlineHelpText>Specify if the renewal service is running for the product family (disable certain automation processes when false)</inlineHelpText>
    <label>Renewal Enabled</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/US_Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>US_Provider_Name__c</fullName>
    <label>US Service Provider Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>LAMBDA-34344 custom object to replace subsidiary fields on Product configuration with lookups</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Subsidiary__c/fields/Netsuite_Id__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_Id__c</fullName>
    <externalId>true</externalId>
    <label>Netsuite Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/User/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <description>ID which is taken from the URL of the employee profile page in the NetSuite</description>
    <externalId>true</externalId>
    <inlineHelpText>Employee profile page is available at https://4914352.app.netsuite.com/app/common/entity/employee.nl?id=&lt;ID&gt; (replace &lt;ID&gt; with this field value)</inlineHelpText>
    <label>NetSuite ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/AdvanceRenewalOppToRenewalEngagementTest.cls
@isTest
public with sharing class AdvanceRenewalOppToRenewalEngagementTest {
    
    @isTest
    public static void notActiveOpportunityShouldNotMoveToRenewalEngagementTest() {
        // Arrange
        insertOpportunity(DateTime.now().addDays(5).date(), true);
        // Act
        startFlow();
        // Assert
        Opportunity oppAfterFlow = [SELECT ID, StageName FROM Opportunity];
        System.assert(oppAfterFlow.StageName == 'Pending', 'Opportunity should not move from Pending');
    }

    @isTest
    public static void activeOpportunityShouldMoveToRenewalEngagementTest() {
        // Arrange
        insertOpportunity(DateTime.now().addDays(5).date(), false);
        // Act
        startFlow();
        // Assert
        Opportunity oppAfterFlow = [SELECT ID, StageName FROM Opportunity];
        System.assert(oppAfterFlow.StageName == 'Outreach', 'Opportunity should move to Outreach');
    }

    @isTest
    public static void testOpportunityShouldNotMoveToRenewalEngagementTest() {
        // Arrange
        insertOpportunity(DateTime.now().addDays(5).date(), false);
        Opportunity opp = [SELECT ID, NAME FROM Opportunity];
        opp.name = '_Test_';
        update opp;
        // Act
        startFlow();
        // Assert
        Opportunity oppAfterFlow = [SELECT ID, StageName FROM Opportunity];
        System.assert(oppAfterFlow.StageName == 'Pending', 'Opportunity should move not move to Outreach');
    }

    @isTest
    public static void notRenewalOpportunityShouldNotMoveToRenewalEngagementTest() {
        // Arrange
        insertOpportunity(DateTime.now().addDays(5).date(), false);
        Opportunity opp = [SELECT ID, type FROM Opportunity];
        opp.type = 'New Business';
        update opp;
        // Act
        startFlow();
        // Assert
        Opportunity oppAfterFlow = [SELECT ID, StageName FROM Opportunity];
        System.assert(oppAfterFlow.StageName == 'Pending', 'Opportunity should move not move to Outreach');
    }

    /*@isTest
    public static void closeDateMoreThan121DaysShouldNotMoveToRenewalEngagementTest() {
        // Arrange
        insertOpportunity(DateTime.now().addDays(122).date(), false);
        // Act
        startFlow();
        // Assert
        Opportunity oppAfterFlow = [SELECT ID, StageName FROM Opportunity];
        System.assert(oppAfterFlow.StageName == 'Pending', 'Opportunity should not move to Renewal Engagement');
    }*/

    private static void startFlow() {
        Map<String, Object> params = new Map<String, Object>();
        Flow.Interview.AdvanceRenewalOpportunityFromPendingToRenewalEngagement flow = 
           new Flow.Interview.AdvanceRenewalOpportunityFromPendingToRenewalEngagement(params);
        
        flow.start();
    }

    private static Opportunity insertOpportunity(Date renewalDate, Boolean draft) {
        Subsidiary__c subsidiary = new Subsidiary__c();
        insert subsidiary;
        Product_Configuration__c prodConfig = TestData.createProductConfiguration(subsidiary.Id, null,'Kayako');
        /*Product_Configuration__c prodConfig = new Product_Configuration__c(Name = 'Kayako',
                 Product__c = 'Kayako',
                 US_Provider_Name__c = TestData.USA_PROVIDER_NAME,
                 Non_US_Provider_Name__c = TestData.NON_USA_PROVIDER_NAME,
                 Fulfillment_Email__c='test@trilogy.com',
                 Manual_Quote__c = false,
                 Renewal_Enabled__c = true,
                 New_Business_Enabled__c = true,
                 Contracting_Entity_US_and_AE__c = subsidiary.Id,
                 Contracting_Entity_Other__c = subsidiary.Id);
        insert prodConfig;*/
        Product_Configuration__c prodConfigDb = [SELECT Id FROM Product_Configuration__c
                                                 WHERE Id = :prodConfig.Id];

        User user = TestData.getUser('System Administrator');
        Opportunity opp = new Opportunity(
                Name = 'Advance Renewal',
                StageName = 'Pending',
                CloseDate = renewalDate.addDays(-1),
                Type = 'Renewal',
                OwnerId = user.Id,
                NetSuite_ID__c = '1234',
                Product__c = 'Kayako',
                Renewal_Date__c = renewalDate,
                Draft__c = draft,
                Parent_Subscription_ID__c = 'A-S12345678',
                Product_Configuration__c = prodConfigDb.Id,
                Product_Configuration__r = prodConfigDb
        );
        insert opp;
        return opp;
    }

}