metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Master_Products_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Master_Products_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SUM([OpportunityProduct where Product.ChargeType = Recurring and Product.Edition != Add-On and Total Price &gt; 0].Quantity)</description>
    <inlineHelpText>The total quantity of non zero priced, recurring, and non add-on products on the opportunity</inlineHelpText>
    <label>Master Products Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Opportunity_Term__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Term__c</fullName>
    <description>max term of the opportunity renewal products non Add-On with Total Price &gt; 0</description>
    <inlineHelpText>Term of the subscription after renewal (max term of none zero renewable price opportunity products that are not Add-On)</inlineHelpText>
    <label>Opportunity Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/UpdateOpportunitiesBatchTest.cls
@isTest
public class UpdateOpportunitiesBatchTest {
    static final String TEST_EMAIL = 'test@trilogy.com';

    @isTest
    static void update_all_opportunites() {
        //Arrange
        TestData.createOppAndContract();
        Test.StartTest();
        List<Opportunity> opps = [SELECT Id, LastModifiedDate, Master_Products_Quantity__c 
                                  FROM Opportunity WHERE Master_Products_Quantity__c != 0];
        opps[0].Master_Products_Quantity__c = 0;
        opps[0].Opportunity_Term__c = 0;
        //Act
        update opps;
        UpdateOpportunitiesBatch batch = new UpdateOpportunitiesBatch(new String[] {TEST_EMAIL});
        Database.executeBatch(batch, 200);
        //Verify
        List<Opportunity> updatedOpp = [select Id, LastModifiedDate, Master_Products_Quantity__c, Opportunity_Term__c 
                                        From Opportunity];
        Test.StopTest();
        System.assert(updatedOpp[0].Master_Products_Quantity__c == 20.0, 
                        'Error Opportunity Master Products Quantitiy not updated');
        System.assert(updatedOpp[0].Opportunity_Term__c == 1, 'Error Opportunity Term not updated');
        
    }
}