metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Parent_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Parent_Subscription_ID__c</fullName>
    <description>A valid NetSuite or Zuora (for Kayako) subscription number of the parent/renewed subscription.</description>
    <inlineHelpText>A valid NetSuite or Zuora (for Kayako) subscription number of the parent/renewed subscription.</inlineHelpText>
    <label>Parent Subscription ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>&apos;Product Family&apos; is required, please refer PB001 for details.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/SamePrimaryContactOppControllerTest.cls
@isTest
public class SamePrimaryContactOppControllerTest {
  @isTest 
  static void testGetSamePrimaryContactOpp(){
    Opportunity opp = new Opportunity();
    opp.Name = 'Test Opp';
    opp.CloseDate = System.today();
    opp.Renewal_Date__c = System.today();
    opp.StageName = 'Pending';
    opp.Type = 'Renewal';
    opp.Product__c = 'Test';
    opp.Parent_Subscription_ID__c = 'Test';
    insert opp;

    Contact con = new Contact();
    con.FirstName = 'test first name';
    con.LastName = 'test last name';
    con.Email = 'test@test.com';
    insert con;

    OpportunityContactRole conRole = new OpportunityContactRole();
    conRole.OpportunityId = opp.Id;
    conRole.ContactId = con.Id;
    conRole.IsPrimary = true;
    insert conRole;


    Test.startTest();
    List<Opportunity> opps = SamePrimaryContactOppController.getSamePrimaryContactOpp(opp.Id);
    Assert.areEqual(0, opps.size(), 'Should be 0 opp');
    Test.stopTest();
  }    
}