metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Parent_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Parent_Subscription_ID__c</fullName>
    <description>A valid NetSuite or Zuora (for Kayako) subscription number of the parent/renewed subscription.</description>
    <inlineHelpText>A valid NetSuite or Zuora (for Kayako) subscription number of the parent/renewed subscription.</inlineHelpText>
    <label>Parent Subscription ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>&apos;Product Family&apos; is required, please refer PB001 for details.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Configuration</label>
    <referenceTo>Product_Configuration__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/OpportunityLineItem/fields/Subscription_Term__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Term__c</fullName>
    <description>The term of the subscription in months. Used in MRR calculation.</description>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Min_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Min_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Min Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product2/fields/Subscription_Terms__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Terms__c</fullName>
    <label>Subscription Terms</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Terms</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/Product_Configuration__c.object-meta.xml
<CustomObject>
    <label>Product Configuration</label>
    <nameField>
        <label>Product Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_Families</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>LAMBDA-34344 custom object to replace subsidiary fields on Product configuration with lookups</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/classes/MigrationQuoteCreationBatchTest.cls
@isTest
public with sharing class MigrationQuoteCreationBatchTest {
    @isTest
    public static void e2eTest(){
        arrange(15.00, 20, 1, null);
        Test.startTest();
        Database.executeBatch(new MigrationQuoteCreationBatch('Sococo'), 1);
        Test.stopTest();
        LIST<SBQQ__Quote__c> quotes = [SELECT ID, CreatedDate, CreatedBy.Name
        FROM SBQQ__Quote__c];
        System.assert(quotes.size() > 0, 'Quotes should be created.');
    }

    @isTest
    public static void e2eForOneOppTest(){
        arrange(15.00, 20, 1, null);
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Test.startTest();
        Database.executeBatch(new MigrationQuoteCreationBatch(opp.Id), 1);
        Test.stopTest();
        LIST<SBQQ__Quote__c> quotes = [SELECT ID, CreatedDate, CreatedBy.Name, CurrencyIsoCode
                                        FROM SBQQ__Quote__c];
        System.assert(quotes.size() == 1, 'A Quote should be created.');
    }

    @isTest
    public static void e2eForEuroOppTest(){
        arrange(15.00, 20, 1, 'EUR');
        Opportunity opp = [SELECT Id, CurrencyIsoCode FROM Opportunity LIMIT 1];
        Test.startTest();
        Database.executeBatch(new MigrationQuoteCreationBatch(opp.Id), 1);
        Test.stopTest();
        LIST<SBQQ__Quote__c> quotes = [SELECT ID, CreatedDate, CreatedBy.Name, CurrencyIsoCode
                                        FROM SBQQ__Quote__c];
        System.assert(quotes.size() == 1, 'A Quote should be created.');
        System.assert(quotes[0].CurrencyIsoCode == opp.CurrencyIsoCode, 
                        'Quote currency should match Opportunity currency');
    }

    @isTest
    public static void notRenewalOpportunitiesShouldNotBeProcessed(){
        arrange(15.00, 20, 1, null);
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        opp.type = 'New Business';
        update opp;
        Test.startTest();
        Database.executeBatch(new MigrationQuoteCreationBatch(opp.Id), 1);
        List<SBQQ__Quote__c> quotes = [SELECT Id,SBQQ__Opportunity2__c 
                                        FROM SBQQ__Quote__c LIMIT 10];
        Test.stopTest();
        
        // Assert
        System.assert(quotes.size() == 0, 'A Quote should not be generated for non renewal opportunities');
    }

    static void arrange(Decimal unitPrice, Integer quantity, Integer term, String currencyIsoCode){
        Account acct = new Account(Name='Test Account');
        insert acct;
        // Product2
        Product2 product;
            product = new Product2(    Name = 'Sococo:Standard:Standard:0:49:Monthly',
                                       CanUseRevenueSchedule = false,
                                       IsActive = true,
                                       Product__c = 'Sococo',
                                       ProductCode = 'starter',
                                       Subscription_Terms__c = '1',
                                       Min_Quantity__c = 1,
                                       SBQQ__SubscriptionTerm__c=12);
        insert product;
        Product2 productDb = [SELECT Id FROM Product2];
        // PriceBook2
        PriceBook2 pb2 = new PriceBook2(Name = 'Standard Price Book',
                                        IsActive = true);
        insert pb2;
        Id idPricebook = Test.getStandardPricebookId();
        // PriceBookEntry
        PriceBookEntry priceBook = new PriceBookEntry(UnitPrice = unitPrice,
                                                     Product2Id = productDb.Id,
                                                     IsActive = true,
                                                     PriceBook2Id = idPricebook,
                                                     UseStandardPrice = false);
        insert priceBook;
        
        PriceBookEntry priceBookDb = [SELECT Id FROM PriceBookEntry];

        if (currencyIsoCode != null) {
            CurrencyType currencyType = [SELECT ConversionRate, Id, IsActive, IsoCode 
                                            FROM CurrencyType where isoCode = :currencyIsoCode
                                        ];
            PriceBookentry currencyEntry = new PricebookEntry(
            Pricebook2Id = idPricebook,
            Product2Id = productDb.Id,
            UnitPrice = unitPrice * currencyType.ConversionRate,
            CurrencyIsoCode = currencyIsoCode,
            IsActive = true);
            insert currencyEntry;

            priceBookDb = [SELECT Id FROM PriceBookEntry WHERE CurrencyIsoCode = :currencyIsoCode];
        }


        // Product_Configuration__c
        Subsidiary__c subsidiary = new Subsidiary__c();
        insert subsidiary;
        Product_Configuration__c prodConfig = TestData.createProductConfiguration(subsidiary.Id, null, 'Sococo');
        Product_Configuration__c prodConfigDb = [SELECT Id FROM Product_Configuration__c];
        // Opportunity
        Opportunity opp = new Opportunity(Name=acct.Name + ' Opportunity',
                                       StageName='Prospecting',
                                       CloseDate=System.today().addMonths(1),
                                       AccountId=acct.Id,
                                       Product_Configuration__c = prodConfigDb.Id,
                                       Type = 'Renewal',
                                       Product__c = 'Sococo',
                                       Renewal_Date__c = system.today(),
                                       Parent_Subscription_ID__c = 'A-S00000000',
                                       CurrencyIsoCode = (currencyIsoCode == null ? 'USD' : currencyIsoCode));
        insert opp;
        Opportunity oppDb = [SELECT Id FROM Opportunity];
        // OpportunityLineItem       
        OpportunityLineItem lineItem = new OpportunityLineItem(Product2Id = productDb.Id,
                                                              Quantity = quantity,
                                                              PricebookEntryId = priceBookDb.Id,
                                                              OpportunityId = oppDb.Id,
                                                              UnitPrice = unitPrice,
                                                              Subscription_Term__c = term);
        insert lineItem;
    }
}