metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Configuration</label>
    <referenceTo>Product_Configuration__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/Product_Configuration__c.object-meta.xml
<CustomObject>
    <label>Product Configuration</label>
    <nameField>
        <label>Product Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Mailbox_Override__c.field-meta.xml
<CustomField>
    <fullName>Mailbox_Override__c</fullName>
    <description>Email domain to use for Outreach sequences, system emails to customers sent via Salesforce, and for PostGrid to send AR warning letters to customers. NetSuite adds a CC recipient automatically for all agreements of renewal Quotes (CC to &quot;renewals@OutboundEmailDomain&quot;). This value can ONLY be changed from NetSuite and it&apos;s automatically synchronized here!</description>
    <inlineHelpText>Email domain to use for Outreach sequences, system emails to customers sent via Salesforce, and for PostGrid to send AR warning letters to customers. NetSuite adds a CC recipient automatically for all agreements of renewal Quotes (CC to &quot;renewals@OutboundEmailDomain&quot;). This value can ONLY be changed from NetSuite and it&apos;s automatically synchronized here!</inlineHelpText>
    <label>Outbound Email Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/RenewalCadenceTracker__c/RenewalCadenceTracker__c.object-meta.xml
<CustomObject>
    <description>Custom object for tracking renewal email candences.</description>
    <label>Renewal Cadence Tracker</label>
    <nameField>
        <label>RCT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Renewal Cadence Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/RenewalCadenceTracker__c/fields/Actual_Email_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Email_Date__c</fullName>
    <label>Actual Email Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/RenewalCadenceTracker__c/fields/Email_Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Email_Scheduled_Date__c</fullName>
    <label>Email Scheduled Date</label>
    <type>Date</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/RenewalCadenceTracker__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <label>Error Log</label>
    <type>TextArea</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/RenewalCadenceTracker__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>CadenceOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/RenewalCadenceTracker__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Errored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/RenewalCadenceTracker__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <label>Templateid</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/SendEmailBatch.cls
global class SendEmailBatch implements Database.Batchable<sObject> {
    
     global Database.QueryLocator start(Database.BatchableContext BC) {
        Date sevenDaysAgo = Date.today().addDays(-7);
        return Database.getQueryLocator(
            'SELECT Id, Opportunity__c, TemplateId__c '+
            'FROM RenewalCadenceTracker__c '+
            'WHERE (Email_Scheduled_Date__c = LAST_N_DAYS:7 Or' +
                  ' Email_Scheduled_Date__c = today)' + ' AND Status__c = \'Scheduled\' '
        );
    }

    global void execute(Database.BatchableContext BC, List<RenewalCadenceTracker__c> scope) {
        for (RenewalCadenceTracker__c tracker : scope) {
            sendEmailForTracker(tracker);
        }
    }

    global void finish(Database.BatchableContext BC) {
    }

    private void sendEmailForTracker(RenewalCadenceTracker__c tracker) {
        // Query Opportunity and Contact Roles
        String message ='';
        String recordId='0052x0000049ZXCAA';
        String templateId=tracker.TemplateId__c;
        List<String> userIds = new List<String>();
        try{
            Opportunity opp = [SELECT Id, Name, Owner.Email,Product_Configuration__r.Mailbox_Override__c
                               FROM Opportunity WHERE Id = :tracker.Opportunity__c LIMIT 1];
            List<OpportunityContactRole> contactRoles = [SELECT ContactId, Contact.Email, IsPrimary FROM OpportunityContactRole WHERE OpportunityId = :opp.Id];
    		recordId =opp.Id;
            // Prepare email addresses
            List<String> toAddresses = new List<String>();
            List<String> ccAddresses = new List<String>(new String[]{opp.Owner.Email}); // Add Opportunity owner to CC
            Id primaryContactId;
            for (OpportunityContactRole ocr : contactRoles) {
                if (ocr.Contact.Email != null) {
                    if (ocr.IsPrimary) {
                        primaryContactId=ocr.contactId;
                        toAddresses.add(ocr.Contact.Email);
                    } else {
                        ccAddresses.add(ocr.Contact.Email);
                    }
                }
            }
            if(primaryContactId==null && opp.OpportunityContactRoles!=null 
                    && !opp.OpportunityContactRoles.isEmpty()) {
                    primaryContactId=opp.OpportunityContactRoles[0].contactId;
                }
            if(primaryContactId==null) {
                
            }
            // Prepare and send email
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            Id fromEmailId = GeneralUtility.getOrgWideEmailIdbyName(opp.Product_Configuration__r.Mailbox_Override__c);
            // Set From Address
            mail.setOrgWideEmailAddressId(fromEmailId);
            mail.setToAddresses(toAddresses);
            mail.setCcAddresses(ccAddresses);
            mail.setTemplateId(tracker.TemplateId__c);
            mail.setWhatId(opp.Id);
            mail.setTargetObjectId(primaryContactId);
            mail.setSaveAsActivity(true);
            mail.setTreatTargetObjectAsRecipient(false);
            Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{mail});
            tracker.Actual_Email_Date__c = Date.today();
            tracker.Status__c = 'Sent';
            update tracker;
        } catch (Exception e) {
            message = 'An exception occurred while sending email for template'+templateId==null?'':templateId + '\n Exception: '+e.getMessage();
            GeneralUtility.postToRecord(recordId, userIds, message);
            tracker.Status__c = 'Errored';
            tracker.Error_Log__c ='Message = '+e.getMessage()+'Stack trace='+e.getStackTraceString(); 
            update tracker;
        }
    }
}