metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Configuration</label>
    <referenceTo>Product_Configuration__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales process</businessProcess>
    <label>Sales</label>
</RecordType>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/Product_Configuration__c.object-meta.xml
<CustomObject>
    <label>Product Configuration</label>
    <nameField>
        <label>Product Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Intro_Survey__c.field-meta.xml
<CustomField>
    <fullName>Intro_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LAMBDA-65516 Field to capture link to the welcome survey record</description>
    <inlineHelpText>Related welcome Survey to be sent in intro email</inlineHelpText>
    <label>Intro Survey</label>
    <referenceTo>Survey</referenceTo>
    <relationshipLabel>Product Configurations</relationshipLabel>
    <relationshipName>Product_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Mailbox_Override__c.field-meta.xml
<CustomField>
    <fullName>Mailbox_Override__c</fullName>
    <description>Email domain to use for Outreach sequences, system emails to customers sent via Salesforce, and for PostGrid to send AR warning letters to customers. NetSuite adds a CC recipient automatically for all agreements of renewal Quotes (CC to &quot;renewals@OutboundEmailDomain&quot;). This value can ONLY be changed from NetSuite and it&apos;s automatically synchronized here!</description>
    <inlineHelpText>Email domain to use for Outreach sequences, system emails to customers sent via Salesforce, and for PostGrid to send AR warning letters to customers. NetSuite adds a CC recipient automatically for all agreements of renewal Quotes (CC to &quot;renewals@OutboundEmailDomain&quot;). This value can ONLY be changed from NetSuite and it&apos;s automatically synchronized here!</inlineHelpText>
    <label>Outbound Email Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Product_Configuration__c/fields/Renewal_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specify if the renewal service is running for the product family (disable certain automation processes when false)</description>
    <inlineHelpText>Specify if the renewal service is running for the product family (disable certain automation processes when false)</inlineHelpText>
    <label>Renewal Enabled</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/InitiateRenewalProcessHandlerTest.cls
@isTest
public class InitiateRenewalProcessHandlerTest {
    static final String LABEL_FAKE_ACCOUNT = 'Fake account';
    static final STRING ROLE_DISTRIBUTOR = 'Distributor';
    static final String ROLE_RESELLLER = 'VAR/Reseller';
    static final String USER_PROFILE = 'System Administrator';
    static final String USER_ROLE = 'ISR Renewals';
    static final String MANAGER_PROFILE = 'Team Manager';
    static final String MANAGER_ROLE = 'Manager New Sales';
    @isTest
    static void testOnOutReachTransitionWithoutSurvey() {
        TestData.createOpportunityForCPQDocument('Renewal','ACRM');
        //create test data for class
        Opportunity testOpportunity = [SELECT Id, StageName,OwnerId,Product_Configuration__c 
                                       FROM Opportunity WHERE Type='Renewal' limit 1];
        TestData.createDummyTemplate(true, System.Label.IntroTemplateWithLink , 
                                     System.Label.IntroTemplateWithLink);
        
        TestData.createDummyTemplate(true, System.Label.IntroTemplateWithoutLink,System.Label.IntroTemplateWithoutLink);
        Product_Configuration__c config = new Product_Configuration__c(
        Id=testOpportunity.Product_Configuration__c,
        Mailbox_Override__c='ignitetech.com',
        Renewal_Enabled__c=true);
        update config;
        User userManager = TestData.getUser(MANAGER_PROFILE);
        TestData.updateUserRole(userManager, MANAGER_ROLE);
        User testUser = TestData.createTestUser(USER_PROFILE, USER_ROLE, TestData.PRODUCT_FAMILY, userManager);
        testOpportunity.StageName = 'Pending';
        testOpportunity.OwnerId = testUser.Id;
        update testOpportunity;
        //start test
        Test.startTest();
        testOpportunity.StageName = 'OutReach';
        update testOpportunity;
        Test.stopTest();
    } 
    @isTest(seeAllData=true)
    static void testOnOutReachWithSurvey() {
        //start test
        Opportunity testOpportunity = TestData.createOpportunityForCPQDocument('Renewal','ACRM');
        Id productConfigId = [SELECT Product_Configuration__c 
                              FROM Opportunity
                              WHERE Id =:testOpportunity.Id ][0].Product_Configuration__c;
        //create test data for class
        TestData.createDummyTemplate(true, System.Label.IntroTemplateWithLink , 
                                     System.Label.IntroTemplateWithLink);
        TestData.createDummyTemplate(true, System.Label.IntroTemplateWithoutLink,System.Label.IntroTemplateWithoutLink);
        Id testSurveyId = [SELECT Id from Survey limit 1][0].Id;
        Product_Configuration__c config = new Product_Configuration__c(
        Id=productConfigId,
        Mailbox_Override__c='ignitetech.com',
        Renewal_Enabled__c=true,
        Intro_Survey__c=testSurveyId
        );
        update config;
        User userManager = TestData.getUser(MANAGER_PROFILE);
        TestData.updateUserRole(userManager, MANAGER_ROLE);
        User testUser = TestData.createTestUser(USER_PROFILE, USER_ROLE, TestData.PRODUCT_FAMILY, userManager);
        testOpportunity.StageName = 'Pending';
        testOpportunity.OwnerId = testUser.Id;
        update testOpportunity;
        //start test
        Test.startTest();
        testOpportunity.StageName = 'OutReach';
        update testOpportunity;
        Test.stopTest();
    }
    @isTest(seeAllData=true)
    static void testOnOutReachWithInvalidContact() {
        //start test
        Opportunity testOpportunity = TestData.createOpportunityForCPQDocument('Renewal','ACRM');
        Id productConfigId = [SELECT Product_Configuration__c 
                              FROM Opportunity
                              WHERE Id =:testOpportunity.Id ][0].Product_Configuration__c;
        //create test data for class
        TestData.createDummyTemplate(true, System.Label.IntroTemplateWithLink , 
                                     System.Label.IntroTemplateWithLink);
        TestData.createDummyTemplate(true, System.Label.IntroTemplateWithoutLink,System.Label.IntroTemplateWithoutLink);
        Id testSurveyId = [SELECT Id from Survey limit 1][0].Id;
        Product_Configuration__c config = new Product_Configuration__c(
        Id=productConfigId,
        Mailbox_Override__c='ignitetech.com',
        Renewal_Enabled__c=true,
        Intro_Survey__c=testSurveyId
        );
        update config;
        User userManager = TestData.getUser(MANAGER_PROFILE);
        TestData.updateUserRole(userManager, MANAGER_ROLE);
        User testUser = TestData.createTestUser(USER_PROFILE, USER_ROLE, TestData.PRODUCT_FAMILY, userManager);
        testOpportunity.StageName = 'Pending';
        testOpportunity.OwnerId = testUser.Id;
        update testOpportunity;
        //start test
        Test.startTest();
        testOpportunity.StageName = 'OutReach';
        List<OpportunityContactRole> lstOCR = [SELECT ID from OpportunitycontactRole 
                                                where OpportunityId=:testOpportunity.Id];
        delete lstOCR;
        update testOpportunity;
        Test.stopTest();
    }
}