metadata/sf-prod/force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>This is the quote that will be processed and sent to the customer when you move the opportunity to Final Quote. Opportunity products and all the calculations are based on this quote.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Quality_Bars_Configuration__c/Quality_Bars_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Quality Bars Configuration to enable and disable validation rules</description>
    <label>Quality Bars Configuration</label>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Quality_Bars_Configuration__c/fields/Disabled_Opportunity_QBs__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Opportunity_QBs__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true validation rules for the Opportunity object will be disabled</description>
    <inlineHelpText>If true validation rules for the Opportunity object will be disabled</inlineHelpText>
    <label>Disabled Opportunity QBs</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/TaskTriggerHandler.cls
/**
 * @description: LAMBDA-58199 Trigger handler for Task object
 */
public without sharing class TaskTriggerHandler {

    public static void validateTasks(List<Task> newRecords) {
        if(currentUserHasByPass()) {
            return;
        }
        validateRelatedOpportunities(newRecords, 'Renewal Call', System.Label.TaskRenewalCallMessage);
        validateRelatedOpportunities(newRecords, 'Price Reset Call', System.Label.TaskPriceResetCallMessage);
    }
    private static void validateRelatedOpportunities(List<Task> newRecords, string taskSubject, string errorMessage) {
        Set<Id> setRelatedOpportunityIds = new Set<Id>();
        Set<Task> setaffectedTasks = new Set<Task>();
        for(Task tsk : newRecords) {
            String whatId = (String)tsk.WhatId;
            if(whatId!=null && whatId.startsWithIgnoreCase('006') 
                && tsk.Subject.containsIgnoreCase(taskSubject) 
                && (tsk.Type=='Call' || tsk.Type==null)) {
                    setRelatedOpportunityIds.add(whatId);
                    setaffectedTasks.add(tsk);
            }
        }
        Map<Id,Opportunity> queriedOpportunities = fetchRelatedOpportunities(setRelatedOpportunityIds);
        addErrorMessage(queriedOpportunities,setaffectedTasks, errorMessage);
    }
    private static Map<Id,Opportunity> fetchRelatedOpportunities(Set<Id> setOpportunityId) {
        Map<Id,Opportunity> mapOpportunityToReturn = new Map<Id,Opportunity>();
        if(setOpportunityId!=null && !setOpportunityId.isEmpty()) {
            mapOpportunityToReturn = new Map<Id,Opportunity>([SELECT Id, 
            StageName, SBQQ__PrimaryQuote__c FROM Opportunity
            WHERE Id IN: setOpportunityId AND (SBQQ__PrimaryQuote__c=null OR  HasOpportunityLineItem=false)]);
        }
        return mapOpportunityToReturn;
    }
    private static void addErrorMessage(Map<Id,Opportunity> mapQueriedOppys,
      Set<Task> setaffectedTasks,string errorMessage) {
        if(setaffectedTasks.isEmpty() || mapQueriedOppys==null || mapQueriedOppys.isEmpty()) {
            return;
        }
        //add messages to non-eligible tasks
        for(Task tsk : setaffectedTasks) {
            if(mapQueriedOppys.containsKey(tsk.WhatId)) {
                tsk.addError(errorMessage);
            }
        }
    }
    public static boolean currentUserHasByPass() {
        Quality_Bars_Configuration__c qualityBars = Quality_Bars_Configuration__c.getInstance();
        if(qualityBars!=null && qualityBars.Disabled_Opportunity_QBs__c) {
            return true;
        }
        return false;
    }
}