metadata/sf-prod/force-app/main/default/objects/Quality_Bars_Configuration__c/Quality_Bars_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Quality Bars Configuration to enable and disable validation rules</description>
    <label>Quality Bars Configuration</label>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/Quality_Bars_Configuration__c/fields/Disabled_Opportunity_QBs__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Opportunity_QBs__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true validation rules for the Opportunity object will be disabled</description>
    <inlineHelpText>If true validation rules for the Opportunity object will be disabled</inlineHelpText>
    <label>Disabled Opportunity QBs</label>
    <type>Checkbox</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/OpportunityQBDisable.cls
public with sharing class OpportunityQBDisable {
    //Adding a new setting with setup owner as the current user will disable the QBs only for the current user.
    @InvocableMethod(label='Disable opportunity quality bars for current user')
    public static void execute() {
        Id userId = UserInfo.getUserId();
        List<Quality_Bars_Configuration__c> qbConfigs = [SELECT Disabled_Opportunity_QBs__c 
            FROM Quality_Bars_Configuration__c WHERE SetupOwnerId = :userId];
        Quality_Bars_Configuration__c qbConfig;
        if (qbConfigs.size() == 0) {
            qbConfig = new Quality_Bars_Configuration__c();
            qbConfig.SetupOwnerId = userId;
        } else {
            qbConfig = qbConfigs[0];
        }
        qbConfig.Disabled_Opportunity_QBs__c = true;
        upsert qbConfig;
    }
}