metadata/sf-prod/force-app/main/default/objects/QC_Rule__c/QC_Rule__c.object-meta.xml
<CustomObject>
    <label>QC Rule</label>
    <nameField>
        <label>QC Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/QC_Rule__c/fields/Enforced_On__c.field-meta.xml
<CustomField>
    <fullName>Enforced_On__c</fullName>
    <label>Enforced On</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Work_Unit_Types</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule__c/fields/Metric_Field_Path__c.field-meta.xml
<CustomField>
    <fullName>Metric_Field_Path__c</fullName>
    <label>Metric Field Path</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule_Result__c/QC_Rule_Result__c.object-meta.xml
<CustomObject>
    <label>QC Rule Result</label>
    <nameField>
        <label>QC Rule Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Rule Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/QC_Rule_Result__c/fields/Metric_Value__c.field-meta.xml
<CustomField>
    <fullName>Metric_Value__c</fullName>
    <label>Metric Value</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule_Result__c/fields/QC_Rule__c.field-meta.xml
<CustomField>
    <fullName>QC_Rule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>QC Rule</label>
    <referenceTo>QC_Rule__c</referenceTo>
    <relationshipLabel>QC Rule Results</relationshipLabel>
    <relationshipName>QC_Rule_Results</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule_Result__c/fields/QC_Scorecard__c.field-meta.xml
<CustomField>
    <fullName>QC_Scorecard__c</fullName>
    <label>QC Scorecard</label>
    <referenceTo>QC_Scorecard__c</referenceTo>
    <relationshipLabel>QC Rule Results</relationshipLabel>
    <relationshipName>QC_Rule_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Scorecard__c/QC_Scorecard__c.object-meta.xml
<CustomObject>
    <label>QC Scorecard</label>
    <nameField>
        <label>QC Scorecard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Scorecards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/QC_Scorecard__c/fields/QC_Summary__c.field-meta.xml
<CustomField>
    <fullName>QC_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>QC Summary</label>
    <referenceTo>QC_Summary__c</referenceTo>
    <relationshipLabel>QC Scorecards</relationshipLabel>
    <relationshipName>QC_Scorecards</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Summary__c/QC_Summary__c.object-meta.xml
<CustomObject>
    <description>Quality Check Summary object provides insights for a work unit, specifically it shows if work unit completed per defined quality. If some quality bars are not satisfied then comments provided with the explanation.</description>
    <label>QC Summary</label>
    <nameField>
        <label>QC Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/QC_Summary__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QC_Result</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/Task_Dispatcher__c/Task_Dispatcher__c.object-meta.xml
<CustomObject>
    <label>Task Dispatcher</label>
    <nameField>
        <label>Task Dispatcher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Dispatchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/TCAP__Call_Coach_Metrics__c/TCAP__Call_Coach_Metrics__c.object-meta.xml
<CustomObject>
    <description>Object to keep Call Coach metrics for a call</description>
    <label>Call Coach Metrics</label>
    <nameField>
        <displayFormat>CCM-{00000000}</displayFormat>
        <label>Call Coach Metrics</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Coach Metrics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/TCAP__Call_Coach_Metrics__c/fields/TCAP__Call_Duration__c.field-meta.xml
<CustomField>
    <fullName>TCAP__Call_Duration__c</fullName>
    <description>Total call duration in seconds</description>
    <inlineHelpText>Total call duration in seconds</inlineHelpText>
    <label>Call Duration</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/QCHelperTest.cls
@isTest(seeAllData = false)
public class QCHelperTest {
    
    @IsTest
    static void fillGradingFields_ShouldFillValueWhenOkay() {
        String callDurationField = 'Call Coach Metrics.Call Duration';
        QC_Summary__c summary = new QC_Summary__c();
        insert summary;
        QC_Scorecard__c scorecard = new QC_Scorecard__c();
        scorecard.QC_Summary__r = summary;
        scorecard.QC_Summary__c = summary.Id;
        insert scorecard;
        Task task = new Task();
        task.QC_Summary__r = summary;
        task.QC_Summary__c = summary.Id;
        insert task;
        QC_Rule__c rule = new QC_Rule__c();
        rule.Enforced_On__c = 'Renewal Call';
        rule.Metric_Field_Path__c = callDurationField;
        insert rule;
        QC_Rule_Result__c result = new QC_Rule_Result__c();
        result.QC_Rule__r = rule;
        result.QC_Rule__c = rule.Id;
        result.QC_Scorecard__r = scorecard;
        result.QC_Scorecard__c = scorecard.Id;
        result.Result__c = 'Unable To Grade';
        insert result;
        System.assert(result.QC_Scorecard__r != null);
        // no metrics
        Task[][] tasks = new Task[][]{ new Task[]{ task }};
        result = QCHelper.fillGradingFields(tasks).get(0).get(0);
        System.assertEquals(null, result.Metric_Value__c);
        // result already set
        TCAP__Call_Coach_Metrics__c metrics = new TCAP__Call_Coach_Metrics__c();
        metrics.TCAP__Call_Duration__c = 44;
        insert metrics;
        task.TCAP__Call_Coach_Metrics__r = metrics;
        task.TCAP__Call_Coach_Metrics__c = metrics.Id;
        update task;
        rule.Metric_Field_Path__c = callDurationField;
        update rule;
        result.Result__c = 'Fail';
        update result;
        SObject obj = task;
        obj = obj.getSObject('TCAP__Call_Coach_Metrics__r');
        System.assertEquals(44, obj.get('TCAP__Call_Duration__c'));
        QC_Rule_Result__c[] results = QCHelper.fillGradingFields(tasks).get(0);
        System.assertEquals(0, results.size());
        // no metric field
        result.Result__c = null;
        update result;
        rule.Metric_Field_Path__c = null;
        update rule;
        results = QCHelper.fillGradingFields(tasks).get(0);
        System.assertEquals(0, results.size());
        // invalid metric field: not exists
        rule.Metric_Field_Path__c = 'Garbage.More Garbage';
        update rule;
        result = QCHelper.fillGradingFields(tasks).get(0).get(0);
        System.assertEquals(null, result.Metric_Value__c);
        // invalid metric field: not a number
        rule.Metric_Field_Path__c = 'Call Coach Metrics.Call Coach Metrics';
        update rule;
        result = QCHelper.fillGradingFields(tasks).get(0).get(0);
        System.assertEquals(null, result.Metric_Value__c);
        // okay
        rule.Metric_Field_Path__c = callDurationField;
        update rule;
        result = QCHelper.fillGradingFields(tasks).get(0).get(0);
        System.assertEquals(44, result.Metric_Value__c);
    }
        
    @IsTest
    static void getApiPath_ShouldReturnApiNames() {
        System.assertEquals('Type', QCHelper.getApiPath('Task', 'Type'));
        System.assertEquals('QC_Summary__r.Name', QCHelper.getApiPath('Task', 'QC Summary.QC Summary Name'));
        System.assertEquals(null, QCHelper.getApiPath('Task', 'Not_A_Valid_Field__c'));
        System.assertEquals(null, QCHelper.getApiPath('Task', null));
    }
    
    @IsTest
    static void getPathValue_ShouldReturnValue() {
        QC_Summary__c summary = new QC_Summary__c();
        Task t = new Task(Type = 'Call', QC_Summary__r=summary);
        System.assertEquals('Call', QCHelper.getPathValue(t, 'Type'));
        System.assertEquals(summary, QCHelper.getPathValue(t, 'QC_Summary__r'));
        System.assertEquals(null, QCHelper.getPathValue(t, null));
        System.assertEquals(null, QCHelper.getPathValue(t, 'Task_Dispatcher__c.Name'));
    }
}