metadata/sf-prod/force-app/main/default/objects/QC_Rule__c/QC_Rule__c.object-meta.xml
<CustomObject>
    <label>QC Rule</label>
    <nameField>
        <label>QC Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/QC_Rule__c/fields/Metric_Field_Path__c.field-meta.xml
<CustomField>
    <fullName>Metric_Field_Path__c</fullName>
    <label>Metric Field Path</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule_Result__c/QC_Rule_Result__c.object-meta.xml
<CustomObject>
    <label>QC Rule Result</label>
    <nameField>
        <label>QC Rule Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Rule Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/QC_Rule_Result__c/fields/Metric_Value__c.field-meta.xml
<CustomField>
    <fullName>Metric_Value__c</fullName>
    <label>Metric Value</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule_Result__c/fields/QC_Rule__c.field-meta.xml
<CustomField>
    <fullName>QC_Rule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>QC Rule</label>
    <referenceTo>QC_Rule__c</referenceTo>
    <relationshipLabel>QC Rule Results</relationshipLabel>
    <relationshipName>QC_Rule_Results</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Rule_Result__c/fields/QC_Scorecard__c.field-meta.xml
<CustomField>
    <fullName>QC_Scorecard__c</fullName>
    <label>QC Scorecard</label>
    <referenceTo>QC_Scorecard__c</referenceTo>
    <relationshipLabel>QC Rule Results</relationshipLabel>
    <relationshipName>QC_Rule_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Scorecard__c/QC_Scorecard__c.object-meta.xml
<CustomObject>
    <label>QC Scorecard</label>
    <nameField>
        <label>QC Scorecard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Scorecards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/QC_Scorecard__c/fields/QC_Summary__c.field-meta.xml
<CustomField>
    <fullName>QC_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>QC Summary</label>
    <referenceTo>QC_Summary__c</referenceTo>
    <relationshipLabel>QC Scorecards</relationshipLabel>
    <relationshipName>QC_Scorecards</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/sf-prod/force-app/main/default/objects/QC_Summary__c/QC_Summary__c.object-meta.xml
<CustomObject>
    <description>Quality Check Summary object provides insights for a work unit, specifically it shows if work unit completed per defined quality. If some quality bars are not satisfied then comments provided with the explanation.</description>
    <label>QC Summary</label>
    <nameField>
        <label>QC Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/sf-prod/force-app/main/default/objects/QC_Summary__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QC_Result</valueSetName>
    </valueSet>
</CustomField>

metadata/sf-prod/force-app/main/default/classes/QCHelper.cls
public class QCHelper {
    
    @InvocableMethod(label='Set QC_Rule_Result for Grading' 
                     description='Resolve metric field path from QC Rule and fill thresholds in QC Rule Result')
    public static QC_Rule_Result__c[][] fillGradingFields(Task[][] taskIds) {
        Map<String, String> apiPaths = new Map<String, String>();
        List<QC_Rule_Result__c[]> batches = new List<QC_Rule_Result__c[]>();
        for (Task[] ts : taskIds) {
            Set<Id> summaryIds = new Set<Id>();
            for (Task t : ts) {
                if (t.QC_Summary__c != null) {
                    summaryIds.add(t.QC_Summary__c);
                }
            }
            List<QC_Scorecard__c> scorecards = [SELECT Id FROM QC_Scorecard__c WHERE QC_Summary__c IN :summaryIds];
            List<Id> scorecardIds = new List<Id>();
            for (QC_Scorecard__c scorecard : scorecards) {
                scorecardIds.add(scorecard.Id);
            }
            List<QC_Rule_Result__c> results = [
                SELECT Id, QC_Scorecard__r.QC_Summary__c, QC_Rule__r.Metric_Field_Path__c
                FROM QC_Rule_Result__c
                WHERE QC_Scorecard__c IN :scorecardIds
                AND QC_Rule__r.Metric_Field_Path__c != NULL
                AND (Result__c = NULL OR Result__c = 'Unable To Grade')
            ];
            Set<String> fieldPaths = new Set<String>();
            for (QC_Rule_Result__c res : results) {
                fieldPaths.add(res.QC_Rule__r.Metric_Field_Path__c);
            }
            List<String> query = new List<String>();
            query.add('SELECT Id, QC_Summary__c');
            for (String field : fieldPaths) {
                String apiPath = getApiPath('Task', field);
                if (apiPath != null) {
                    apiPaths.put(field, apiPath);
                    query.add(', '+apiPath);
                }
            }
            query.add('FROM Task WHERE QC_Summary__c IN :summaryIds');
            Map<Id, Task> tasks = new Map<Id, Task>();
            for (Task task : Database.query(String.join(query,' '))) {
                tasks.put(task.QC_Summary__c, task);
            }
            updateResults(tasks, apiPaths, results);
            batches.add(results);
        }
        return batches;
    }

    private static void updateResults(Map<Id, Task> tasks, 
            Map<String, String> apiPaths, List<QC_Rule_Result__c> results) {
        for (QC_Rule_Result__c res : results) {
            Task task = tasks.get(res.QC_Scorecard__r.QC_Summary__c);
            String apiPath = apiPaths.get(res.QC_Rule__r.Metric_Field_Path__c);
            if (apiPath == null) {
                res.Metric_Value__c = null;
            } else {
                try {
                    res.Metric_Value__c = (Decimal) getPathValue(task, apiPath);
                } catch (TypeException cause) {
                    String msg = 'Metric Field Path of QC Rule {0} is not a Number';
                    String[] args = new String[] { res.QC_Rule__c };
                    System.debug(String.format(msg, args));
                    res.Metric_Value__c = null;
                }
            }
        }
        update results;
    }
    
    public static String getApiPath(String baseType, String fieldPath) {
        if (fieldPath == null) return null;
        SObjectType objType = Schema.getGlobalDescribe().get(baseType);
        List<String> pathNodes = fieldPath.split('[.]');
        List<String> path = new List<String>();
        for (String fieldLabel : pathNodes) {
            Map<String, Schema.SObjectField> fieldMap = objType.getDescribe().fields.getMap();
            for (String fieldName : fieldMap.keySet()) {
                Schema.SObjectField field = fieldMap.get(fieldName);
                Schema.DescribeFieldResult fieldDesc = field.getDescribe();
                if (fieldDesc.getLabel() == fieldLabel) {
                    path.add(fieldDesc.getName());
                    List<Schema.SObjectType> refs = fieldDesc.getReferenceTo();
                    if (refs.isEmpty()) {
                        return String.join(path,'.').replace('__c.','__r.');
                    } else {
                        objType = refs.get(0);
                        break;
                    }
                }
            }
        }
        return null;
    }
    
    public static Object getPathValue(SObject record, String fieldPath) {
        if (fieldPath == null) return null;
        SObject obj = record;
        List<String> fields = fieldPath.split('[.]');
        for (String field : fields) {
            if (obj == null) return null;
            try {
                obj = obj.getSObject(field);
            } catch (SObjectException e) {
                return obj.get(field);
            }
        }
        return obj;
    }
    
}